### ISSUE TITLE
Permits by City Department, Report 1 (On PROD) (SB)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#5576] opened 2021-03-23 17:55 UTC
**Stakeholder:** Ryan M.

Main Report Sample Layout:

![image.png](https://images.zenhubusercontent.com/5f50fe1f66d1a40f7f557fb4/a8d1a3fc-7ec2-46d2-b7e9-cbe0e3ad6b9c) 

Acceptance Criteria: 

- From Date, To Date and Department should be available to select as report parameters. 
- From Date and To Date is based on Folder InDate.
- Department should have the same options as info 76765.
- If no Department value is chosen, report should pull details of all departments. 
- Report should pull data from EX folder (all subtypes) and RW folder (Temporary Right of Way Subtype ONLY). 
- Each department should have two tables in the report; one for folder type EX and one for folder type RW. 
- The data contained in the Main Report should come from the following sources: 
-- Submitted: Any folder that has InDate field populated 
-- Issued: Any folder that has IssueDate field populated
-- CIP: Any folder where info 76352 "CIP?" is populated as "Yes" 
-- Non-CIP: Any folder where info 76352 "CIP?" is populated as "No" 
-- Primary: Any folder where folderPriority is 3
-- Secondary: Any folder where folderPriority is 4
-- Emergency: Any folder where folderPriority is 1
-- Other: Any folder where folderPriority is NOT 1, 3 or 4 will be a 2
  
Subreport (Drill-Down) Sample Layout: 

![image.png](https://images.zenhubusercontent.com/5f50fe1f66d1a40f7f557fb4/a31e67dd-24b5-4471-a259-3a3530e9598a)

- Each department should have two tables in the report; one for folder type EX and one for folder type RW. 
- The data contained in the Subreport should come from the following sources:
-- Permit Number:  Folder Reference Number
-- Folder Name: Folder Name
-- CIP (Yes/No): Based on value provided in Info 76352
-- CIP Number: Value provided in Info 76350
-- CIP Project Manager: Value provided in Info 76360
-- Applicant Name: Contact field of Applicant People Record in the folder

![image.png](https://images.zenhubusercontent.com/5cca1e522b8dfc0ee14dedf5/bbe6d14b-aea3-4f4a-bdf3-b8da0cf6f12e)

**Comment by vschandramouli** [comment] 2021-04-06 18:13
Outstanding items to discuss: 

1. Report format (PDF, XLS) and layout need to be finalized.

**Comment by vschandramouli** [comment] 2021-04-12 22:08
Possible report layout: to be confirmed with Ryan 

![image.png](https://images.zenhubusercontent.com/5f50fe1f66d1a40f7f557fb4/807cd517-0bc3-41c4-9e76-e744eec1ad3f)

**Comment by vschandramouli** [comment] 2021-04-13 20:29
Had a meeting with Ryan, finalized AC. Currently working on converting notes into usable AC for this ticket.

**Comment by vschandramouli** [comment] 2021-04-15 20:46
@TracyLinder @Nadin-Nader I took a first pass at writing AC for this report. Could you do a quick review and let me know what you think? It can be moved to Backlog if you think it is good to go.

**Comment by vschandramouli** [comment] 2021-04-19 20:20
Moving to Backlog as other ticket was reviewed by Tracy.

**Comment by sreelathab** [comment] 2021-05-26 13:36
@Nadin-Nader , @TracyLinder - Working on summary report.

**Comment by Nadin-Nader** [comment] 2021-05-28 18:44
##  **Status:**

This card is being and the functions are being reviewed by Sree before the actual creation of the report.

**Comment by sreelathab** [comment] 2021-06-03 13:29
@Nadin-Nader , @TracyLinder - Test Summary report format sent on 6/2/2021 for review.

![image](https://user-images.githubusercontent.com/65371095/120652943-d9280c00-c445-11eb-9640-db9bb968fc5c.png)

**Comment by sreelathab** [comment] 2021-06-07 20:30
@Nadin-Nader , @TracyLinder  - Please find the Detail report format layout for review.

![image](https://user-images.githubusercontent.com/65371095/121083557-335a0180-c7a5-11eb-8a04-9fe94a908449.png)

**Comment by sreelathab** [comment] 2021-06-09 14:31
@Nadin-Nader , @TracyLinder  - Please find the consolidated Summary & Detail report of Permits by City Department. I am still working on Testing the report. 
![image](https://user-images.githubusercontent.com/65371095/121374199-51d70e80-c905-11eb-9fab-111560935639.png)

![image](https://user-images.githubusercontent.com/65371095/121374297-67e4cf00-c905-11eb-8d84-0a2c7e53ac84.png)


![image](https://user-images.githubusercontent.com/65371095/121374279-64e9de80-c905-11eb-9753-35b3011ab6ac.png)

**Comment by Nadin-Nader** [comment] 2021-06-15 16:24
@Sreelatha-BlazeKannan can you send me the actual rpt file so i can put it on DEV since CTM doesnt usually do that for DVE and TEST.

**Comment by Nadin-Nader** [comment] 2021-06-15 17:23
@Sreelatha-BlazeKannan i have placed this on DEV but found that none of the calculations are working. I also found that the detailed Table after the Number of City Department table is overlapping the output in the "Applicant Name" Field.

[https://app.zenhub.com/files/140626918/17950c3a-4624-44ef-8def-524706229386/download]

**Comment by sreelathab** [comment] 2021-06-16 22:00
@Nadin-Nader , @TracyLinder  - Nadin, Until the object creation, New function move are completed in DEV, the report would not execute properly. I have sent the updated applicant Name/organization name corrected report for your reference. please review and let me know your thoughts.

**Comment by Nadin-Nader** [comment] 2021-06-17 17:52
I deployed this to DEV yesterday and reviewed it with Sree. We found that we cannot UAT this due o the fact that the Object needs to be created first (SCTASK0144355, Currently assigned to George Shirai). Once it's created we can run it on DEV and UAT.

**Status:** 
Waiting on George rom CTM to deploy

**Comment by Nadin-Nader** [comment] 2021-06-17 23:00
Spoke to George and he will check with Martin to see if this was done. If not he will do it tonight

**Comment by Nadin-Nader** [comment] 2021-06-18 18:16
**Status:**
This has been deployed by George to DEV and is currently being tested by us since the report is already deployed.

**Comment by Nadin-Nader** [comment] 2021-06-21 01:47
Reviewed the report on DEV and it looks good other than it not pulling any data for the date ranges i used 6/6/19-6/22/21. It also added a blank page after each table that had the CIP/Non-CIP totals. @Sreelatha-BlazeKannan we will need to find out why its inserting a blank page before moving to TEST

**Comment by Nadin-Nader** [comment] 2021-06-21 21:37
@Sreelatha-BlazeKannan Ok so i tested this on DEV and found that if i run ALL Departments it inserts a blank page after each department. If i select one department (ACC-C) I got a one page report but it had 0 numbers.

**Comment by Nadin-Nader** [comment] 2021-06-29 15:41
Tested this and it is now working as it should on DEV. I will go ahead and create on TEST then UAT.

**Status:**

Creating and UATing on TEST

**Comment by Nadin-Nader** [comment] 2021-06-29 18:56
@Sreelatha-BlazeKannan the report is created on TEST. We just need to send the commit through so that the Procedure is created. Right now the "Get Perm By Department procedure error is coming up saying its not there. We will need to send the commit to DevOps to Promote to TEST tomorrow or after you verify your changes are good.

**Comment by sreelathab** [comment] 2021-06-30 15:36
@Nadin-Nader , @TracyLinder  - TEST Deployment plan sent on 06/25/2021. Here is the commit ID : d5c1fb1b27da. Could you please create TASK ID for me. 

Note: Manual commit (Object Creation) must be done before moving the components

**Comment by Nadin-Nader** [comment] 2021-06-30 19:27
@Sreelatha-BlazeKannan I have sent this to the DevOps CM Team under **SCTASK0148682**

**Status:**
Waiting on DevOps M Team to deploy to TEST

**Comment by Sreelatha-BlazeKannan** [comment] 2021-06-30 21:45
@Nadin-Nader  - @TracyLinder  - TEST Commit deployment plan sent again today, due to the change of manual commit 
Order
1.	Manual Commit :100dfde5240f
2.	Procedural Commit : d5c1fb1b27da
3.	Report Update : 99022

**Comment by Nadin-Nader** [comment] 2021-07-01 14:40
**Status:**
Waiting on DevOps M Team to deploy to TEST

**Comment by Nadin-Nader** [comment] 2021-07-09 18:18
Sent Martin a chat to see what the ETA was for this to be deployed.

**Status:** 
Waiting on Response from Martin/DevOps

**Comment by Nadin-Nader** [comment] 2021-07-09 18:38
@Sreelatha-BlazeKannan Per Martin, this has not been deployed due to the "Manual Commit"
Per Martin:
the whole CREATE OR REPLACE TYPE COA_OBJ_DEPT_TYPE AS OBJECT section should be a commit rather than manual piece. He sent us an email with instructions on how to do it on 6/30/21

**Comment by Nadin-Nader** [comment] 2021-07-09 19:35
@Sreelatha-BlazeKannan George has deployed this to TEST

**Comment by Nadin-Nader** [comment] 2021-07-14 16:08
**Status:**

UAT on TEST in progress

**Comment by Sreelatha-BlazeKannan** [comment] 2021-07-14 19:19
@Nadin-Nader , @TracyLinder - found a bug while testing with data in test reverted and re-submitted the Procedural commit only; here is the commit id : 0d3f11661529

**Comment by Nadin-Nader** [comment] 2021-07-16 17:06
@Sreelatha-BlazeKannan this has been deployed to DEV. Please UAT

**Comment by Sreelatha-BlazeKannan** [comment] 2021-07-20 13:46
** Status **
DEV Testing is in progress

**Comment by Sreelatha-BlazeKannan** [comment] 2021-07-21 22:04
@Nadin-Nader , @TracyLinder  - 

@Nadin-Nader,

As we discussed I will continue to display in the summary report both submitted and issued counts,  though there is redundancy in data. i.e., submitted record (in date) has both in date and issued date then the record will get counted in both submitted as well as in issued. 

I need one more clarification, before sending the DEV commit. 
Can I suppress the empty/0 valued summary & Detail report? I was already doing the same for the Detail report. However now I felt like doing it for summary also. Otherwise, when we give ‘ALL’ option it will pull all department's data whether the values are available or not, it displays as ‘0’. Instead if I suppress then the report will show all departments that has the data and the remaining will not be displayed.

**Comment by Nadin-Nader** [comment] 2021-07-22 15:07
Asked Darren and Ryan if they want it suppressed or to show 0. 
**Status:** 
Waiting on response

**Comment by Nadin-Nader** [comment] 2021-07-26 15:03
@Sreelatha-BlazeKannan I spoke to Ryan Mooney and he said that he will defer the decisions to us. So if it makes it cleaner, lets suppress. My only concern is that they may want to know what has a 0 value later

**Comment by Sreelatha-BlazeKannan** [comment] 2021-07-26 21:04
@Nadin-Nader , @TracyLinder - As per our conversation i suggest to suppress at this point; later if we want them to display all 0 departments. then will add one more subreport just to display 0 value departments; that way the report will look tidy.

Created DEV Procedural commit for COA_DECLARE, F_COA_GET_PERM_BY_DEPT_REPORT components. Here is the commit id: c8ecbbc5c52a, please approve and create task for me.

**Comment by Nadin-Nader** [comment] 2021-07-26 22:11
@Sreelatha-BlazeKannan I have sent this to the DevOps Team for deployment to DEV under **SCTASK0154771**

I also put the report on DEV.

**Status:**
Waiting on DevOps CM Team to deploy to DEV

**Comment by Nadin-Nader** [comment] 2021-07-30 17:46
@Sreelatha-BlazeKannan can you please UAT this on DEV and let me know the status.

**Status:**
This had a commit conflict and was resolved by Martin and Sree. This is on DEV and needs to be UATd

**Comment by Nadin-Nader** [comment] 2021-08-05 23:42
@Sreelatha-BlazeKannan can you update this with its current status please.

**Comment by Sreelatha-BlazeKannan** [comment] 2021-08-06 13:52
@Nadin-Nader , @TracyLinder - As per Nadin its moved to DEV. I will have to do DEV testing.

**Comment by TracyLinder** [comment] 2021-08-20 18:11
I'm moving this to the backlog until the fee updates are done.

**Comment by TracyLinder** [comment] 2022-01-20 22:03
@Nadin-Nader this may be a good candidate for work during the code freeze.
I'm removing this from the FY22 fee epics.

**Comment by TracyLinder** [comment] 2022-10-11 19:34
Per Paloma, she is currently manually calculating this data. They are required to submit this data annually; Jim wanted quarterly.

**Comment by Nadin-Nader** [comment] 2023-01-05 14:43
Subha has created an incident to get required Amanda admin privileges to test. Waiting on that.

**Comment by SubhaShroff** [comment] 2023-01-06 15:38
Anu has worked on above incident and I can access the report. I tested the report on DEV. I have to fix the following:

-  one of the totals are not displaying
- Department Parameter should have default value as 'All' and a list of departments drop- down

**Comment by SubhaShroff** [comment] 2023-01-09 23:33
Status Update: The Security group assignment tha Anu did is not shown on Dev. Have asked her to look at it.

**Comment by TracyLinder** [comment] 2023-01-13 20:39
@SubhaShroff i don't have DEV access. Can you please attach the report?

**Comment by SubhaShroff** [comment] 2023-01-13 20:55
@TracyLinder  @Nadin-Nader  The report disappeared from DEV report Menu for the second time. Basically, security group (ATD) that my login user associated should be added to the Menu Report(99022). As I don't have privilege I had raised a ticket and  Anu has fixed it. But its gone again. Have pinged Anu and waiting for her response and fix.

**Comment by SubhaShroff** [comment] 2023-01-17 20:05
@Nadin-Nader  @TracyLinder 
Here are the sample data attached. Please review.
[99022_Permits_by_City_Department_Report_All.pdf](https://github.com/cityofaustin/atd-data-tech/files/10438869/99022_Permits_by_City_Department_Report_All.pdf)
[ATD - Permits by City Department (99022)-ACC-C Result.pdf](https://github.com/cityofaustin/atd-data-tech/files/10438871/ATD.-.Permits.by.City.Department.99022.-ACC-C.Result.pdf)

**Comment by SubhaShroff** [comment] 2023-02-02 15:15
### Status:
Waiting for Ryan's feedback on the sample reports sent in email. The same samples attached in the above comment also. Today, I sent a follow up email to Ryan.
@Nadin-Nader  @TracyLinder

**Comment by SubhaShroff** [comment] 2023-02-06 20:07
@Nadin-Nader  Since Ryan responded through email that report looks good, I have submitted TEST deployment request - SCTASK0284480.

**Comment by SubhaShroff** [comment] 2023-02-07 20:46
@Nadin-Nader  This is deployed in TEST and available as Menu Report. I tested it and looks good to me. Ready for UAT.

**Comment by Nadin-Nader** [comment] 2023-02-17 00:50
Sent email to Ryan asking him to UAT on TEST

**Comment by SubhaShroff** [comment] 2023-02-24 14:52
### Status:
Ready for UAT on TEST for last two weeks.

**Comment by TracyLinder** [comment] 2023-02-24 20:14
### Test Notes

- Data validation failed on ATD on EX. 
- Searching manually only found one record 


![Screenshot 2023-02-24 at 2.13.09 PM.png](https://images.zenhubusercontent.com/5cca1e522b8dfc0ee14dedf5/d7d09d39-edf4-4003-9f7a-017f92825fea)

**Comment by TracyLinder** [comment] 2023-02-24 20:56
### Approved for PROD

**Comment by SubhaShroff** [comment] 2023-02-24 21:40
@TracyLinder  @Nadin-Nader  PROD promotion request is raised - SCTASK0289840.

**Comment by SubhaShroff** [comment] 2023-03-09 14:51
@Nadin-Nader  This is good, verified on PROD.

**Comment by SubhaShroff** [comment] 2023-03-17 19:41
Today, in the call Paloma mentioned that we still wait on this ticket before closing.

**Comment by Nadin-Nader** [comment] 2023-03-24 19:06
The data we found we correct. Per Ryan we can close

**Closed by Nadin-Nader** 2023-03-24 19:06 UTC
Labels: Workgroup: ROW, Need: 1-Must Have, Type: Reports, Product: AMANDA, Provider: LaunchIT
