### ISSUE TITLE
Change the way Activate Upon Payment Features from ROW Permit Folders behave (On PROD🎉🎉)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#6255] opened 2021-05-28 19:39 UTC
### ROW is considering removing the Activate Upon Payment features from their permit folders. 

**Acceptance Criteria**

- When an applicant makes a payment on DS, EX and RW folders through the portal and folder status is changed to 'Active', system should automatically update 'Activate Upon Payment' Info value (75001) to 'No'. 

**Batch Job(s):**
System must check everyday as part of a batch job to validate whether it has been 7 calendar days since the most recent bill on an DS, EX or RW folder was created. If 7 calendar days have passed since the last invoice on a DS, EX or RW folder was created and the invoice has not yet been paid, system must:
1.  Update 'Activate Upon Payment' Info (75001) to 'No'  on the folder 
2. Send an e-mail to the 'Applicant' type People Record associated with the folder. 
    - Only send the folder applicant 1 email reminder.
    - The e-mail body is provided below: 

Hello,
Please notify your analyst once payment has been made on permit *Permit Number*. 

![RW Activate Upon Payment Workflow](https://user-images.githubusercontent.com/49930868/145621344-aead2f5c-b00a-4773-a50c-6c966eb61791.jpg)

![TURP Permit Extension - Extension Granted (1)](https://user-images.githubusercontent.com/49930868/145621364-8145e777-3b43-4b69-9ee3-5f2a4f1ab8cf.jpg)

**Comment by TracyLinder** [comment] 2021-06-15 19:56
**Stakeholder Update**
The ROW team discussed this and found that the feature is often not being used because of various issues/pain points
They'd still like to use it, but update the feature so it works for them

1. After permit issued, can activate upon payment be automatically updated to No? 
2. If no fee is paid within a certain time frame, can activate upon payment be automatically updated to No?
    - Maybe 5 days after invoice date?
    - This would prevent the system from issuing a permit when the customer pays the fee after the event start date. Staff may need to redo coordination when this happens.

**Comment by TracyLinder** [comment] 2021-07-21 19:52
Activate upon payment features on TURP are being updated on #1802.

**Comment by vschandramouli** [comment] 2021-09-03 19:23
Email to applicant. 

Body of the email: 

Hello, 
Please notify your analyst once payment has been made on permit *Permit Number*.

**Comment by vschandramouli** [comment] 2021-09-15 13:38
Updated Acceptance Criteria. Moving to Backlog.

**Comment by Nadin-Nader** [comment] 2021-11-02 14:40
Sent email to Paloma and Kim asking them the above. See the email below:


> To: Amayo-Ryan, Paloma <Paloma.Amayo-Ryan@austintexas.gov>; Perez, Kimberly <Kimberly.Perez@austintexas.gov>
> Cc: Linder, Tracy <Tracy.Linder@austintexas.gov>
> Subject: Questions on Card # 6255 Remove Activate Upon Payment from ROW Permit Folders
> Importance: High
> 
> Hello Ladies,
> 
> I hope you are having a great day. I was reaching out regarding card 6255 where it is requested to remove the Activate Upon Payment from ROW Permit folders. Subha is currently working on this but has a few questions she needs answers to in order to continue. Questions are below:
> 
> o	Is it an exclusion for COS autopayments of EX, RW TURP from COS Payment Automation - TURP & EX New Permit Fees (UAT On DEV) #7162 ? Otherwise, I see a conflict.
> o	Please specify the Sub & Work combinations for each Permit(if it applies for specific sub & work).
> o	What are the valid Permit statuses to check in the Batch Job to send email and change the status?
> o	Are there any other conditions to check, before sending an email to the applicant about the payment due?
> Once I get the answers, Subha can continue her work.
> 
> Respectfully,
> 
> Nadin A. Nader (He/Him/His)
> Product Delivery Manager

**Comment by SubhaShroff** [comment] 2021-11-03 13:46
### Status:
Work in Progress and waiting for the responses from Paloma/Kim.

**Comment by Nadin-Nader** [comment] 2021-11-03 15:58
**Status:**
Vish has updated Subha and she is currently working on this

**Comment by TracyLinder** [comment] 2021-11-03 16:04
@vschandramouli can you please update the AC with the feedback you provided Subha? Thank you.

**Comment by Nadin-Nader** [comment] 2021-11-04 19:18
Received an email from Paloma with UAT results:

![image.png](https://images.zenhubusercontent.com/5e8dfbfabf171441c3a5684e/8987c18b-cd6d-4daa-974b-bd4bff07df0a)

**Comment by SubhaShroff** [comment] 2021-11-05 21:02
@Nadin-Nader  SCTASK0178810 is submitted for DEV deployment of the changes to reflect Paloma's email.

**Comment by Nadin-Nader** [comment] 2021-11-09 20:57
@SubhaShroff this has been deployed to DEV. Please UAT

**Comment by TracyLinder** [comment] 2021-11-09 22:20
**Update:** We need to get this done before the code freeze because if we don't it's likely to have bad outcomes for our other work like automated payments on extension fees.

**Comment by SubhaShroff** [comment] 2021-11-10 18:47
### Status:
Waiting on Batch related Deployment in DEV. Yesterday, Anu submitted a DevOps DEV deployment request for  a commit.

**Comment by SubhaShroff** [comment] 2021-11-12 20:28
@TracyLinder  @Nadin-Nader  SCTASK0179943 is submitted for DEV deployment of the changes in Batch after testing it.

**Comment by TracyLinder** [comment] 2021-11-12 20:52
**Clarification on valid status:** Do not include 'Pending Payment

**Comment by SubhaShroff** [comment] 2021-11-16 19:34
@Nadin-Nader  @TracyLinder  The batch job is working I need to make a demo and send you. will do that today.

**Comment by SubhaShroff** [comment] 2021-11-17 17:34
@Nadin-Nader  SCTASK0180888 is submitted for TEST deployment of the Activate upon payment part, so that we can test it.

**Comment by Nadin-Nader** [comment] 2021-11-19 18:09
@SubhaShroff looks like this is deployed to TEST. Please UAT during meeting if possible

**Comment by TracyLinder** [comment] 2021-11-19 21:36
### UAT BLOCKED BY POSSIBLE PORTAL BUGS

Portal would not show us any of the invoices we tried to test with. Nate is working with Gita to figure out what's going on. We cannot test until this is resolved.

**Comment by SubhaShroff** [comment] 2021-11-23 03:34
@TracyLinder @Nadin-Nader  SCTASK0181956 is submitted for Batch job TEST deployment.

**Comment by SubhaShroff** [comment] 2021-11-23 17:51
@Nadin-Nader  @TracyLinder  SCTASK0182122 - is submitted for the DEV Deployment of the Batch procedure changes to remove the validation messages that are overflowing the error message field.

**Comment by SubhaShroff** [comment] 2021-11-23 23:08
> 

@TracyLinder  @Nadin-Nader  @Sreelatha-BlazeKannan  - The issue: RW TURP not available for online Payment: I traced to a webservice(1010) and then narrowed to a function - f_coa_allow_online_payment. After debugging this function for couple of RW TURP permits, this points to the ticket #7327. 
Before I do any changes we need to discuss this.

**Comment by SubhaShroff** [comment] 2021-11-23 23:12
### Status:
RW TURP not available for online Payment issue thats a blocker for UAT is traced to a ticket 7327. Need inputs before the fix.

**Comment by TracyLinder** [comment] 2021-11-24 17:46
@SubhaShroff will update online payments for RW folder on this issue. 

Online payments should be available for all RW sub/work types, and for all statuses.

**Comment by SubhaShroff** [comment] 2021-11-24 20:00
@Nadin-Nader  @TracyLinder  SCTASK0182349 is submitted for the fix to enable all RW types at status to be enabled for online payment.

**Comment by Nadin-Nader** [comment] 2021-11-24 20:02
**Status:**
Waiting on DevOps to deploy new changes to **_DEV_**

**Comment by SubhaShroff** [comment] 2021-11-24 23:26
@Nadin-Nader  The DEV deployments are done by EOD. I need to test.

**Comment by SubhaShroff** [comment] 2021-11-29 16:59
@Nadin-Nader  @TracyLinder  Now all RW types with billed fees are enabled for online payments on DEV. Please let me know if I can promote this change to TEST.

**Comment by SubhaShroff** [comment] 2021-11-29 17:36
@Nadin-Nader  SCTASK0182623 is submitted for TEST promotion.

**Comment by Nadin-Nader** [comment] 2021-11-30 15:08
@SubhaShroff this has been deployed to **_TEST_**. Please do your initial UAT and let me know if it is ready for the stakeholder to UAT

**Comment by SubhaShroff** [comment] 2021-11-30 17:33
@Nadin-Nader  @TracyLinder Tested this ticket on TEST for the batch job and Activate upon payment features:

- 2021 048898 000 00 EX , 2021 048897 000 00 RW - with online payment both turned to Active and 'Activate Upon Payment' is updated to 'No'.
- Batch job is running at midnight, daily. And I am getting emails for the permits(EX, RW, DS) permits. The emails look as follows. I am not adding the caution content. I think it is set in COA mail server.

![image](https://user-images.githubusercontent.com/51680715/144098187-fb5f46dc-c8ed-499c-bf03-cf69eb0f8915.png)

**Comment by SubhaShroff** [comment] 2021-11-30 23:37
### Status:
Ready for UAT on TEST.

**Comment by TracyLinder** [comment] 2021-12-03 20:59
**AC just updated after testing w/ stakeholders**

**Comment by Nadin-Nader** [comment] 2021-12-07 15:59
**Status:**
on Friday's UAT Session with the stakeholders, this failed for EX, DS.  Subha is debugging it currently.

**Comment by SubhaShroff** [comment] 2021-12-07 18:23
@Nadin-Nader  @TracyLinder 

- Batch job is updated on localhost. 
- DS case in UAT failed because we tried adding a random fee and pay online. DS gets activated only on payments for the following fees. I tried with these fees - 2021 049056 000 00 DS and it worked as expected.
- **So, that raises the question, is the requirement should apply for any fees added, for EX, DS, RW-TURP?**
50145	Excavation/Concrete Permit Fee - PDR	                5090-5300-9771-4099-0000-0000-0000-0000-0000
50147	Excavation/Concrete Permit Fee	                        5090-5300-9771-4099-0000-0000-0000-0000-0000
50348	Excavation/Concrete Permit Fee - Transportation	5125-2400-9100-4057-0000-0000-0000-0000-0000

- For EX, EX - 12668437 I think it has worked. It showed active on that day, only info was not showing updated to NO. Today i opened the same permit. It was marked NO. So, I tried another EX - 12668684 on TEST. It worked as expected.

**Comment by TracyLinder** [comment] 2021-12-10 18:09
I added 2 workflows to the issue description. FYI @SubhaShroff

**Comment by SubhaShroff** [comment] 2021-12-15 03:27
### Status:

- Batch Job procedure is updated for the latest AC.
- RW, EX, DS - I need to retest it and fix for DS that is not getting updated for AUP and status.

**Comment by SubhaShroff** [comment] 2021-12-15 17:32
@TracyLinder  @Nadin-Nader  SCTASK0186794 is submitted for Batch Procedure update. 
Yet I need to fix on DS folders that failed in UAT.

**Comment by SubhaShroff** [comment] 2022-01-05 14:48
### Status:
AUP changes are applied for DS (that failed in UAT) - i will commit it today.

**Comment by SubhaShroff** [comment] 2022-01-05 19:13
@Nadin-Nader  SCTASK0190850 is submitted for DEV deployment.

**Comment by SubhaShroff** [comment] 2022-01-10 22:51
@Nadin-Nader I tested the deployment and it failed on DEV. So after fixing it, submitted the DEV deployment request -SCTASK0191816, for the respective commit -"70bf4fe88328".

**Comment by SubhaShroff** [comment] 2022-01-11 23:52
### Status:
Testing on DEV is in progress. Yet to test DS case. Will continue tomorrow.

(EX - 11904198 - Fee added and billed on 1/11/2022 - It should email on 1/18/2022 to subhashini.s@launchitcorp.com.
EX - 11904157(AWU) - Fee added and billed on 1/11/2022 - It should email on 1/18/2022 to subhashini.s@launchitcorp.com.
RW - 11904134(TURP AWU) - Fee added and billed on 1/11/2022 - It should email on 1/18/2022 to subhashini.s@launchitcorp.com.
DS - 11902183(Com. Curb, Gutter) - Fee added and billed on 1/11/2022 - It should email on 1/18/2022 to subhashini.s@launchitcorp.com.
DS - 11904194(Res. Driveway, Sidewalk, Curb, Gutter)- Fee added and billed on 1/11/2022 - It should email on 1/18/2022 to subhashini.s@launchitcorp.com.)

**Comment by SubhaShroff** [comment] 2022-01-12 21:20
@Nadin-Nader  Retested the payments as Portal payment citybase working now. It works as follows. Batch should work, I should get email on 18th, since I billed them yesterday.(That will complete Batch job test). Other part of the ticket Activate works as expected.
2022-000096 RW - PCO
2022-000095 RW - PVT

Please let me know if I can move it to TEST.

**Comment by SubhaShroff** [comment] 2022-01-19 14:48
### Status:
After UAT, permit status check is added as per stakeholder's feedback. I am done testing the code for EX on localhost. After testing for RW, DS, I am committing today.

**DS**
Pending

**EX**
Active
Expired
Pending


**RW**
Active
Expired
Pending
Pending Permit

**Comment by SubhaShroff** [comment] 2022-01-19 18:06
@Nadin-Nader  SCTASK0194147 is submitted for DEV deployment of commit -"15ca880d2a17".

**Comment by Nadin-Nader** [comment] 2022-01-20 21:28
@SubhaShroff This has been deployed to **DEV**. Please UAT

**Comment by SubhaShroff** [comment] 2022-01-21 17:22
@Nadin-Nader  @TracyLinder  I tested 6255 - all looked good to me. I submitted TEST deployment request - SCTASK0194755.

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/SUBHAS~1/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/SUBHAS~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



Tested on DEV with AUP-YES : |   |   |   |   |   |  
-- | -- | -- | -- | -- | -- | --
Status b4 payment | RSN | Foldertype | Subtype | Work Type | AUP to NO? | Active? |  
Pending Permit | 11904246 | RW | Parking Spaces | Residential Parking Permit | yes | yes | Pass
Expired | 11904133 | RW | TURP | Austin Transportation (ATD) | yes | yes | Pass
Active | 11904137 | RW | TURP | Private Development or CIP | yes | YES | Pass
Pending | 11903773 | RW | TURP | Project Connect | yes | yes | Pass
  |   |   |   |   |   |   |  
Active | 11904156 | EX | Austin Water   Utility (AWU) | NA | yes | yes | Pass
Expired | 11904022 | EX | Franchised   Utility | NA | yes | yes | Pass
Pending | 11904020 | EX | Private   Development or CIP | NA | yes | yes | Pass
  |   |   |   |   |   |   |  
Pending | 11901373 | DS | Res. Curb, Gutter | Demo | yes | yes | Pass



</body>

</html>

**Comment by Nadin-Nader** [comment] 2022-01-21 19:55
@subha this has been deployed to TEST please UAT

**Comment by SubhaShroff** [comment] 2022-01-21 20:32
@Nadin-Nader  I tested it on TEST, testing one permit for each permit type (RW, EX, DS). It looked good. Batch Job part can't be tested as job runs only after midnight. It will start today.

**Comment by SubhaShroff** [comment] 2022-01-25 20:11
@Nadin-Nader  SCTASK0194851, SCTASK0194854 are closed. PROD deployment is done.

**Comment by TracyLinder** [comment] 2022-02-09 21:10
### Update - Move to PROD

- Subha has tested this in TEST. Because this is a batch job & it's hard to test, this is all the UAT we will do. 
- We'll need to verify in PROD that this is working, a few days after it goes to PROD. @SubhaShroff does AMANDA keep a log of all the records updated by the batch job?

**Comment by SubhaShroff** [comment] 2022-02-14 15:29
@Nadin-Nader @TracyLinder  we are still waiting on the re-deployment of the commits in PROD. CTM is still trying to figure out the cause of PROD issues. Once its resolved they will redeploy the code in PROD.

**Comment by SubhaShroff** [comment] 2022-02-16 14:28
@TracyLinder @Nadin-Nader I checked the log files in Amanda7, which logged in user can access. I don't see it maintaining any info of the updated records through batch job.

**Comment by Nadin-Nader** [comment] 2022-03-25 20:20
All is well per Paloma. Closing

**Closed by Nadin-Nader** 2022-03-25 20:20 UTC
Labels: Workgroup: ROW, Need: 1-Must Have, Type: Enhancement, Product: AMANDA, Provider: LaunchIT, Status: Awaiting Response, Project: FY22 AMANDA Fee Updates
