### ISSUE TITLE
[BUG] Users getting an "You must attach Property to this Folder to assign an inspector" error when trying to Issue an EX permit (Discuss @ 2pm)

### ISSUE THREAD

**Issue by Nadin-Nader** [cityofaustin/atd-data-tech#10813] opened 2022-11-16 23:06 UTC
### There is something wrong with the PropertyID 2041381. The system does not recognize it as a folder property for unknown reasons. 
- When attempting to issue the folder the system won't allow it, throwing error: "You must attach a property to this folder to assign an inspector."

**INC0244163 Created**

-----
Users getting an "You must attach Property to this Folder to assign an inspector" error when trying to Issue an EX permit

Timeframe: 12:45 pm
User: BONDR
Tab : Folder
Folder: 2022 144418 EX
Attempting To: Issue the permit
Browser Type: Chrome
Type of Connection: Netmotion
Server: S1 DB PROD
See error below. I have followed all our normal permitting procedures and cannot get the permit to issue.

![MicrosoftTeams-image (24).png](https://images.zenhubusercontent.com/5e8dfbfabf171441c3a5684e/d11dadcf-695f-4421-8863-14b3227d399c)

- **This is a time sensitive issue and needs to be resolved Priori to 11/22 (Customer needs it by 11/23)**
- Isabel P. has also tried to issue and receives the same error.
- This is only happening on this one folder
- The normal workflow is used and there is no work around yet

**Comment by Nadin-Nader** [comment] 2022-11-17 13:29
@SubhaShroff 
Notes from Paloma:
> 
> [Yesterday 5:50 PM] Amayo-Ryan, Paloma
> Nader, Nadin - I don't know if this helps but I did a ton of poking around and my best guess is that the issue is specific to the Property Tab.  Here's the audit of that tab ... it looks a little wonky:

![MicrosoftTeams-image (25).png](https://images.zenhubusercontent.com/5e8dfbfabf171441c3a5684e/8c361f1a-a6be-484f-825d-c08e3d66b439)

And Notes from Russell:

> [7:16 AM] Bond, Russell
> It looks wonky because as Izzy can testify too, the segment ID's and block ranges on S Lakeshore have changed with some GIS update in the past. The property segment that was selected at the time of application did not exist in ROWPACT, so I corrected it to what was in ROWPACT and matched the Utility Plan per policy. 
> 
> [7:16 AM] Bond, Russell
> The reason that property tab looks wonky Paloma was me trying to figure out the initial issue when I couldn't get any results in ROWPACT searching by the original ROW ID.

**Comment by SubhaShroff** [comment] 2022-11-17 17:08
@Nadin-Nader  Looks like its got resolved (itself) after user corrected the Property. Can we close it?

**Comment by TracyLinder** [comment] 2022-11-17 17:58
@SubhaShroff @Nadin-Nader I'm going to meet with Russel and Izzy this afternoon to better understand what happened. Then I'll write notes here and close it. Thank you.

**Comment by TracyLinder** [comment] 2022-11-17 21:07
### Mtg Notes

**We were able to reproduce this issue on FOLDER ROWID 13053687:**
1. Begin Portal application for EX folder
2. When selecting the folder properties use the text search tool. Type "lakeshore" and click search. 
3. Select the S Lakeshore segment
4. Continue & submit application 
5. Pay application fee
6. Complete all folder processes
7. Issue folder **System throws error message**


**Work-Around:**
1. Remove the property from the folder. 
2. Add the correct properties for this application (propertyid 3381701)
3. Issue the folder



----
### There is something wrong with the PropertyID 2041381. The system does not recognize it as a folder property for unknown reasons. 
- Comparing this propertyID against one we know works (3381701); the only difference I see is that the working property has a **Created Date** whereas the other doesn't (is null). 
<img width="591" alt="Screenshot 2022-11-17 at 3 05 36 PM" src="https://user-images.githubusercontent.com/49930868/202559799-9b00c30f-53bb-4cc9-8c08-3eb913aa4350.png">

**Comment by TracyLinder** [comment] 2022-11-17 21:14
### INC0244163 Created

**Comment by SubhaShroff** [comment] 2022-11-30 16:05
### Status 11/30/2022
  I checked the INC0244163 status - its still Open.

**Comment by TracyLinder** [comment] 2022-12-16 19:38
Swapna is waiting on a response from me.

**Comment by Nadin-Nader** [comment] 2023-04-17 23:47
@TracyLinder @SubhaShroff Swapna has closed the incident for this stating that she could not replicate. Seems like it may be resolved??

**Comment by TracyLinder** [comment] 2023-05-26 19:40
### Update & Closing

- This permit has been issued
- Izzy spoke w/ addressing at 911 at the time and they fixed it

**Closed by TracyLinder** 2023-05-26 19:40 UTC
Labels: Workgroup: ROW, Type: Bug Report, Impact: 1-Severe, Product: AMANDA, Provider: CTM, Provider: LaunchIT, Status: Awaiting Response
