### ISSUE TITLE
TURP Info: Total Days of Permit Validity 

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#8015] opened 2021-12-17 20:36 UTC
### ROW Stakeholders & ATD-IT do not know why this info exists, or what (if any) functions it serves. 

**Discovery**

- [ ] Is this info doing anything other than collecting data?
- [ ] Will removing it cause any issues?

_(Paloma & Kim seem to be ok with removing the info barring any complications.)_

**Comment by TracyLinder** [comment] 2022-01-10 19:19
**Notes**

- Our intention is to remove this info.
- First we need to determine if removing this info will cause any bugs that we aren't aware of.

**Comment by TracyLinder** [comment] 2022-01-12 17:25
Assigning to Vish for discovery.

**Comment by vschandramouli** [comment] 2022-01-20 19:56
Talking to Subha about reviewing this info. Info code seems to 75390. It is possible this is used for calculating a fee. Subha to review when she has availability.

**Comment by SubhaShroff** [comment] 2022-01-25 21:44
- The TURP Info: Total Days of Permit Validity (75992) is used in TURP  fee calculation in the package function - COA_FOLDER_FEES.f_turp_permit_fee. The info is used when the extension parameter value in the function was passed as 'Y' or 'Yes'. But I don't see this function called anywhere with 'Y' or 'Yes' value in its extension parameter.
----------------------------------------------------------------------------------------------------------------------------
- INFO validation - The Total Days of Permit Validity (75992) info value is updated with the info Number of Days Requested (75390) value for RW TURP.
- ISSUE -  The Total Days of Permit Validity (75992) info value is updated with the info Number of Days Requested (75390) value for RW TURP.
PERMIT EXTENSION - The Total Days of Permit Validity (75992) info value is updated with the info Number of Days Requested (75390) value + total number of days from Process Info (59820) for RW TURP.

**Comment by vschandramouli** [comment] 2022-02-04 07:33
@SubhaShroff If the fee function isnt called anywhere, does this mean the function is no longer being used? So do you think we can remove this info without it breaking any code?

**Comment by SubhaShroff** [comment] 2022-02-07 16:24
@vschandramouli  I rechecked, this function is used with 'Y' as extension parameter value for "Temporary Right of Way use permit fees"(50220). In the function, there is only a validation check if this info has a non-zero value or not(Error Message -'Total Days of permit validity not found';). But, its not used to calculate fee. That's bit strange! 

I think the info can be removed. From the code, I don't see its been used. There should not be any code breakage if we comment its reference in the procedures/packages. Nor should it break any functionality.

**Comment by vschandramouli** [comment] 2022-02-07 16:59
@SubhaShroff Thanks. Let me confirm with Kim and Paloma about this once more and then we can go ahead and remove the info.

**Comment by vschandramouli** [comment] 2022-02-07 18:56
Confirmed from Paloma on Scoping channel that this info can be removed. 
@SubhaShroff  Can you please go ahead and remove if you are working on this ticket.

**Comment by SubhaShroff** [comment] 2022-02-08 19:25
Thanks @vschandramouli. This info is there for other RW subtypes also. Should I remove this only for TURP? 
Though it is there, not used (my observation in the code).

**Comment by vschandramouli** [comment] 2022-02-09 15:03
@SubhaShroff  Yes, it can be removed in all RW folders. Thanks!

**Comment by SubhaShroff** [comment] 2022-02-21 15:16
### Status:
Development is done and committed. Waiting until code freeze is over to do further deployments.

**Comment by SubhaShroff** [comment] 2022-03-30 19:09
@Nadin-Nader  DEV deployment request is submitted for this ticket - SCTASK0209473.

**Comment by SubhaShroff** [comment] 2022-04-05 14:13
@Nadin-Nader @TracyLinder  Verified in DEV. Now TURP Info - Total Days of Permit Validity doesn't add in new permits. I checked info tab save and issue. I didn't find any issues. Please let me if we can get it promoted to TEST.

**Comment by SubhaShroff** [comment] 2022-04-05 14:50
@Nadin-Nader TEST Deployment request is submitted - SCTASK0210401.

**Comment by SubhaShroff** [comment] 2022-04-06 14:25
@Nadin-Nader  This ticket is in TEST and verified by me. Ready for UAT.

**Comment by SubhaShroff** [comment] 2022-04-13 13:55
### Status:
Ready for UAT.

**Comment by TracyLinder** [comment] 2022-04-15 19:32
### Approved for PROD 🎉

**Comment by SubhaShroff** [comment] 2022-04-15 20:29
@TracyLinder  @Nadin-Nader SCTASK0212405 - submitted the PROD deployment request.

**Comment by SubhaShroff** [comment] 2022-04-19 13:32
### Status:
This ticket is in PROD now.

**Comment by Nadin-Nader** [comment] 2022-04-20 12:24
Status: Paloma will let us know on Friday if we can close

**Comment by SubhaShroff** [comment] 2022-04-26 14:49
### Status:
Informed to Paloma. User is doubting after deploying this ticket, 'insert + run' TURP Extension fees are not working. I will verify it.

**Comment by SubhaShroff** [comment] 2022-05-03 14:29
@Nadin-Nader  @TracyLinder  I verified about the 'insert + run' TURP Extension fees are not working. Its not due to removing 'TURP Info: Total Days of Permit Validity'.  I don't see any relation in the code with this info and extension fees.

I am not sure how the user was adding the fees. Because, for extension fee it expects the tier values and as I understand that is possible with 'Extension Granted' attempt. If tier values are not given, the fees won't be calculated.
### Status:
We can close this ticket.

**Comment by SubhaShroff** [comment] 2022-05-11 14:15
@Nadin-Nader  @TracyLinder Yesterday(5/10/2022), had a call with LaTonya about the TURP ROW usage fees  not inserting with Extension. LaTonya explained that the Info -Total Days of Permit Validity that we removed in this ticket is used to find the tier in which permit is in. Accordingly the fees were calculated. However, she mentioned that the system never calculated fees as expected. This field was holding the number of days since the permit was active for first time. That tells in which tier the permit lies.
The call record link - https://cityofaustin-my.sharepoint.com/:v:/g/personal/nadin_nader_austintexas_gov/EXwQ6_sFoUJNuY8RCNyAvw0BGssK36jz3G-AEiRrLjmwJA

This ticket needs rescoping.

**Comment by SubhaShroff** [comment] 2022-05-18 14:44
### Status:
Based on the conversation with LaTonya, this ticket needs rescoping.

**Comment by Nadin-Nader** [comment] 2022-05-20 18:08
Closing and Revisiting in V7

**Comment by Nadin-Nader** [comment] 2022-05-20 18:09
Closing and revisiting in V7

**Closed by Nadin-Nader** 2022-05-20 18:09 UTC
Labels: Workgroup: ROW, Need: 3-Could Have, Type: Enhancement, Product: AMANDA, Provider: LaunchIT
