### ISSUE TITLE
Meeting: Weekly Sync (Stephanie & Tracy) - RTRC

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#8818] opened 2022-03-31 18:33 UTC
**Beginning 3/31/22 Stephanie & Tracy meet weekly to sync on this project.**
_All meeting notes to be captured here for the duration of the weekly meetings._

**Comment by TracyLinder** [comment] 2022-03-31 19:11
### Notes - 3/31

- Steph has met w/ ROW & MMC and compiled a list of initial requirements. OSE delayed by SXSW conflicts - discovery will be scheduled w them. 
- Darren w/ ROW is applying for grant funding. More info to come. Stephanie informed ATD Finance & got some basic guidance about grants. 
- Steph met w/ ATD finance. Advised we should follow the city's Solicitation process for this project. The first step is a statement of work. Steph & Tracy will work on this together next week. ATD Finance thinks we could be done w/ solicitation and ready for vendor evaluations by the start of FY23. They also advised council approval is required. 

**Priority Deliverables:**
- Schedule a meeting with Jim ASAP to update him. 
- Prepare a timeline for Jim to present at the meeting. 
- Draft SOW

**Comment by moorerst** [comment] 2022-04-28 16:46
**Update - 4/28**

- Scheduled meeting with Office of Special Events - meeting has been rescheduled several times. Currently scheduled for 5/3

- Forwarded requirements that were documented from meeting with MMC to Lance for review. Wanted to make sure we captured what they wanted.

- Darren facilitated a demo with the vendor One Network, I did not attend.

- Updated the SOW, communicated with Darren requested that he review and provide input. He agreed he would work on it this week.

- Focus is getting the SOW submitted to ATD Finance this week for review.

**Comment by moorerst** [comment] 2022-05-05 18:00
Met with Office of Special Events (Frances/Maria)

- Reviewed the goals of the project

- Review what meetings have occurred thus far

- Discussed the need to gather requirements from different stakeholder groups so we can compile a list of requirements for vendor evaluations    
- They talked about their current process: 
-they enter permits into Amanda for upcoming special events
-they search Amanda for any road closures that might conflict with scheduled special events
-they do not get notifications from 311 on construction road closures
-they defined 2 different type of road closures: construction road closures and road closures for special events.
- they have a need to be informed about emergency road closures due to water main breaks, etc.

**Comment by moorerst** [comment] 2022-06-02 18:22
sent status email to Darren, Ryan and Brian informing them the SOW has been submitted to ATD Finance for review.

**Comment by moorerst** [comment] 2022-09-13 16:58
- Received updated/formatted SOW from ATD Finance. ATD Finance has a few questions on the SOW. Forwarded the questions to Darren.

- After SOW is finalized it will be sent to central purchasing to start the solicitation. 

- ATD asked if we had a list of possible vendors. I will forward the names of the  vendors we discussed during the project kickoff. Darren confirmed they are still interested in these vendors
One Network
Mixon Hill
Dot Maps

**Comment by moorerst** [comment] 2022-09-14 15:48
Forwarded the updated SOW and vendor list to ATD Finance (Ken)

**Comment by moorerst** [comment] 2022-10-03 14:30
Provided vendor information to ATD Finance for solicitation:

Here’s the contact info for the following vendors: 

•	One Network –
o	Name: Rob Foster, Director
o	Email: [rob.foster@one.network](mailto:rob.foster@one.network) 
o	Phone: 612-402-8833

•	Dot Maps (SADA)
o	Name: John Biesak, Product Business Development Lead
o	Email: [john.biesak@sada.com](mailto:john.biesak@sada.com)
o	Phone: 818-942-2030

•	Mixon Hill
o	Name: Chris Poe, Director
o	Email: [chris.poe@mixonhill.com](mailto:chris.poe@mixonhill.com)
o	Phone: 913-239-8066

Waiting on next steps from ATD Finance

**Comment by moorerst** [comment] 2022-10-05 16:59
Provided project funding and reassigned ATD PR for management approval

**Closed** 2022-12-01 23:22 UTC
Labels: Type: Meeting, Workgroup: OSE, Workgroup: ROW, Service: Product, Project: Real-time Road Closures
