### ISSUE TITLE
Austin-Travis County Traffic Report Migration to ODP page, deprecate old source page

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#10688] opened 2022-11-03 15:17 UTC
# Austin-Travis County Traffic Report Meeting Notes 11/3

## Target Time frame
`Early next year (Jan-March 2023)`
- After the City Data Hub Migration

## High-level Next Steps: 
- ATD to recreate Traffic Incident Report [page ](austintexas.gov/qact/default.cfm?sort=1))into an Open Data Story Page - Karo
  - Marbenn can assist as needed
  - [link](https://www.austintexas.gov/qact/default.cfm)
- ATD in collaboration with CTM to update the data feed for [Real-Time Traffic Incident Reports](https://data.austintexas.gov/Transportation-and-Mobility/Real-Time-Traffic-Incident-Reports/dx9v-zd7x) on the Data Portal to pull directly from the CTM Oracle Database
  - Danhao and Marbenn can assist as needed 
  - Note: The CTM Oracle database refreshes every 3 minutes from the database of record at CTECC that houses incident data

**Comment by KaroEngstrom** [comment] 2022-12-21 22:15
## W 12/21/22 

- Audit requests for this item have come in November/December; that work is documented [here](https://docs.google.com/document/d/1v8odTCGChf4o5BYG83QCiBLYxSTPJn4UF-d9DJYe7-g/edit#)

**Comment by Charlie-Henry** [comment] 2023-01-31 04:54
Noticed this evening that this incidents [dataset ](https://data.austintexas.gov/Transportation-and-Mobility/Real-Time-Traffic-Incident-Reports/dx9v-zd7x) is no longer being updated as of 1/17/23. I assume the ODP migration zapped it.

**Comment by dianamartin** [comment] 2023-01-31 12:57
@Charlie-Henry cc @KaroEngstrom we'll have to figure out what happened. We intended to rebuild the public page anyhow, so this conversation would be starting again in the next few months.

**Comment by chiaberry** [comment] 2023-01-31 13:54
Could also be that the endpoint needs to be updated to be datahub on our end. I think this is the script, the endpoint is somewhere in the secrets file. 
https://github.com/cityofaustin/atd-data-publishing/blob/production/transportation-data-publishing/data_tracker/traffic_reports.py

**Comment by amenity** [comment] 2023-02-08 20:53
@dianamartin @KaroEngstrom - this came up in Dev + Product Sync - sounds like it should go in Backlog or Blocked?

**Comment by dianamartin** [comment] 2023-02-08 21:08
@amenity we're gonna put it in backlog and pick it up in a next sprint.

**Comment by chiaberry** [comment] 2023-03-09 17:36
Diana submitted a CTM SN ticket `INC0272574` to get the CTM database access we need to build out the "Austin-Travis County Traffic Report" data feed

**Comment by dianamartin** [comment] 2023-03-16 22:39
# 3/16
- CTM provided credentials to the RACWEB database
- I added to 1password and slack message to folks

Instructions
>RACWEB's TNS entry is below. It's already been added in global TNS file.
You can access an Oracle DB through client tools such as SQL Developer, SQL*Plus, etc. Database developers usually know how to access an Oracle DB.

```RACWEB_TAF.WORLD =
  (DESCRIPTION =
    (ADDRESS_LIST =
      (ADDRESS = (PROTOCOL = TCP)(HOST = coaracp.austintexas.gov)(PORT = 1521))
    )
    (CONNECT_DATA =
      (SERVER = DEDICATED)
      (SERVICE_NAME = racweb_taf.world)
      (FAILOVER MODE =
        (TYPE = SESSION)
        (METHOD = BASIC)
        (RETRIES = 90)
        (DELAY = 5)
      )
    )
  )

**Comment by dianamartin** [comment] 2023-03-28 18:55
@johnclary @chiaberry do we have status on whether or not we've been able to hit this DB? cc @ChristinaTremel

**Comment by chiaberry** [comment] 2023-03-29 21:06
@dianamartin I have been able to successfully hit the DB. I think I'll have to reach out to Danhao or Marbenn to see if there is a table that contains all of the reports of all time or just daily reports.

**Comment by dianamartin** [comment] 2023-03-29 21:39
@chiaberry The CTM person that gave me access was an IT DBA Sr, Wendy C., I slacked you her name.

**Comment by KaroEngstrom** [comment] 2023-04-05 16:33
@chiaberry 
Checking in on the status of the data feed migration after our App Sync. 
s there anything we can do to prepare or assist from the Apps side?

**Comment by chiaberry** [comment] 2023-04-05 21:32
@KaroEngstrom I opened this issue to rewrite the script and write a new ETL for it

**Comment by KaroEngstrom** [comment] 2023-06-13 15:53
## T 6/13/23 
- email from a community user that the RSS feed page is unavailable; assuming that CTM has shut it down w/o alerting us
- published [our new version of the page ](https://data.austintexas.gov/stories/s/Austin-Travis-County-Traffic-Report-Page/9qfg-4swh/)
- retired previous verbiage in the Brief Description: 
     `This data set contains traffic incident information from the Austin-Travis County traffic reports RSS feed, 
     available at http://www.ci.austin.tx.us/qact/default.cfm.`
     `The dataset is updated every 5 minutes.`
      `Incidents that are currently  in the RSS feed have a status of "active" in this dataset.`
       `Incidents that are no longer appear in the feed have a status of "archived."`
- wrote new Brief Description with link to the new context page
![image](https://github.com/cityofaustin/atd-data-tech/assets/100615928/7c623287-1115-4159-9a7e-a6894a0ed732)
- published updated dataset 
- notified community member via email from Transportation Data account

**Comment by dianamartin** [comment] 2023-06-13 17:39
@KaroEngstrom that new page looks nice! 🎉 @johnclary @chiaberry what's the status of the RSS feed?

**Comment by chiaberry** [comment] 2023-06-13 17:55
I rewrote the script and ETL to connect to the traffic incident database directly to update the dataset, bypassing the CTM cold fusion app. My understanding is that the Cold Fusion RSS feed page was to be deprecated entirely.

**Comment by dianamartin** [comment] 2023-06-13 18:18
I thought were were going to evaluate if we were going to rebuild some part of it..but I don't remember

**Comment by KaroEngstrom** [comment] 2023-06-13 18:20
Same understanding as @chiaberry above. 

We were going to replace their model with getting the data directly from their database. 

| Steps ⬇️ |Old Model | New Model | 
| ---- | ---- | ---- | 
| CTM database | ✅ | ✅ |
| Cold Fusion app - RSS feed | ✅ | ❌ |
| widget of last five minutes at a time of data on the COA hosted page with more context data | ✅ | ❌ |
|  DTS Dataset| 🧓 DTS using RSS feed data to create a dataset with metadata referencing COA hosted page | 🆕  DTS using direct feed to add to dataset; DTS has Story Page to replace COA hosted page (all the same details and links but no RSS feed) |

**Comment by KaroEngstrom** [comment] 2023-06-13 18:21
We can evaluate if reproducing the last-five-minutes widget or the RSS feed in addition to the full on-going dataset is worth the effort or needed.

**Comment by johnclary** [comment] 2023-06-13 18:43
not a replacement for RSS feed users, but we could make a view of the data that only shows active incidents. maybe add that to the story page (if that's possible)? that would more closely resemble the RSS feed.

**Comment by dianamartin** [comment] 2023-06-13 18:55
That might be helpful if it's possible and a low level of effort

**Comment by KaroEngstrom** [comment] 2023-06-13 22:01
- added a quick table to the page with filters Published Date = Today and Status = Active. Not a lot of freedom of presentation but I can look into making it prettier later 😁 

![image](https://github.com/cityofaustin/atd-data-tech/assets/100615928/6234b367-81b9-4b5f-8ac7-49a26d9ceeb2)

**Comment by KaroEngstrom** [comment] 2023-06-13 22:06
From the public user: 

"Hi, 
 
Is there a query URL that will somewhat replicate the old page, where the page is automatically updated with the most recent events.
I tried this to sort descending on the status date.  It works once but does not repeat.
 
[https://data.austintexas.gov/Transportation-and-Mobility/Real-Time-Traffic-Incident-Reports/dx9v-zd7x/explore/query/SELECT%0A%20%20%60traffic_report_id%60%2C%0A%20%20%60published_date%60%2C%0A%20%20%60issue_reported%60%2C%0A%20%20%60location%60%2C%0A%20%20%60latitude%60%2C%0A%20%20%60longitude%60%2C%0A%20%20%60address%60%2C%0A%20%20%60traffic_report_status%60%2C%0A%20%20%60traffic_report_status_date_time%60%0AORDER%20BY%20%60traffic_report_status_date_time%60%20DESC%20NULL%20LAST/page/filter](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdata.austintexas.gov%2FTransportation-and-Mobility%2FReal-Time-Traffic-Incident-Reports%2Fdx9v-zd7x%2Fexplore%2Fquery%2FSELECT%250A%2520%2520%2560traffic_report_id%2560%252C%250A%2520%2520%2560published_date%2560%252C%250A%2520%2520%2560issue_reported%2560%252C%250A%2520%2520%2560location%2560%252C%250A%2520%2520%2560latitude%2560%252C%250A%2520%2520%2560longitude%2560%252C%250A%2520%2520%2560address%2560%252C%250A%2520%2520%2560traffic_report_status%2560%252C%250A%2520%2520%2560traffic_report_status_date_time%2560%250AORDER%2520BY%2520%2560traffic_report_status_date_time%2560%2520DESC%2520NULL%2520LAST%2Fpage%2Ffilter&data=05%7C01%7Ctransportation.data%40austintexas.gov%7C5aed9ea1f01c448b04d208db6c5a12db%7C5c5e19f6a6ab4b45b1d0be4608a9a67f%7C0%7C0%7C638222906343626806%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=eBxGBRfAwpiEcBu%2B796B5049SaPEgq0mKp7QV8BcxG4%3D&reserved=0)
 
The old page also used to identify if an incident was APD or Travis County.  Is there a column we can add to show this?"

**Comment by KaroEngstrom** [comment] 2023-06-13 22:07
@johnclary @dianamartin 
I've added the table which I don't think he's seen, so that would cover the latest and active reports pretty well. 

From what I can tell we've lost the origin info and that's not something we've reported out to ODP ever.

**Comment by chiaberry** [comment] 2023-06-14 16:14
@KaroEngstrom we can get agency type from the database, there needs to be a few extra steps to get it into the dataset

@johnclary am I right that we need to update the postgrest metadata to save that information, then add the column to socrata and the payload in the ETL?

**Comment by KaroEngstrom** [comment] 2023-06-14 16:29
Thanks @chiaberry - I talked to Diana about this at App Sync and I'll respond to the user with what we have now. 
I'll create an issue for adding the agency as an enhancement request and y'all on the dev side can prioritize that accordingly if that sounds good.

**Comment by KaroEngstrom** [comment] 2023-06-14 17:10
# W 6/14/23 

- responded to requester from Transportation Data email 
     - see new table of Active Reports Today
     - see option to save a view of the dataset to preserve preferred data order 
     - we have put in the request to add the Agency column; no estimate on the delivery date as that will be prioritized with other work
- created a new issue #12590  for dev team to scope and prioritize the addition of the Agency column

**Comment by dianamartin** [comment] 2023-06-23 19:29
# 6/23
I also noticed the old page is redirecting to a new page: https://services.austintexas.gov/qact/default.cfm

I thought we were going to rebuild this page, not CTM?

**Comment by KaroEngstrom** [comment] 2023-07-18 18:24
We have our context page for the data we put out, in an ODP Story as planned. We were not going to rebuild their five-minute widget because we don't provide incremental data or an RSS feed like they used to, but rather the full dataset based on their database reporting. 

I think the only question remains: do we want to link to their new version from the dataset? It's seem like largely a dupe. They seem to have reproduced the page when the understanding was that they would retire it altogether.

**Comment by KaroEngstrom** [comment] 2023-07-28 19:09
Closing because our work here is done.

**Closed by KaroEngstrom** 2023-07-28 19:09 UTC
Labels: Workgroup: DTS, Service: Dev, Service: Apps, Type: Open Data, Type: Integration
