### ISSUE TITLE
[Bug] Public Ability to Edit Case Details and Remove Breadcrumbs

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#3692] opened 2020-08-14 04:06 UTC
### The public is able to edit TIA case attachments

**Requirements:**
- Only TIA Case Reviewers should have the ability to update case information after customer submittal (from backend)
    - Excluding the 2 scenarios where the applicant is sent a link to add case attachments
- On the Submission Confirmation page: 
    - Replace the current link 'Back to TIA Review Submission' with a link to view the case the customer just submitted. Link Text: _View TIA Submission_ 
    - Remove the path links above the confirmation message; these all allow the applicant to edit case details after submission.
- On the public page review-status/view-details:
    - Remove the + button that allows the public to add an attachment
    - Remove the green New Submission button

![image](https://user-images.githubusercontent.com/49930868/90212514-21901380-ddb9-11ea-87f7-1471bfd202d4.png)

![image](https://user-images.githubusercontent.com/49930868/90212633-7a5fac00-ddb9-11ea-8b13-d612d37c4b74.png)

**Comment by ChrispinP** [comment] 2020-08-28 20:43
@SurbhiBakshi and @johnclary would either of you know how to remove breadcrumb navigation links for forms?

Thanks

**Comment by ChrispinP** [comment] 2020-09-02 22:45
I have disabled the links with JS but the link text still shows. The CSS code does not seem to be functioning as intended and hiding the text. May need a second pair of eyeballs to take a look or if we are okay with the text still showing.

![image](https://user-images.githubusercontent.com/67915167/92044528-0ecb8780-ed44-11ea-86c8-366bfa581746.png)

**Comment by SurbhiBakshi** [comment] 2020-09-03 14:40
@ChrispinP - we can look at this in Apps Sync next week.

**Comment by ChrispinP** [comment] 2020-09-18 21:55
@johnclary any update on how to fix the code to hide breadcrumbs text? would it be worth to spend some time with a dev to figure out?

**Comment by ChrispinP** [comment] 2020-09-28 16:51
Pinged john again about this on Thursday.

**Comment by TracyLinder** [comment] 2020-10-09 20:36
Per @ChrispinP he was able to disable the links, which meets the business need. Perhaps one day we can work on hiding them if it becomes a priority.

**Comment by TracyLinder** [comment] 2020-10-09 20:48
I just tested; the breadcrumbs still link on the confirmation splash page.

**Comment by ChrispinP** [comment] 2020-11-09 18:52
Updated code for breadcrumb links for the TIA Request application process

**Comment by ChrispinP** [comment] 2020-11-23 22:54
Updated breadcrumbs and back links for TIA Case Status from the Case Details page, Submission Details page, and Add Submission page for requesters. Requester should only be able to navigate back to Case Details page and not the Case Status table that lists all cases now.

Ready for Review

**Comment by ChrispinP** [comment] 2020-11-25 18:40
Working as intended during TIA Module Sync. closing.

**Closed** 2020-11-25 18:41 UTC
Labels: Need: 1-Must Have, Product: TIA Module, Service: Apps, Type: Bug Report
