### ISSUE TITLE
AULCC, Report 3 (On PROD)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#5578] opened 2021-03-23 17:55 UTC
### A custom AMANDA report, PDF output, with 3 sections. 
_Markup Below_

**Stakeholders:** Ryan M, Darren U.

![image.png](https://images.zenhubusercontent.com/5f50fe1f66d1a40f7f557fb4/bc8f79b6-218c-4fb7-a538-cf9052db2bb7)

![image.png](https://images.zenhubusercontent.com/5f50fe1f66d1a40f7f557fb4/942e42a4-0571-4f4e-b8e5-b25cbfa9f380)

Tracy's Spreadsheet is [here](https://github.com/cityofaustin/atd-data-tech/files/6306249/City.Department.Reports.Request.xlsx)

**Comment by TracyLinder** [comment] 2021-03-31 16:28
### Meeting Notes
Participants: Tracy, Ryan, 

CIP UC Cases = Subtype is CIP (51600)
Non CIP = Subtype **isn't** CIP
Department name is in info 'Facility owner/sponsor'
Submittal Date = Folder Indate


Average # of Resubmittals needed to clear comments
- Counting the # of cycles to approval
- Only include folders w/ an issue date



![image.png](https://images.zenhubusercontent.com/5cca1e522b8dfc0ee14dedf5/02a299d9-674e-4a9f-ace2-5effb16a1bbe)



- [ ] New backlog issue: 61060 Adjust Review Due Dates: update attempts (same functionality, just different attempt names)
- Resubmittal
- Corrections

**Comment by TracyLinder** [comment] 2021-04-01 18:27
This has been assigned to LIT.

**Comment by SubhaShroff** [comment] 2021-04-08 19:22
Thank you @Nadin.
@TracyLinder @Nadin-Nader In the case of 3rd table from the report for SCP folder, is it 76765 info I should look for Department Name?
I checked the SCP folder configuration on TEST and 76765 info is not configured for SCP folder.

**Comment by TracyLinder** [comment] 2021-04-08 19:47
**Email to Stakeholders:**

![image](https://user-images.githubusercontent.com/49930868/114087314-5cc7e100-9879-11eb-8f94-551366d6b0aa.png)

**Comment by Nadin-Nader** [comment] 2021-04-13 17:22
@SubhaShroff here is Ryan's response:

> [4/7 9:52 AM] Nader, Nadin
>     Morning Ryan, hey do you have a sec to talk about the AULCC Report Request card? I just have 3 questions from the developer
> ​[4/7 9:52 AM] Nader, Nadin
>     the questions are about the sections in the screenshot pointed out by the arrows:
> ![MicrosoftTeams-image (1).png](https://images.zenhubusercontent.com/5e8dfbfabf171441c3a5684e/b5a6b247-bc10-4acc-a193-e4ffdf6058f6)
> 
> ​[4/7 9:59 AM] Mooney, Ryan
>     In a meeting but can respond through chat.
> ​[4/7 10:00 AM] Nader, Nadin
>     That's perfect thank you
> ​[4/7 10:02 AM] Nader, Nadin
>     First question, Day to Issuance says # of days between InDate and Issue Date..if it is the same day do you want it to be 0 or 1?
> ​[4/7 10:04 AM] Nader, Nadin
>     Second question; Average # of Resubmittal for 61060...if there are no attempts should it be 1 or 0 since there is a +1 added?
> ​[4/7 10:06 AM] Nader, Nadin
>     3 is kind of the same question as 2 but for the attempts on SCP 85303...would it be 0 or the +1?
**_> [4/7 10:08 AM] Mooney, Ryan
>     If same day it can be 1
> ​    Is that standard for other reports?
> ​    2nd: it should be 1 I think, since it +1 would be added, may need to verify with Tracy as well
>     3: Same_**
>

**Comment by TracyLinder** [comment] 2021-04-13 19:37
Just an FYI, I updated the spreadsheet & report image in the description.

![image](https://user-images.githubusercontent.com/49930868/114610699-d4c14d00-9c65-11eb-8aae-09770a629397.png)

**Comment by SubhaShroff** [comment] 2021-04-13 21:56
Status: Working on the SCP table query.

**Comment by SubhaShroff** [comment] 2021-04-15 16:09
@TracyLinder  @Nadin-Nader

1. I have sent you the sample Report PDF for the review. Once you approve the report, then we can copy it in server to see it in Amanda.
2. I did Report configured in DEV Amanda.

**Comment by SubhaShroff** [comment] 2021-04-21 14:08
**Status:** Waiting for approval of PDF sample output sent to @TracyLinder and @Nadin-Nader on 4/15/2021.

**Comment by TracyLinder** [comment] 2021-04-21 16:10
I need to review the PDF Subha sent me.

**Comment by TracyLinder** [comment] 2021-04-23 19:12
**Update** 
We reviewed the sample PDF with stakeholders. Ryan asked for another section to be added that will allow users to view permit data line by line, similar to #5576. 

@vschandramouli please work on updating AC. Thank you,

**Comment by SubhaShroff** [comment] 2021-04-28 14:23
**Status:** Waiting on updated AC.

**Comment by TracyLinder** [comment] 2021-05-12 15:51
**Status Update**

@vschandramouli is meeting w/ Ryan today and will update the AC.

**Comment by vschandramouli** [comment] 2021-05-17 20:15
Added a drill-down report with AC to the side like the other reports. Development work on this can begin. Moving to On Deck

**Comment by SubhaShroff** [comment] 2021-05-18 21:34
### Status:
Since AC is ready, I will start working on drill-down report.

**Comment by SubhaShroff** [comment] 2021-05-26 13:32
### Status:
In progress. Working on the detail report.

**Comment by SubhaShroff** [comment] 2021-05-28 14:51
@Nadin-Nader  @TracyLinder  @vschandramouli Here is the demo output from crystal report tool as per the latest AC.  

- Orientation is changed to landscape to accommodate all the columns of detailed report.
- SCP summary report is moved to top of the report and the CIP summary report is moved to third place.
- I am waiting to hear from Tracy about Project Manager display in case there are more than one Project Manager per permit. Based on that I will update the report query. Otherwise, the format will look as in attached sample report.

[99020_AULCC_Report.pdf](https://github.com/cityofaustin/atd-data-tech/files/6557005/99020_AULCC_Report.pdf)

**Comment by vschandramouli** [comment] 2021-06-02 16:35
@SubhaShroff @Nadin-Nader Added note on first main report that info for Process 61060 also needs to be pulled though it is not used in the main report, only in the sub-report. Please let me know if I need to add anything more.

**Comment by SubhaShroff** [comment] 2021-06-03 02:18
### UPDATE on Detail Report: In today's sprint call, confirmed with Tracy to concatenate the Project Managers, if there are more than one with a permit.

I will be making that change in the detail report.

**Comment by Nadin-Nader** [comment] 2021-06-04 17:01
Subha will be working on this today

**Comment by SubhaShroff** [comment] 2021-06-07 18:33
@Nadin-Nader  @vschandramouli  @TracyLinder Here is sample Report output for your review. I have updated the report to display the project managers of the permit in the same row separated by comma. In the output, **6th page** - I have highlighted the permit that displays two Project Managers.
[Uploading 99020_AULCC_Report.pdf…]()

**Comment by SubhaShroff** [comment] 2021-06-08 22:23
### Status: 
As per Nadin's feedback on Teams:
[12:15 PM] Nader, Nadin
    Had a few questions, Can the tables be centered to the page? and on page 3 and 4, the tables last 2 lines are on a completely different page, is there any way we can get it on one page?

- The tables are centered.
- The 3rd table, last lines moving to next page :- I tried couple of fixes, but nothing looked as a good solution. Can't help with that much, if the Departments list is big, it will move to the next page.

Following is the latest sample with centered tables.
[99020_AULCC_Report.pdf](https://github.com/cityofaustin/atd-data-tech/files/6619884/99020_AULCC_Report.pdf)

**Comment by Nadin-Nader** [comment] 2021-06-10 04:53
@SubhaShroff I spoke to Tracy and had her look at this and her only concerns were that of the information splitting between the two pages. 
@TracyLinder if there is nothing we can do to stop the information from splitting in between two pages if there are only a few over the limit, should we still go ahead with it or ask the stakeholders?

**Comment by SubhaShroff** [comment] 2021-06-10 19:32
@Nadin-Nader  @TracyLinder  
I tried to squeeze the rows in third table. Please check the attached PDF. With this format, another 6 rows of data can fit in the page, if at all any. If that format is ok, let me know if I need to change the 1st, 2nd tables format to bring the uniform look.
[99020_AULCC_Report_with_squeezedRows_in_3rd_table.pdf](https://github.com/cityofaustin/atd-data-tech/files/6633923/99020_AULCC_Report_with_squeezedRows_in_3rd_table.pdf)

**Comment by TracyLinder** [comment] 2021-06-11 19:23
Can the column headers copy to the next page if the table breaks onto a second page?

**Comment by SubhaShroff** [comment] 2021-06-14 19:40
@Nadin-Nader  @TracyLinder @vschandramouli Now column headers are copying to the next page along with the extending table. Please check the attached PDF file.
[99020_AULCC_Report_with_3rd_table_with_headers_in_extended_Page.pdf](https://github.com/cityofaustin/atd-data-tech/files/6650804/99020_AULCC_Report_with_3rd_table_with_headers_in_extended_Page.pdf)

**Comment by Nadin-Nader** [comment] 2021-06-15 16:36
@SubhaShroff I have reviewed the PDF output and it looks way better with the column Headers in the new page. I sent a screenshot to @TracyLinder but i am pretty sure she will approve the move to DEV. Go ahead and send me the rpt file so that i can get it ready to go on DEV, UAT and then possibly TEST for the stakeholders to UAT before PROD.

![image.png](https://images.zenhubusercontent.com/5e8dfbfabf171441c3a5684e/5cfe0440-3ca0-4aaf-b2fc-60e634b8b032)

**Comment by Nadin-Nader** [comment] 2021-06-15 18:23
@SubhaShroff Tracy has approved. Lets go ahead and get this moving along

**Comment by Nadin-Nader** [comment] 2021-06-15 18:55
@SubhaShroff i have moved the file to DEV. Please UAT and let me know

**Comment by SubhaShroff** [comment] 2021-06-18 21:15
@Nadin-Nader, I sent you the latest sample PDF outputs after updating the report today. Please review. I sent you the latest .rpt file, as well.

**Comment by Nadin-Nader** [comment] 2021-06-21 01:54
@SubhaShroff as mentioned in our chat, It looks good to me. Lets get it on TEST for Stakeholder UAT.

**Status:**
Ready for TEST deployment

**Comment by SubhaShroff** [comment] 2021-06-21 19:54
@Nadin-Nader I sent you TEST deployment plan and .rpt file for the deployment.

**Comment by Nadin-Nader** [comment] 2021-06-21 20:58
@SubhaShroff  have deployed the file to TEST but i am getting errors trying to pull up the parameters during setup and when i try to run the report it gives an error see images below:

![Error Populating Parameters.png](https://images.zenhubusercontent.com/5e8dfbfabf171441c3a5684e/2aa9c0e1-a922-4ba5-8ff3-834320647534)

![Error when running report.png](https://images.zenhubusercontent.com/5e8dfbfabf171441c3a5684e/1fb6b377-ee7a-4fa5-98be-ad5edf52c41f)

**Comment by SubhaShroff** [comment] 2021-06-22 22:19
### Status:
Report is not generating on AMANDA. I am trying to fix it.

**Comment by Nadin-Nader** [comment] 2021-06-25 19:17
@SubhaShroff 
**Status:**
Getting Error with the parameters so this has been sent to CT under **INC0111386** for Anu to work on

**Comment by SubhaShroff** [comment] 2021-06-29 22:32
### Status:
It is working for Nadin and Anu. But giving errors to me for any report. It doesn't looks like report issue but the browser compatibility issue. Anu also says so. i have to fix my IE browser. Should we push it for UAT?

**Comment by Nadin-Nader** [comment] 2021-07-02 18:53
This is working on and off for both CTM and us. Anu sent an email:

Hi,
Please follow below email instruction for fix the issue and let me know once they are completed so we can add it to AMANDA 7. 

Thanks
________________________________________
From: McKissick, Jenice <Jenice.McKissick@austintexas.gov>
Sent: Thursday, July 1, 2021 3:57 PM
To: Mahindrakar, Anu <Anu.Mahindrakar@austintexas.gov>; Rajagopalan, Gita <Gita.Rajagopalan@austintexas.gov>
Cc: CTM Amanda Tango <CTMAmandaTango@austintexas.gov>; Rajagopalan, Amita <Amita.Rajagopalan@austintexas.gov>
Subject: RE: INC0111386 - Report 99020 AULCC Report is getting an error when ran from the ATD Report menu on TEST 
 
Hi Anu,
 
I have 99020 working you need to make sure the dates are correct in the query,  See the changes I made below. 
 
The way it was  endDate and startDate 
I fixed it to enddate and enddate   
 
 ![1.png](https://images.zenhubusercontent.com/5e8dfbfabf171441c3a5684e/cc3a4e90-fff0-4b2a-a7df-ebd85f993792)
 
 
Make sure to populate in AMANDA once the changes.
 
 
 ![2.png](https://images.zenhubusercontent.com/5e8dfbfabf171441c3a5684e/0d2e85b2-4db5-4c46-853f-d2bfa2175f42)

Reports= reports 99020, 99021, 99022, pretty much any report

**Comment by Nadin-Nader** [comment] 2021-07-02 19:13
@SubhaShroff can you check the calculation n this report. Seems to be a large average.
@Nadin-Nader email report to subha

**Comment by SubhaShroff** [comment] 2021-07-06 22:11
### Status:
Checking the calculations (Permitting Resubmittal averages) on the report. 
@Nadin-Nader @vschandramouli  Can we have a call sometime tomorrow to ensure the calculations with my findings?

**Comment by Nadin-Nader** [comment] 2021-07-07 20:04
@SubhaShroff meeting scheduled for tomorrow 7/8/21 @930

**Comment by Nadin-Nader** [comment] 2021-07-08 14:56
Had the meeting with Darren and found that the calculation fix was correct and he also decided on the average showing 2 decimal spaces.
He also would like to have us:
  -  Remove the 2 number columns that arent the average from the average column on the far right
  -  Center the data retrieved in the columns.
  -  Fix the overall Average (if need be)
  -  Add the Attempt/s
  -  Add the Attempt/s date

@SubhaShroff as mentioned in the meeting, once this gets addressed we will send a test copy for revision and if all is well, promote to PROD.

**Comment by Nadin-Nader** [comment] 2021-07-09 18:26
**Status:**

Subha is making the changes and should be finalizing today.

**Comment by SubhaShroff** [comment] 2021-07-09 21:31
[99020_AULCC_Report.pdf](https://github.com/cityofaustin/atd-data-tech/files/6794007/99020_AULCC_Report.pdf)
@Nadin-Nader  Here is the report sample output after the enhancements. I sent you in email also. Please review and let me know.

**Comment by SubhaShroff** [comment] 2021-07-16 18:21
@Nadin-Nader PROD deployment request is submitted - SCTASK0152455.

**Comment by SubhaShroff** [comment] 2021-07-16 20:17
SCTASK0152455 is closed and PROD deployment is done.

**Comment by Nadin-Nader** [comment] 2021-07-19 16:13
Email Sent to Stakeholders:

> Good Morning,
> 
> Hope you are all doing well and had a great weekend. I was reaching out to inform you that the AULCC Report is now on PROD. Please log on and make sure you are able to run the report and let me know the outcome or if anything is amiss.
> 
> I will go ahead and close the card by COB unless otherwise instructed.
> 
> Respectfully,
> 
> Nadin A. Nader (He/Him/His)
> IT Business Systems Analyst
> Data and Technology Services

**Closed** 2021-07-20 18:03 UTC
Labels: Need: 1-Must Have, Product: AMANDA, Provider: LaunchIT, Type: Reports, Workgroup: ROW
