### ISSUE TITLE
Add Edit item request button

### ISSUE THREAD

**Issue by JaceDeloney** [cityofaustin/atd-data-tech#1233] opened 2020-01-21 20:27 UTC
We should add an edit button to the work order. This button should be styled and behave similar to the time logs button. The user should be redirected back to the parent page once they submit the edit.

Editable items are as follows:
-
-
-

**Comment by mddilley** [comment] 2020-01-27 20:41
Duplicate of https://github.com/cityofaustin/atd-data-tech/issues/1215. Closing.

**Closed by mddilley** 2020-01-27 20:41 UTC
Labels: Duplicate, Need: 2-Should Have, Project: Mobile Signal Work Order, Service: Dev, Type: Enhancement, Workgroup: AMD
