### ISSUE TITLE
Product: Vision Zero In Action

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#145] opened 2019-05-23 17:54 UTC
We are building an app for APD officers to record Vision Zero in Action citations. By digitizing what is now a paper-based process, we can streamline workflows and collect data to inform VZA program management. 

![VZA-App](https://user-images.githubusercontent.com/1463708/106407039-9c4cf980-6400-11eb-9096-b3a08739be42.png)

### How might we ...
- Increase the efficacy of VZA enforcement?
- Leverage VZA enforcement data to inform the Vision Zero program?
- Measure the ROI of Vision Zero in Action's expenditures on APD VZA citation staffing? 

### Challenge
[Vision Zero in Action](https://austintexas.gov/page/vision-zero-action) is a coordinated Vision Zero education and enforcement effort by Austin Transportation Department and Austin Police Department. Long term, data on APD's VZA citations would help the program improve enforcement scheduling and identify areas for targeted educational outreach. However the immediate need is being able to report on the efficacy of money spent on enforcement and maximize value.

### Request
A web app that APD can use to log Vision Zero in Action citation activities. Features would include

**Primary**
- Ability for APD officers to log time, location, and activity type of VZA citations
- Ability for ATD to see what shifts have been staffed and what citations were made during those shifts

**Secondary**
- Ability for ATD staff to query the information and identify geographic and temporal hotspots for different types of activities during certain time periods

### Target users
**APD**
- Scheduler 
- Officers on shift

**ATD**
- Vision Zero staff

### Key Stakeholders
- Jen D., Division Manager, Arterial Management Division
- Lewis L., Transportation Safety Officer,  Vision Zero
- Randy D., Office of Special Events, APD
- Pat O., Program Liaison, APD
- Lance M. and Alyson R., Mobility Managment Center 

### Additional information
**Previous applications**
DTS built a basic version in Knack previously and then made a new version with enhancements, but it was never used:
- [UI for scheduler to create shifts](https://atd.knack.com/amd#vision-zero-portal/)
- [UI for officer to log citations](https://atd.knack.com/amd#vision-zero-enforcment-officer-portal-login/vision-zero-enforcment-officer-portal/) — switch to the "month" view on the shift calendar and you will see a shift that you can click on
- [Data](http://transportation.austintexas.io/data-tracker/#vision-zero-portal/)

**Behaviors targeted for enforcement**
- Safety enforcement
     - Failure to stop at red lights and stop signs (all vehicles, including bikes)
     - Speeding, including school zone speed compliance
     - Vehicles using bus-only lanes or parking in bike lanes
     - Driver inattention (i.e., enforcing the City’s Hands-Free Ordinance)
     - Failure to yield right of way (including at crosswalks or yield signs)
     - Lane splitting (i.e., riding a bicycle or motorcycle in between lanes)
     - Passing stopped school buses that are loading or unloading students
     - Failure to comply with pedestrian hybrid beacons
- Congestion management
     - Don’t Block the Box (enforcement for vehicles blocking cross-traffic by being present in an intersection when the light is red)
- Air quality
     - Enforcement for motor vehicles idling in the right of way (applies to heavy-duty vehicles weighing over 14,000 pounds)

### Resources
 - [Google Drive](https://drive.google.com/drive/folders/1IUXtA0WsDXK5WfFidIZCfuDg5DjkHvOt)
 - [Power BI dashboards](https://app.powerbigov.us/groups/me/reports/31d30635-b90e-46a4-a97d-d9858acc7fe6/ReportSection?openReportSource=ReportInvitation&ctid=5c5e19f6-a6ab-4b45-b1d0-be4608a9a67f) (requires CoA login)
 - App: https://atd.knack.com/vza
 - [Officer Training](https://docs.google.com/presentation/d/1nuNBaVGKPAvLfbX5-8B-Khef_iZ4ou0puWojZTmIh6A/edit#slide=id.g6512805fdb_0_198)
 - [Website Link](https://www.austinmobility.io/products/145)

---
This Github issue represents a project of Austin Transportation's [Data & Technology Services](https://transportation.austintexas.io/about/) team. Project status is documented regularly in the comments below.

**Comment by dianamartin** [comment] 2019-05-23 18:43
AMD (Jen) is managing program. Bring Lewis Leff into conversation. 

John will attach document from VZ Citation Report App. 

~ Proposed Time Line
Summer 2019 - Prototype & Testing
Fall 2019 - Go Live

**Comment by johnclary** [comment] 2019-06-12 18:13
[This doc](https://docs.google.com/document/d/1o24XLXDNiKofJmCt37wdiY0QxhvMWqCe1Oz44oThTU0/edit) summarizes my understanding of the previous data capture needs.

**Comment by amenity** [comment] 2019-06-13 19:45
Changing "How might we maximize the impact of Vision Zero in Action's enforcement and education efforts?" to "How might we measure the ROI of Vision Zero in Action's expenditures on APD VZA citation staffing?"

**Comment by amenity** [comment] 2019-08-06 23:54
We have [interviewed primary users](https://github.com/cityofaustin/atd-data-tech/issues/208#issuecomment-506549653) and started [implementation in Knack](https://github.com/cityofaustin/atd-data-tech/issues/238). Once the initial prototype is ready, we will do a stakeholder demo, perform usability testing, and iterate on the app.

**Comment by amenity** [comment] 2019-09-26 20:53
**Status update**
@SurbhiBakshi has picked up this project. She went to meet APD user Pat O at his APD location to observe his current processes. She has begun definition of the Knack data model, functional requirements, and MVP implementation. She will be reaching out to the VZ team with a few questions about their workflow.

**Comment by amenity** [comment] 2019-10-29 23:04
**Status update**
We have completed all the must-have features for the first release of the app along with a set of reports for staff — citation breakdowns by location, time, officer, etc.  — that will help them manage the program. In the coming weeks we'll be doing moderated user testing with APD officers to see identify areas for improvement.

**Comment by amenity** [comment] 2019-12-09 04:50
**Status update**
After performing [usability tests with APD officers](https://drive.google.com/drive/folders/1cAChXqvTwCVfXs6evIEJK5YuHSsxsqBB) and gathering feedback from ATD's VZA staff, we are in the process of optimizing our data structure and user interfaces. We are also looking into the potential for direct integration with APD's Brazos citation technology, which would allow us to greatly simplify the workflow for APD officers.

**Comment by JaceDeloney** [comment] 2019-12-27 17:43
Unassigning this to me. Not sure why I was assigned to this. Happy to help as needed :)

**Comment by amenity** [comment] 2020-01-08 01:56
**Status update**
We performed user interviews with staff in the VZA [Scheduler](https://github.com/cityofaustin/atd-data-tech/issues/929) and [Assigner](https://github.com/cityofaustin/atd-data-tech/issues/965) roles and made a number of subsequent refinements to those UIs. We will be rolling out the app to these two roles/users first as VZA 1.0 while APD officers will continue their current paper/Excel workflow. Meanwhile we continue to investigate a Brazos integration that would eliminate the need for officers to record individual citations in the field.

**Comment by amenity** [comment] 2020-02-26 01:43
After extensive testing, we have determined that we can reliably use Power BI to analyze and report on Brazos citation data and therefore do not need to capture complete citation data in the VZA App.

While piloting VZA 1.0 scheduling functionality, we worked with AMD and VZ stakeholders on a standardized data model for VZA locations. Implementation of this location model and resolution of bugs identified during the pilot will mark the VZA 1.0 release.

We also worked with APD to identify an improved assignment workflow: In VZA 2.0 officers will manage their own assignments, thus saving a substantial staff time and likely increasing program participation.
We are about to begin testing the officer workflow so that we can release VZA 2.0 to a pilot group of officers after SXSW. (e

**Comment by amenity** [comment] 2020-04-06 07:35
**Status update**

**Comment by amenity** [comment] 2020-05-18 06:57
*Status update*

**Comment by amenity** [comment] 2020-06-29 01:08
After [reviewing the VZA Scheduling interface with the AMD Signals workgroup](https://github.com/cityofaustin/atd-data-tech/issues/2668), we determined that it makes sense to extend the application to support scheduling APD officers for traffic control during signal installation and maintenance. Work is now in progress to [integrate the app with Data Tracker](https://github.com/cityofaustin/atd-data-tech/issues/2879) so that signal locations will be available to Schedulers. We are also [building the VZA Location geospatial data set and reference map](https://github.com/cityofaustin/atd-data-tech/issues/2916). 
We [met with Pat to review the interface Officers will use](https://github.com/cityofaustin/atd-data-tech/issues/1476) to manage their assignments and track activities while they are on assignment and are currently making a couple of usability improvements based on his feedback. Once these are complete, we will be ready to open the application to a pilot group of Officers and begin working on the [APD Administrator interface](https://github.com/cityofaustin/atd-data-tech/issues/1480).

**Comment by amenity** [comment] 2020-07-22 06:41
7/22 email to stakeholders 

> 
> I wanted to provide y'all with a quick update on the VZA App.
> 
> Since we last met: 
> 
> -   Surbhi has built out the VZA 2.0 interface for Officers to use the app, including
> 
> -   Logging in with their CoA credentials
> -   Signing up for assignments
> -   Clocking their time on shifts
> -   Adding notes about observations and periods of inactivity during shifts
> 
> -   We [met with AMD](https://github.com/cityofaustin/atd-data-tech/issues/2668 "https://github.com/cityofaustin/atd-data-tech/issues/2668") to discuss extending the application to include Signal scheduling
> 
> -   We [met with Pat](https://github.com/cityofaustin/atd-data-tech/issues/1476 "https://github.com/cityofaustin/atd-data-tech/issues/1476") to review the first pass at the Officer workflow and got some great feedback
> 
> Currently:
> 
> -   The Dev Team is [implementing some customizations](https://github.com/cityofaustin/atd-data-tech/issues/3249 "https://github.com/cityofaustin/atd-data-tech/issues/3249") to improve the usability of the Officer sign up workflow; specifically making it clear that they are expected to do all three assignments on a shift
> 
> -   Surbhi is polishing the Location data, including adding traffic signal locations from Data Tracker
> 
> Next up:
> 
> -   Set Billy up to schedule traffic signal shifts
> 
> -   Have a Sprint Review to review the Dev Team's customizations and nail down VZA 2.0 pilot and launch logistics
> 
> -   Open pilot to several officers
> 
> -   Work with Randy to see how the app affects his invoicing process and make any necessary changes there 
> -   Launch VZA 2.0 
> -   Pick up where we left off on reporting functionality
> 
> Our schedule has been a bit delayed since Surbhi has been very involved prepping for Diana's maternity leave --- hiring+onboarding an additional Application Analyst, working with Diana to document all-the-things... but we expect to have a more bandwidth in the coming month and look forward to getting this out there!
> 
> Let me know if you have any questions and/or updates on y'all's end of things.
> 
> Thanks,
> Amenity

**Comment by amenity** [comment] 2020-09-22 17:55
**Status Update**

**Comment by amenity** [comment] 2020-11-02 10:33
been positive and the officers are eager to move into the new system. Single sign-on is working well and we’ve ascertained that Randy has all the information he needs to do his invoicing. We made several refinements based on officer feedback and feel very good about the current user experience. Unfortunately, a significant bug was reported several weeks into the pilot that we were unable to reproduce until last week. We made changes to the custom code and are meeting with users today and Wednesday to ascertain that the issue is resolved. 
We would like to bring a few more officers into the pilot for additional testing before opening the application to officers mid-month. 
We are in the process of extending the location model to include signals and will onboard Billy once this is complete.

**Comment by amenity** [comment] 2020-12-16 09:06
**Status Update**
- We trained the second set of pilot officers last week and will run the pilot for two more weeks to ensure all is running smoothly. 
- @SurbhiBakshi  is working on BI dashboards for program management
- We have been working with Randy to streamline his process; relieved of scheduling involvement, will only be doing invoicing
- We are coordinating with Lewis and Pat to hold a training for all officers in January and flip the switch on the new system

**Comment by amenity** [comment] 2021-01-29 07:30
After four officer training sessions at the beginning of the month, we launched VZA 2.0 last week. We trained 43 officers but only 3 have signed up for shifts. Randy likes his new process and he and Lewis will be doing weekly invoice processing now. Surbhi is working on the Power BI reports for invoicing and program management. We’ll walk through scheduling shifts with Billy tomorrow.

**Comment by amenity** [comment] 2021-03-11 16:57
**Status update**
Work is currently focused on:
- Training and technical support for officers
- Reporting and BI improvements for invoicing, program management, and data analysis

**Comment by amenity** [comment] 2021-04-19 15:18
*Status update*

**Comment by patrickm02L** [comment] 2021-06-11 18:53
@SurbhiBakshi demoed the VZA Application for me.

**Comment by patrickm02L** [comment] 2021-08-04 17:58
At the August's monthly Sprint Review, Lewis said that they don't have any current VZA needs.

**Comment by amenity** [comment] 2024-04-25 18:58
@johnclary I "archived" this product. 👮🏻‍♂️ 🪦 👋

**Closed** 2024-08-22 16:27 UTC
Labels: Workgroup: AMD, Type: New Application, Service: Apps, Workgroup: VZ, Product: Vision Zero in Action, Archived Product
