### ISSUE TITLE
Meet with stakeholders: Update, demo, review user stories

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#221] opened 2019-06-17 14:59 UTC
Make sure to gather any additional user stories from Signs that aren't on the list

**Comment by amenity** [comment] 2019-09-09 16:09
@amenity schedule this for Sprint 8.

**Comment by dianamartin** [comment] 2019-09-23 17:21
Duplicate of #610

**Closed** 2019-11-06 23:13 UTC
Labels: Project: Warehouse Inventory, Service: Apps, Type: Meeting, Workgroup: AMD, Workgroup: SMB
