### ISSUE TITLE
[RPP Back Office] Add field to Issue Permit Page for Total # of Day Passes

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#4442] opened 2020-11-10 20:30 UTC
Requested by Daniil

When you select Day Passes from Permit Type on the Issue Permit page Is it possible to add a "Number of Day Passes" field to enter the total # of day passes purchased.
Keep the serial # field so all the serial #'s can be entered

**Comment by moorerst** [comment] 2020-11-10 20:33
![image](https://user-images.githubusercontent.com/56606465/98730309-b3c89900-2361-11eb-9474-cf3474cdead8.png)

**Comment by ChrispinP** [comment] 2020-11-11 19:13
This is a feature request. RPP Staff not using form as intended. Duplicate issue, closing.

New issue #4450

**Closed** 2020-11-11 19:14 UTC
Labels: Product: Residential Parking Permit Digitization, Service: Apps, Workgroup: PE
