### ISSUE TITLE
Project: 2019 Print Bike Map

### ISSUE THREAD

**Issue by alan-deanda** [cityofaustin/atd-data-tech#522] opened 2019-08-21 20:12 UTC
## Description
The City of Austin publishes a print version of the bike map every year. The bike map shows the recommended routes for bicycling, and it displays them by level of comfort so that they may be useful for people of all ages and abilities. The bike map is a collaboration between Active Transportation & Street Design, Public Information Office and the Data & Technology Services Team at Austin Transportation Department.

### Resources

[cityofaustin/atd-geospatial/issues/73](https://github.com/cityofaustin/atd-geospatial/issues/73)
[Mapping Comfort](https://peopleforbikes.org/blog/mapping-comfort-how-psychological-stress-influences-bike-maps/)
[Four Types of Cyclists](https://www.portlandoregon.gov/transportation/44597?a=237507)

**Comment by alan-deanda** [comment] 2019-08-21 20:14
@johnclary this is the new index for the print bike map.

**Comment by alan-deanda** [comment] 2019-10-28 16:54
Project update:
Work is still ongoing, we are currently reviewing the 2nd draft of the map. Nothing newsworthy for the newsletter, though.

**Comment by johnclary** [comment] 2020-05-14 16:40
> The 2020 Edition of Austin's Print Bike Map has been completed and it will be printed, proofed and published / released in the near future.

**Comment by johnclary** [comment] 2020-05-14 16:45
Dupe of #1911.

**Closed** 2024-04-27 19:18 UTC
