### ISSUE TITLE
Feature to allow portal users to print their permit reports (LP) (Ready for UAT on PROD)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#10471] opened 2022-10-11 20:53 UTC
### ROW permit holders should be able to log into portal and print/save a copy of their permit report. 

**Acceptance Criteria**

- The Acceptance Criteria mentioned below applies to DS, EX, PSM and all RW folders. 
- Previously, on the Permit Details page of the portal (Portal Homepage -> My Permits -> Click on a Permit), there used to be a small window at the bottom with a button called View/Print Permit on all these folders. This generated and opened a PDF report of the Permit document. 
- This feature has disappeared from the permit details page and needs to be brought back. 
- For reference, the way to access these reports in the Back office is to navigate to Folder Tab of the folder and Click on Options -> Print -> ROW Permit (for example). 
- The following are the permit report codes that need to be allowed to be printed on the portal. 
-- DS - 50506
-- EX - 50510
-- PSM - 85008, 
-- RW PArking - 50512
-- RW Valet Annual  - 50504
-- RW Valet Temp - 50502
-- RW Valet Operator - 50505
-- RW STreet Event - 50513
-- RW TURP - 50511
-- RW Film - 50509

Previous ticket where this was reported and implemented #1528

**Comment by vschandramouli** [comment] 2022-10-26 12:41
Updated AC, moving to backlog.

**Comment by TracyLinder** [comment] 2022-11-18 21:05
### Update
- Paloma reiterated this is the highest priority right now, 
FYI @Nadin-Nader

**Comment by Lpriya-LIT** [comment] 2022-11-21 17:06
@TracyLinder @Nadin-Nader There is a issue in Smarlet for view permit link. Working with Swapna to fix the issue. Once the issue is resolved , will work on enabling view permit link for EX, DS, RW and PSM folders.

**Comment by Lpriya-LIT** [comment] 2022-12-07 15:43
This is a manual deployment - Created request - SCTASK0270098

**Comment by Nadin-Nader** [comment] 2022-12-13 15:14
@Lpriya-LIT this has been manually deployed. Please UAT

**Comment by Lpriya-LIT** [comment] 2022-12-13 15:38
@Nadin-Nader But when I click the button , getting error. This error is common for all portal folders . Swapna and team are workig on the fix.

**Comment by Lpriya-LIT** [comment] 2022-12-13 15:39
![image.png](https://images.zenhubusercontent.com/611eac1954217f265acc0499/15565016-2f6a-4cdb-a367-a7ea978e9000)

**Comment by Lpriya-LIT** [comment] 2022-12-16 19:41
@Nadin-Nader Submitted manual deployment plan to deploy smartlet changes from Dev to Test - SCTASK0272550

**Comment by Nadin-Nader** [comment] 2022-12-22 15:16
@Lpriya-LIT this has been deployed. Please UAT

**Comment by Lpriya-LIT** [comment] 2022-12-22 15:41
@Nadin-Nader Verified in Test, View permit button is only visible for DS and EX. For RW and PSM it doesnt show up even after adding it to the Web service as discussed with Swapna. 
Moving Back to In progress and work with Portal team again

**Comment by Lpriya-LIT** [comment] 2022-12-30 14:04
@Nadin-Nader View permit Button is working for all folders reports PSM, RW, DS, EX

**Comment by Lpriya-LIT** [comment] 2022-12-30 18:16
@Nadin-Nader Ready for UAT on Test

**Comment by Lpriya-LIT** [comment] 2023-01-04 15:43
@Nadin-Nader @TracyLinder This is a manual Deployment that has to be done by CTM portal team in 3 Steps. I have created request for Step 1 - Copy files from Test server to Prod Server - SCTASK0276190. Once done will proceed with next step

**Comment by Nadin-Nader** [comment] 2023-01-06 13:17
@Lpriya-LIT the first step has been deployed Please proceed with the next.

**Comment by Lpriya-LIT** [comment] 2023-01-06 15:32
@Nadin-Nader Created Manual Deployment request - SCTASK0277022. I will work with Anu and get it done.

**Comment by Lpriya-LIT** [comment] 2023-01-10 19:13
@Nadin-Nader Step 2 has been deployed , working with ctm support team on deploying the last step to Prod.

**Comment by Lpriya-LIT** [comment] 2023-01-12 17:20
@Nadin-Nader Created Manual deployment request to move smartlet changes to Prod- SCTASK0278554

**Comment by Nadin-Nader** [comment] 2023-01-13 18:10
@Lpriya-LIT this has been deployed to PROD. Please UAT

**Comment by Lpriya-LIT** [comment] 2023-01-13 18:24
@Nadin-Nader Created prod deployment request to deploy web service commit to Prod - SCTASK0278854

**Comment by Lpriya-LIT** [comment] 2023-01-18 15:34
@Nadin-Nader Changes deployed to Prod , Ready for UAT

**Comment by Nadin-Nader** [comment] 2023-02-17 00:25
closing as this is good to go.

**Closed by Nadin-Nader** 2023-02-17 00:25 UTC
Labels: Workgroup: ROW, Type: Feature, Impact: 2-Major, Need: 1-Must Have, Product: AMANDA, Provider: CTM, Provider: LaunchIT, Product: AMANDA Portal
