### ISSUE TITLE
TIA Submissions Page Design

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#4371] opened 2020-11-03 21:49 UTC
This page needs better design. 

https://atd.knack.com/development-services#view-tia-reviews/tia-request-details/5f80d60665abf800163a2c9e/project-submissions/5f80d60665abf800163a2c9e?

**Comment by ChrispinP** [comment] 2020-11-09 19:36
Had to rebuild Submissions page and update rules. Not sure how much nicer in comparison it looks now but should be an improvement. Function wise, everything on the page should be working as intended now.

Ready for Review

**Comment by ChrispinP** [comment] 2020-11-25 18:54
no further issues, closing

**Closed by ChrispinP** 2020-11-25 18:54 UTC
Labels: Product: TIA Module, Service: Apps, Service: Product, Type: Enhancement, Workgroup: TDSD
