### ISSUE TITLE
[Enhancement] - PSM Info Type Change - # of Bolts

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#9224] opened 2022-05-20 19:12 UTC
### Ordnance update removed the # of bolts limit. This info needs to allow any number value. 

- Note from Tracy: Will changing the info type cause us to loose any data? If yes let me know please.

**Comment by TracyLinder** [comment] 2022-05-20 19:13
This issue was generated during a sprint review w/ ROW and requested by Paloma.

**Comment by vschandramouli** [comment] 2023-04-14 14:46
@TracyLinder Confirmed from Priya that changing the info type will not affect any historical data. 

This card is a duplicate of #11929 , which is currently in Ready to Deploy status. 

I am closing this card.

**Closed by vschandramouli** 2023-04-14 14:46 UTC
Labels: Workgroup: ROW, Need: 2-Should Have, Type: Enhancement, Product: AMANDA
