### ISSUE TITLE
Make AGOL map with Moped data to demo to TPW executive team

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#14453] opened 2023-10-27 20:56 UTC
Date TBD, but we're hoping to present a post-Access-migration Moped update at the TPW Executive Team meeting in November or December. An AGOL map of project data (along with EAZs, sidewalks, demographic data?) would be very compelling. 

cc/ @maccallump @johnclary

**Comment by andrewshensky** [comment] 2023-10-30 16:13
We can definitely start putting together a web application similar to the existing Interim Mobility Project Viewer. Once we have an alike product I can reach out to Nathan for further input

**Comment by amenity** [comment] 2023-10-30 19:45
Thanks @andrewshensky @johnclary ... Would it be helpful for me to set up a brief meeting w/ Nathan or start a Teams chat? Or would you prefer to start from a IMPDB Viewer parity?

**Comment by johnclary** [comment] 2023-10-30 20:45
Thank you both. Something to keep in mind is that we have not settled the question if/how we want to handle the challenge of dealing with point + line feature services in the viewer. As y'all know, this is handled in the interim viewer by converting point features to lines and cramming all the data into one layer.

I need to open a backlog issue for that task—and I would consider it to be blocking this work.

**Comment by andrewshensky** [comment] 2023-10-30 21:07
That is good to keep in mind. We have been utilizing FME more for automating processing on the geo side, I can explore a process on my end to get those points converted to lines and appended to a single feature layer. Lets do a little more research prior to reaching out to Nathan

**Comment by johnclary** [comment] 2023-10-31 14:56
so, is this really just a dupe of:
- https://github.com/cityofaustin/atd-data-tech/issues/3672?

**Comment by amenity** [comment] 2023-11-02 22:05
Renaming this to reflect what the humbler ask - an online map of some Moped projects that we can demo for the executives, similar to a Moped-in-AGOL glimpse that John recently showed to the Moped User Group. 

That said, @andrewshensky mentioned in our Data Science Retro today that he was able to automate the point-to-line process with FME, so maybe it does make sense just to put off our next executive presentation until #3672 is ready to share.

**Comment by amenity** [comment] 2024-04-30 15:07
@andrewshensky worked w/ Nathan W. on a [Moped Database Viewer](https://austin.maps.arcgis.com/apps/webappviewer/index.html?id=404d31d56b57491abe53ccfd718fcaee)

We link to it from the Moped menu: 
<img width="315" alt="Screenshot 2024-04-30 at 10 07 32 AM" src="https://github.com/cityofaustin/atd-data-tech/assets/1463708/34f9ccc2-e99c-4609-aa68-70a2238a89c4">

Other workgroups are also using Moped data in AGOL with their own viewers.

**Closed** 2024-04-30 15:08 UTC
Labels: Workgroup: DTS, Type: Map Request, Service: Geo, Service: Product, Type: Communication, Product: Moped, Project: Moped v2.0, Workgroup: TPW
