### ISSUE TITLE
[Bug] Incorrect locations/signals in Signal Engineer Areas AGOL layer

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#9804] opened 2022-07-20 14:53 UTC
John C.
DTS

Follow-up of #9678
>This makes me wonder if we should re-process all the Data Tracker locations/signals since the layer has changed significantly since we last did this - ?

Context: The[ location update script](https://github.com/cityofaustin/atd-data-publishing/blob/production/transportation-data-publishing/data_tracker/location_updater.py) was pointing to an old signal engineer area layer. This change points the script to the official GIS datamart layer.

**Comment by amenity** [comment] 2022-08-24 21:13
Thanks @dianamartin! 

@chiaberry @johnclary - do you think this belongs in the backlog or needs scoping?

**Comment by johnclary** [comment] 2022-08-29 17:28
It should be possible for an apps person to knock this out by following [these steps](https://github.com/cityofaustin/atd-data-tech/issues/9678#issuecomment-1185791026).

**Comment by amenity** [comment] 2022-08-30 03:10
@dianamartin - will you please add an estimate? Thanks!

**Comment by dianamartin** [comment] 2022-11-29 18:15
Brian G. was just trying to submit a DTS request about this today, 11/29

"SR Number `TMC22-32400  22-00439614` This is showing NORTHWEST area but is actually NORTHEAST. Somehow our areas are not working correctly, at least for this one location"

@johnclary is this affected by this issue or a GIS feature/311 issue?

**Comment by johnclary** [comment] 2022-11-30 17:05
@dianamartin - confirming that yes, this issue is the cause of the problem Brian observed.

**Comment by dianamartin** [comment] 2022-12-02 16:28
Following steps from #9678 to update:
- Location ID: `LOC16-002630`
- Signal ID: `537:  PARMER LN / 35 SVRD`

**Comment by dianamartin** [comment] 2022-12-02 16:51
@johnclary for this issue, would I just update all the locations and signals so that it'll update via script?

**Comment by johnclary** [comment] 2022-12-05 16:13
yes, by following [these steps](https://github.com/cityofaustin/atd-data-tech/issues/9678#issuecomment-1185791026).

**Comment by dianamartin** [comment] 2022-12-05 16:15
@johnclary yep, did that. I'm gonna check it if updated over the weekend.

**Comment by dianamartin** [comment] 2022-12-05 16:18
@johnclary well, it looks like `LOC16-002630` still didn't update even though I followed those steps.. :(

**Comment by johnclary** [comment] 2022-12-05 17:56
@dianamartin the location updater script is failing :/ it's a wild guess, but it may be related to the knack performance upgrades. this will need to be further triaged and estimated :(

**Comment by amenity** [comment] 2022-12-28 16:45
This continues to create issues, e.g. [[Data Tracker] Change Area Engineer Designation for Signals 957 & 958](https://github.com/cityofaustin/atd-data-tech/issues/11024#top)

Potentially the same pattern (geospatial reference script) as the one disrupting the [mechanism for assets in service requests that come over from 311](https://github.com/cityofaustin/atd-data-tech/issues/11058#top)

**Comment by Charlie-Henry** [comment] 2023-02-01 21:32
Synced with @johnclary about this and we're gonna try to refactor the old location updating script and roll it into [atd-knack-services](https://github.com/cityofaustin/atd-knack-services/tree/production/services)

**Comment by Charlie-Henry** [comment] 2023-02-07 18:11
I've re-located all locations in the [test data tracker app](https://builder.knack.com/atd/test--austin-transportation-data-tracker--30-aug-2022/records/objects/object_11). I'm curious how we want to end up validating some of these. 

@dianamartin LOC16-002630 shows `NORTHEAST` for signal engineer area.

**Comment by dianamartin** [comment] 2023-02-07 21:03
@Charlie-Henry awesome, thanks for the update

**Comment by Charlie-Henry** [comment] 2023-03-02 19:49
Looks like this is running alright on a test Data Tracker app. @dianamartin is there anything else we should look at before we switch this over to production?

**Comment by dianamartin** [comment] 2023-03-02 19:52
@Charlie-Henry it should be a straight forward script I think

**Comment by johnclary** [comment] 2023-03-06 19:55
@Charlie-Henry i'd say you should:
1. Test this locally against production (yolo...)
2. Request review on the knack servies and prefect PRs
3. I will tear down the legacy script

**Comment by Charlie-Henry** [comment] 2023-03-06 19:56
@johnclary Diana and I yolo'd this last week 👍 

One bug I am fixing then we can PR then merge and close this out!

**Closed** 2023-03-23 20:20 UTC
Labels: Workgroup: AMD, Type: Bug Report, Impact: 3-Minor, Service: Dev, Service: Apps, Product: AMD Data Tracker
