### ISSUE TITLE
Feature request: TCP Tracker Multiple Attachments, Submitted vs Returned TCP

### ISSUE THREAD

**Issue by ChrispinP** [cityofaustin/atd-data-tech#3824] opened 2020-08-28 21:42 UTC
I would like to start attaching TCPs in Knack instead of using the network drive. This functionality was added so I think we should take advantage of it. I think it will make it easier to track TCPs through the review process. For each submittal, I recommend attaching both the submitted TCP and the TCP that was returned, whether it was with comments or the approved version. There’s an attachment tab for each submittal entry that should allow for us to do so. Is this something we can start to implement?

**Comment by amenity** [comment] 2020-09-03 16:48
@ChrispinP @TracyLinder — We [just got a request that I think will be covered by this feature](https://github.com/cityofaustin/atd-data-tech/issues/3867)....

**Comment by ChrispinP** [comment] 2020-12-11 23:27
Need to determine with stakeholders if we should add a replica of the TIA Module Submission Portal for the TCP Tracker so a submitter can add/update submission documents from their own portal page.

**Comment by TracyLinder** [comment] 2020-12-16 16:26
@TracyLinder include scoping this in the ROW Portal product review meeting

**Comment by TracyLinder** [comment] 2021-08-17 15:46
This is a duplicate of #3867, which is in progress. 
Closing.

**Closed by TracyLinder** 2021-08-17 15:46 UTC
Labels: Workgroup: ROW, Type: Feature, Impact: 3-Minor, Service: Apps, Need: 2-Should Have, Product: ROW Portal, Project: TCP | Traffic Control Plans
