### ISSUE TITLE
Project: UKG Digital Timekeeping System

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#11415] opened 2023-02-08 17:17 UTC
We're supporting the department during the transition to the new, Citywide UKG digital timekeeping system.

## Background

The UKG Timekeeping system implementation is a City-wide initiative to get all City of Austin departments completing timesheets within the same system. ATD is in the Group 4 migration to using the UKG system and is following this project timeline per direction from CTM.

This project will impact all employees, permanent and temporary, and the deadline ATD is following is out of our control. Jennifer with HR and Gilda with the administrative group are spearheading this project, but DTS has stepped in to provide technical support. 

## Scope

DTS met with Anthony S (Assistant Director), Jennifer (HR), and Gilda (Administrative) and we identified the project components that DTS will support:

- Usability testing in the UKG environment for various hardware devices

- Interviews with the ATD Divisions to conduct research and document functionalities they need in the UKG system

- Interviews with Departments to conduct research and capture their lessons learned/tips 

- DTS to be the technical liaison between ATD and CTM

- Meet with ATD group internally to debrief after “Reoccurring CoA Group 4 Digital Timekeeping Meeting for Departmental Experts”

- DTS participates in train the trainer meetings and trainings 

- Works with HR on technical documentation for training

### Users Impacted
**How many users?** 390 ATD employees
- Exempt: (?)
- Non-Exempt: (?)

**What kind of hardware will your primary users rely on?** 

- Timeclocks(?)
- Desktop
- iPad
- Samsung tablet
- Brazos devices
- Mobile devices

**Do you need user roles to do different things in a system?** 
- Timekeepers
- Supervisors and Managers 
- Exempt employees
- Non-exempt employees

**Who needs the ability to view the solution/app?**
- ATD staff

**Who needs the ability to edit the solution/app?**
- ATD staff

**Who will perform user account management?**
- CTM Active Directory SSO

**Integrations**
- CTM is integrating UKG with Banner HR system. 

## Workflow
- The user submits leave requests to be approved by Supervisor/Manager.
- The user submits timesheets to be approved by Supervisor/Manager.
- The Super/Manager submits the timesheets and leave requests to be reviewed by timekeepers. 

## Solutions
- UKG Timekeeping System is the solution

## Resources
SharePoint folder: [UKG Timesheet System Implementation Project](https://cityofaustin.sharepoint.com/sites/ATDAdministration/Shared%20Documents/Forms/AllItems.aspx?id=%2Fsites%2FATDAdministration%2FShared%20Documents%2FUKG%20Timesheet%20System%20Implementation%20Project&viewid=7b48fa95%2D4cf0%2D4a90%2D8716%2De8eb2864c855)
[UKG Discovery Effort - ATD](https://cityofaustin.sharepoint.com/:w:/r/sites/ATDAdministration/_layouts/15/Doc.aspx?sourcedoc=%7B5C47E45D-FEE8-41EF-B4C8-52C230F6F987%7D&file=UKG%20Discovery%20Effort%20-%20ATD.docx&action=default&mobileredirect=true)
[UKG Discovery Effort - Other Departments](https://cityofaustin.sharepoint.com/:w:/r/sites/ATDAdministration/_layouts/15/Doc.aspx?sourcedoc=%7BD1414F79-7E1F-4F5D-A6F3-8E4762860F61%7D&file=UKG%20Discovery%20Effort%20-%20Other%20Departments.docx&action=default&mobileredirect=true)
[UKG Migration Project Implementation](https://cityofaustin.sharepoint.com/:w:/r/sites/ATDAdministration/_layouts/15/Doc.aspx?sourcedoc=%7BAB9D4DBD-6F1D-4FAC-80B2-B0D5A35B2844%7D&file=UKG%20Migration%20Project%20Implementation.docx&action=default&mobileredirect=true)
[UKG Project Timeline](https://cityofaustin.sharepoint.com/:x:/r/sites/ATDAdministration/_layouts/15/Doc.aspx?sourcedoc=%7B95528245-5CC6-485C-9A05-CD3044FD22D4%7D&file=UKG%20Project%20Timeline.xlsx&action=default&mobileredirect=true)

![image](https://user-images.githubusercontent.com/21112975/220785563-4fe6d6aa-abad-4b8c-8909-4f95bf1f7db0.png)

---
This Github issue represents a project of Austin Transportation's [Data & Technology Services](https://austinmobility.io/) team. Project status is documented regularly in the comments below.

**Comment by ChristinaTremel** [comment] 2023-04-27 16:22
## Project Updates - 4/27/2023
Over the past 2 and a half months, DTS has provided support to the Administrative and HR team at PWT to assist in the roll out of the UKG Digital Timekeeping System.
- Usability testing in the UKG environment for various hardware devices:
    - Tested functionality of various hardware (desktop, iPads, Surface Pros, and Brazos devices) and included information/screenshots about how UKG works on various devices while training staff. Users were walking through submitting/approving timesheets, adding TKs, and submitting/cancelling leave requests while in the UKG Trainings.
    
- Interviews with the ATD Divisions to conduct research and document functionalities they need in the UKG system:
    - DTS led 4 interviews with Arterial Management, Signs & Markings, Transportation Engineering, and Parking Enterprise to document standard timesheet processes and understand the work rules a typical timesheet includes (Call Back, Shift Differentials, Task Orders).
    
- Interviews with Departments to conduct research and capture their lessons learned/tips:
    - DTS, HR, and Admin teams met other Departments that had already implemented the UKG timekeeping system to document their tips and lessons learned
    
- DTS to be the technical liaison between ATD and CTM:
    - Christina (DTS) joined the Train the Trainer meetings to be the technical liaison for ATD.
    - Diana and Christina attended the reoccurring meetings for Department Experts and acted as technical liaisons to ask for UKG app enhancements or confirm functionality works for the timesheet processes at ATD.
    
- Strategized and implemented ATD Project Plan for Rollout of UKG Timekeeping System
    - DTS built SharePoint page for communicating training plan (April 3rd-April 21st) and providing training resources after the Parallel Testing period started April 24th.
    - DTS created training documentation and presentation for Managers/Supervisors.
    - DTS created UKG Training Plan in coordination with HR, scheduled, and led or assisted in all in-person and virtual meetings.
    
| Date | Training Session | Location | 
| --- | --- | --- |
| 4/3/2023 | **UKG Training Non-Exempt (Dry Run)** | Cameron Training Room |
| 4/5/2023 | **UKG Training Non-Exempt (AMD)** | Cameron Signal Tech Room |
| 4/10/2023 | **UKG Training Non-Exempt (Morning SMD/AMD)** | Cameron Training Room |
| 4/10/2023 | **UKG Training Non-Exempt (Afternoon SMD/AMD)** | Cameron Training Room |
| 4/10/2023 | **UKG Training Exempt (SMD/AMD)** | Cameron Training Room |
| 4/11/2023 | **UKG Training Non-Exempt (ROW/TDS)** | PDC |
| 4/11/2023 | **UKG Training Exempt (ROW/TDS)** | PDC |
| 4/12/2023 | **UKG Training Non-Exempt (PE)** | Rio Grande |
| 4/12/2023 | **UKG Training Non-Exempt (PE)** | Rio Grande |
| 4/12/2023 | **UKG Training Non-Exempt (PE)** | Rio Grande |
| 4/13/2023 | **UKG Training Non-Exempt (Meters)** | Toomey |
| 4/13/2023 | **UKG Training Non-Exempt (PWT)** | Barton Oaks |
| 4/13/2023 | **UKG Training Non-Exempt (PWT)** | Virtual |
| 4/14/2023 | **UKG Training Exempt (PWT)** | Virtual |
| 4/17/2023 | **UKG Training Managers/Supervisors** | Virtual |
| 4/17/2023 | **UKG Training Exempt (PWT)** | Virtual |
| 4/18/2023 | **UKG Training Non-Exempt (PWT)** | Virtual |
| 4/21/2023 | **UKG Training Exempt (PWT)** | Virtual |

**Comment by ChristinaTremel** [comment] 2023-08-21 20:23
## Status Update - 8/21/2023

### Legacy ATD UKG Updates

The UKG Dev system and parallel testing was rolled out the pay period starting on 4/23/2023. DTS supported the parallel testing by monitoring and answering questions on the `TPW UKG Staff Resources` teams channel and when employees reached out to us directly. We helped point staff to resources created by CTM and internal guides created by TPW. 
- In June, TPW staff was asked to stop entering in timesheet information into PWD eTimesheets and to one use UKG Dev. The planned timeline for ending the testing period was the end of June, but had to continue working in dev a couple more pay periods to fix issues with employees timesheets.
- July 16th, legacy Austin Transportation staff moved into using the UKG Production site.

### Legacy PWD UKG Updates
- Legacy Public Works is still working through issues before going live in Production. More training was needed for legacy PWD staff because they did not have as many training opportunities before going into UKG Dev. HR worked with the Admin team and coordinated the training schedule below for staff. DTS provided Chromebooks to HR for the trainings and was ready to jump in with leading/assisting with the training itself. Matt with DTS assisted by setting up the Chromebooks for the trainers prior to the training starting.
   - 7/24/2023: **Timekeepers Training Overview Session** - BOP
   - 7/25/2023: **Non Exempt Dimensions Training** - Saint Elmo 
   - 7/25/2023: **Non Exempt Dimensions Training** - Saint Elmo 
   - 7/25/2023: **Non Exempt Dimensions Training & Q&A** - Virtual
   - 7/25/2023: **Non Exempt Q&A Session** - Saint Elmo
   -  7/25/2023: **Exempt Q&A Session** - Saint Elmo
   -  7/26/2023: **Non Exempt Dimensions Training** - Townview
   - 7/26/2023: **Non Exempt Dimensions Training** - Kramer Lane
   - 7/27/2023: **Non Exempt Dimensions Training** - Dalton
   - 7/27/2023: **Non Exempt Dimensions Training** - Townview
   - 7/28/2023: **Non Exempt Dimensions Training** - Townview
   - 7/28/2023: **Non Exempt Dimensions Training** - Townview
   - 8/3/2023: **Non- Exempt Timeclock Training** - Texas One Center

- Target date for legacy PWD staff to move into UKG Production is 8/28!

**Comment by ChristinaTremel** [comment] 2023-09-29 19:43
## Status Update - 9/29/2023
Legacy PWD staff and legacy ATD staff are all using UKG Production as of now. Although there are still issues that TPW is working through, these issues are being resolved by Administrative TPW staff. Confirmed with HR that DTS resources are no longer required because issues are being resolved at an individual level now. 

Closing out this project! ✅

**Closed by ChristinaTremel** 2023-09-29 19:43 UTC
Labels: Workgroup: OOD, Workgroup: HR, Type: IT Support, Service: Apps, Service: Product, Epic, Project Index, Project: UKG Digital Timekeeping System
