### ISSUE TITLE
[Bug] Edit Time Log Form Fails to Load

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#1217] opened 2020-01-20 18:32 UTC
After clicking the "Edit" time log button, the edit form fails to load.

Here's the edit button:
![Screen Shot 2020-01-20 at 12.31.31 PM.png](https://images.zenhubusercontent.com/5caf676becad11531cc417cb/d9471c2b-7a78-4034-81e3-7d8e81649e18)

And here's the error message on the page that opens:
![Screen Shot 2020-01-20 at 12.30.35 PM.png](https://images.zenhubusercontent.com/5caf676becad11531cc417cb/7c3816f3-95c1-4045-a865-b85e43a5c2c5)

**Comment by johnclary** [comment] 2020-01-20 18:33
@mddilley here's your issue for the time log issue we've discussed. Let me know if i can help with anything. thanks.

**Comment by mateoclarke** [comment] 2020-01-21 20:24
This one is a duplicate of https://github.com/cityofaustin/atd-mobile-signals-work-orders/issues/240. Going to close the other one since this issue is already in the mono repo.

**Comment by mateoclarke** [comment] 2020-01-21 20:25
_More info from the closed duplicate issue:_

> 
> Jorge came by and showed us a bug where an existing `Time Log` resets to the current time when going through the editing process. The desired behavior is to populate the entire form with the existing record information, and then allow the user to edit the log. This test record also breaks the app when attempting to edit a time log (error below).
> 
> Also. change title of view from `New Time Log` to `Edit Time Log`.
> 
> Test record:
> https://mobile-signals.mobility.austin.gov/work-order/5d77b278b4f2ca0012f620d3/edit-time-log/5d77b28b63f52c001282306c
> ### Broken app
> <img width="1367" alt="Screen Shot 2020-01-16 at 2 33 40 PM" src="https://user-images.githubusercontent.com/37249039/72560869-87d9a580-386d-11ea-86cd-9527779e7160.png">
> 
>

**Closed** 2020-01-27 17:40 UTC
Labels: Need: 1-Must Have, Project: Mobile Signal Work Order, Service: Dev, Type: Bug Report
