### ISSUE TITLE
[Update] TIA Email Process for Comments, Scope, Attachments, and Submissions

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#3695] opened 2020-08-14 04:28 UTC
### When adding a scope type comment on TIA Review details and updating the Scope status to 'Approved', the system is sending the 'Request Submission' email to the customer. 
- The Request Submission email should only be sent when the user clicks the button 'Request Submission' from the review details page.

**Comment by TracyLinder** [comment] 2020-08-14 04:46
I just updated the title & description after doing more testing

**Comment by ChrispinP** [comment] 2020-08-14 22:34
I believe this is working as intended when scope status changes.
![image](https://user-images.githubusercontent.com/67915167/90297347-c4956b80-de53-11ea-871b-2690be628185.png)

@TracyLinder do you have a copy of the email you recieved? I do not see 'Request Submission' text, just that Scope is approved and that a submittal and documents are needed to continue the review process.

**Comment by TracyLinder** [comment] 2020-08-28 21:00
I need to clarify with the stakeholders at what point in the workflow they'd like to request submission, so we can know how to design the solution.

**Comment by TracyLinder** [comment] 2020-09-03 19:58
See #3872 this has been clarified

**Comment by ChrispinP** [comment] 2020-09-28 17:01
now that changes have been made to send a notification email to the requester on comments, attachments, and scope, the request submission button may need a new field added that allows the type of submission the reviewer is requesting thus eliciting better detailed notification emails to the requester. Would create an email template for each type of submission.

@TracyLinder should i go ahead and make this change or should we consult stakeholders again?

**Comment by ChrispinP** [comment] 2020-11-09 18:50
Emails updated for all submissions. Email status is set upon submission and based on different submission types such as if its a General Comment vs a Scope Attachment, all emails have been customized accordingly.

**Comment by ChrispinP** [comment] 2020-11-25 18:44
Email template was again updated. May get updated once more in the future. Attempting to make them look as professional as possible. closing

**Closed** 2020-11-25 18:44 UTC
Labels: Need: 2-Should Have, Product: TIA Module, Service: Apps, Type: Bug Report
