### ISSUE TITLE
[Enhancement] Add project tags to project list view

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#10358] opened 2022-09-30 16:36 UTC
Now that we can [search by project tag](https://github.com/cityofaustin/atd-data-tech/issues/10288), we need to add project tags as a column to the main projects list.

This column can be hidden/not selected by default.

This _should_  be a front-end change only—the query is already configured.

**Comment by chiaberry** [comment] 2022-10-18 21:56
duplicate of this https://github.com/cityofaustin/atd-data-tech/issues/10290

**Closed by chiaberry** 2022-10-18 21:56 UTC
Labels: Service: Dev, Need: 1-Must Have, Type: Enhancement, Project: Moped v2.0
