### ISSUE TITLE
Update project component terms in the database

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#6923] opened 2021-08-11 21:08 UTC
## Requested
- Rain garden - Alan & Ella

**Comment by johnclary** [comment] 2021-08-11 21:45
@amenity i just went through the facility types spreadsheet again, and there are just a handful that i'd feel confident in w/o NW's input. I think we should just hold off on this until we get further feedback. Will get Renee's subcomponent additions in at that time as well.

**Comment by johnclary** [comment] 2021-09-22 21:36
Given that we have the signal components, we can save this for v2.0. Label updated.

**Comment by johnclary** [comment] 2022-05-26 17:04
Closing as a dupe of https://github.com/cityofaustin/atd-data-tech/issues/5357 - i've added "Rain Garden" to that issue.

**Closed by johnclary** 2022-05-26 17:04 UTC
Labels: Type: Data, Service: Dev, Product: Moped, Project: Moped v2.0
