### ISSUE TITLE
[Feature] Ability to add a unit code if it's not listed

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#4329] opened 2020-10-30 21:24 UTC
Per Ronnie, when using back-chargeable task orders we must assign the unit (the "U" in FDU) to another department's unit. The vast majority of these are depts 6207 (public works) and 2507 (corridor program?)—we are going to import those via integration.

However, there will be edge cases where we do not have the unit number required for Ronnie to complete his FDU updates. In that case, the user must be able to add a unit code to the units table so that it can be selected from.

**Comment by ChristinaTremel** [comment] 2024-08-21 19:50
- Found this issue and realized it's a duplicate of #17252. Closing this as not planned and will document the solution in the other issue.

**Closed by ChristinaTremel** 2024-08-21 19:50 UTC
Labels: Workgroup: AMD, Type: Feature, Service: Apps, Product: AMD Data Tracker

**Comment by johnclary** [comment] 2024-08-21 19:52
👍 🙏 ♾️
