### ISSUE TITLE
Add all street geometry after ASMP was adopted

### ISSUE THREAD

**Issue by jaime-mckeown** [cityofaustin/atd-data-tech#4955] opened 2021-01-14 19:27 UTC
Need to add all new street segments that have been added to the street segment layer since the ASMP was adopted.

**Comment by dianamartin** [comment] 2021-06-30 15:39
@jaime-mckeown do we still need to do this?

**Comment by jaime-mckeown** [comment] 2021-06-30 15:41
Yes, it should be in the backlog. Why are you checking Geo Issues? Just curious...

**Comment by dianamartin** [comment] 2021-06-30 15:48
I just noticed it when I was doing Sprint Planning, it was in there for 5 months.

**Comment by jaime-mckeown** [comment] 2021-06-30 15:49
Under New? Things always seem to get lost in GitHub, thanks!

**Comment by dianamartin** [comment] 2021-06-30 15:57
Yeah, it was in the "New" pipeline

**Comment by johnclary** [comment] 2021-09-15 18:08
@jaime-mckeown is this related to updating the CTN? In which case it is a duplicate of work andrew is doing. But I wasn't sure if this was referring specifically to an ASMP layer

**Comment by jaime-mckeown** [comment] 2021-09-15 18:18
@johnclary I think this was specially referring to the ASMP Street Network, but it's fuzzy now since it was a while ago. It would probably go along with the work Andrew is currently doing.

**Comment by amenity** [comment] 2022-06-06 16:06
@andrewshensky - also thinks this was probably covered during the CTN refactor when they added the ASPMP streets to the CTN.

**Closed by amenity** 2022-06-06 16:06 UTC
Labels: Workgroup: DTS, Service: Geo, Product: CTN
