### ISSUE TITLE
Project: GIS Sign Asset Management

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#662] opened 2019-10-11 19:10 UTC
Sign data management work related to the [citywide sign data collection effort](https://austinmobility.io/projects/131).

## Background

This project is a collaborative effort between DTS and the Signs & Markings Division to improve the workflow and management of sign assets throughout the city. The main goal of this project is to establish a workflow to integrate ongoing sign installs and removals into mapped sign data provided by an outside contractor.

## Scope & Deliverables

- Establish standardized schema for sign assets 
- Develop process to identify sign assets installed and removed after lidar mapping has taken place
- Create maintenance workflow to integrate ongoing installs and removals with lidar mapped sign data
- Establish ongoing QC process and train technicians to ensure adequate data integrity.

## Desired Outcomes

To have a single updated and maintained dataset holding all sign asset data throughout the city. 

## Timebox

Lidar mapped sign data will be provided by an outside contractor through the end of November 2022. By the end of 2022 all sign assets throughout the city should be mapped and maintenance workflows should be in place to keep all sign asset data updated.

![image](https://user-images.githubusercontent.com/80716478/168835539-71676809-b6eb-4dd9-a956-65eb465f8cbc.png)

---
This Github issue represents a project of Austin Transportation's [Data & Technology Services](https://austinmobility.io/) team. Project status is documented regularly in the comments below.

**Comment by johnclary** [comment] 2019-10-21 20:30
Question: can you use arcpro attribute rules on a feature service?

**Comment by johnclary** [comment] 2019-11-18 20:07
@alan-deanda schedule a meeting with diana and me to discuss

**Comment by johnclary** [comment] 2020-01-22 18:39
@alan-deanda would you schedule a meeting with Diana, Jaime, and me to discuss?

**Comment by alan-deanda** [comment] 2020-01-23 16:28
Meeting scheduled

**Comment by johnclary** [comment] 2020-02-19 18:32
@alan-deanda plz add your notes here

**Comment by amenity** [comment] 2020-08-10 22:11
@alan-deanda @johnclary - Any updates here?

**Comment by alan-deanda** [comment] 2020-08-11 18:22
@amenity I met with Christina Tremel, Diana and Jaime in late January 2020 to come up with a strategy to begin doing GIS QA for Signs Work Orders. We decided to start focusing on migrating our current GIS QA Markings Work Orders to ArcPro first, but that hit a couple of snags, and then the pandemic began. Our priorities are still shifted, as only since the last Discovery Day was Jaime able to focus on migrating Markings to ArcPro.
The Speed Limit Change project has renewed interest in all things Signs, so perhaps soon we'll be able to start looking at this more closely. The biggest obstacle is competition from other incoming/higher priority issues, especially since the pandemic began.

**Comment by jaime-mckeown** [comment] 2020-08-11 18:30
@amenity I've been focused on getting the Parking Migration completed, but am almost done. I should be able to start working on the Markings to ArcGIS Pro soon.

**Comment by jaime-mckeown** [comment] 2020-11-30 20:59
Moving Issue back into the Backlog until the Signs Data Collection Project gets underway. We will start working on this piece when we start getting weekly data inputs from the Vendor.

**Comment by andrewshensky** [comment] 2022-06-27 13:08
6/27/2022 - Official pilot data has been received from the vendor and approved by ATD staff. Our next round of data delivery is scheduled to take place this week (6/27). DTS is currently tracking all sign installs/removals and working on processing procedures to merge the install/removal data with the vendor data. We have created an internal QC web app allowing SMB to QC and review data delivered by the vendor prior to appending the data into or production dataset. The vendor data and internal install/removal data will be merged together once data is reviewed and approved by SMB. DTS has also begun conversations with SMB to start discussing our data management/workflow plan going forward once all sign data has been collected.

**Comment by andrewshensky** [comment] 2022-07-25 12:57
7/25/2022 - The first round of vendor data has now been uploaded to our production dataset and combined with signs that have been installed or removed after vendor data collection. Our current feature counts in our production dataset are below:

**Total Signs Assets:** 25,215
**Sign Assets Requiring QC:** 1,862
**Locations:** 7,625

The vendor has provided the second round data as of 7/22. We are currently working to review that data delivery and associated photos, then will be uploading that data to our internal AGOL viewer allowing SMB to QC. Following SMB QC and review, this data will be pushed to our production dataset in maint.

**Comment by andrewshensky** [comment] 2022-09-16 19:26
9/16 - The Round 3 vendor data delivery has now been added to the production dataset. SMB is finalizing QC of the Round 2 data delivery, which is planned to be added to production by the week of September 26th. We met with the vendor today and they confirmed they are on track for the final two data deliveries scheduled for October 14th and November 30th. Current feature counts are below:

**In Production**
Total Signs Assets: 47,017
Sign Assets Requiring QC: 2,228
Locations: 14,740

**Round 2**
Assets: 49,998
Locations: 15,302

**Comment by andrewshensky** [comment] 2023-01-09 14:22
1/9 - RAS has now provided their final data delivery, which is inclusive of a large area of 125,623 sign assets. Since this final delivery has been provided, we have now appended the data from all previous deliveries into our production dataset. We are currently in the process of updating our internal Sign QC web app so SMD can begin QCing the final data delivery. Once initial QC is completed these assets will be appended to production, which will be the last step in processing RAS Data into production. The SMD QC process will likely take longer than previous deliveries due to the size of this delivery being nearly 3x larger than others. DTS has also had two new GIS Technicians join the team, which will play a large role is reducing the number of Sign Assets Requiring QC in Production.

**In Production**
Total Signs Assets: 146,949
Sign Assets Requiring QC: 2,603
Locations: 45,804

**Currently being QC'd by SMD**
Assets: 125,623
Locations: 39,474

**Comment by andrewshensky** [comment] 2023-05-01 14:13
5/1 - Our current sign inventory data contains 148,708 sign assets at 46,544 unique locations throughout the city. Our GIS technicians have made great progress in QCing the ongoing sign installs and removals, which is being captured in our work order data. They have been able to reduce the count of features needing QC to 1,598, with the majority of those occurring in areas where we are still awaiting the final delivery of asset data from RAS. Our SMD team has been working with RAS to refine the classification of sign condition values. We anticipate receiving the final data delivery from RAS in the coming weeks, which should include roughly 125,000 assets at 40,000 unique locations. Once that data is received, it will be appended into our inventory allowing our technicians to continue QCing. It will also make our complete inventory rough 275,000 signs at 87,500 unique locations.

**Comment by andrewshensky** [comment] 2023-07-11 14:47
7/11 - Still awaiting official final data delivery from vendor (about 125,000 sign assets). Current asset counts in production after mid July append from work orders are below:
**Total Sign Assets:** 150,370
**Total Locations:** 47,128

**Comment by andrewshensky** [comment] 2023-09-05 18:15
**9/5/2023 Asset Counts:**

Signs in Maint: 150,501
Locations in Maint: 47,027
Sings in pending to be added to Maint: 123,195
Locations pending to be added to Maint: 38,753
**Estimated Total Sign Count: 273,696
Estimated Location Count: 85,780**

**Comment by andrewshensky** [comment] 2023-10-09 17:46
**10/9/2023**
All sign data from the vendor has now been added to the source database in maint. This data is now being pushed to AGOL and the Enterprise Data Portal on a daily basis.

**Updated asset counts**
Signs in Maint, AGOL, and EDP: 276,075
Locations in Maint, AGOL: 86,530

**Comment by ChristinaTremel** [comment] 2024-09-05 18:16
Since 2023, the geospatial team has been working on streamlining and improving the QC process for the signs dataset. We have a dedicated team of IT geospatial analysts who ensure that the signs dataset stays up to date with the latest sign installs and removals. They have also been working on extensively cleaning up the dataset and ensuring that the naming and MUTCD codes of sign assets are consistent throughout the City. 

The scope of this project has been accomplished and completed! We will be exploring future enhancements to the GIS sign asset management process by looking into the technician process and potentially incorporating the unique sign assets, but this will be captured in a new project.

**Closed by ChristinaTremel** 2024-09-05 18:16 UTC
Labels: Workgroup: SMD, Workgroup: DTS, Service: Geo, Need: 1-Must Have, Epic, Product: SMD Data Tracker, Project Index, Project: GIS Sign Asset Management
