### ISSUE TITLE
Convert Signal Work Order  "Problem Details" field from free text to list

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#1465] opened 2020-02-25 16:15 UTC
Replace free-text work order entry with discrete data capture of maintenance work at traffic signals. 

E.g.,
- Battery Back-UP (UPS) maintenance
- Detection
...

See [Brian's lists of input categories](https://drive.google.com/drive/u/2/folders/1SieSTJf-hQShibgFU_fjagje50soTiuB).

**Comment by amenity** [comment] 2020-05-18 06:26
This is a duplicate of #1880.

**Closed** 2020-05-18 06:26 UTC
Labels: Need: 2-Should Have, Product: AMD Data Tracker, Service: Apps, Type: Enhancement, Workgroup: AMD
