### ISSUE TITLE
Transportation Development Services AMANDA Training

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#2253] opened 2020-04-03 17:09 UTC
In-depth (possibly a series of meetings) screensharing with TDS analyst to learn about their processes.

**Comment by johnclary** [comment] 2020-04-03 17:29
@SurbhiBakshi would you schedule this one with Sangeeta and Nate? ROW training definitely takes priority over this. FYI @dianamartin

**Comment by SurbhiBakshi** [comment] 2020-04-06 19:11
@johnclary,  @dianamartin - Intro + Training scheduled for April 14th.

**Comment by Nadin-Nader** [comment] 2020-04-21 17:31
Update to this from meeting on 4/14/2020 and 4/16/2020:
4/14/2020
It was more of an overview and catch up to some of the things Tracy was working on and what i need to catch up/follow up on.
Introductions and brief history on their ATD work.
Important Items discussed; ATD Being a part of the Electronic Plan Review/Completeness Check, All fees to be paid on Portal, Add one more Fee code and Mitigation Fees for ATD that are used by DSD to show up on the SP.

Follow Up Meeting on 4/16/2020:
Training on the TIA: Explained what the TIA is used for (to house memo and fee information via attachments/docs or memos
DSD owns the TIA but they would like to have ATD own the folder
Completeness Check not in Electronic Plan Review and they are not being assigned. They stay in the task list and users cant tell which have been worked on.
ATD Engineering Reviw:
Fee is entered manually - this was already put in place on TEST and needs to be deployed to PROD (Fee 83475)
Tasked to check TIA ans SP fees associated with them to see if correct
Discussed that an exact duplicate of ATD ZON-TIA Review Fee is needed but for the SP ATD Engineering Review
Lastly, they are wanting all Fees in TIA to be visible for customers on portal.

**Closed** 2020-04-30 19:36 UTC
Labels: Type: Training, Workgroup: DTS
