### ISSUE TITLE
Host VZ location polygons (street segments) on AGOL

### ISSUE THREAD

**Issue by JaceDeloney** [cityofaustin/atd-data-tech#3316] opened 2020-07-09 16:29 UTC
We would like the VZ locations polygons to be stored in AGOL. This will streamline the management of these layers in the future, and allow for these polygons to become the authoritative data for street segments. We had previously discussed this, but it was never implemented.

**Comment by amenity** [comment] 2022-07-27 18:47
@alan-deanda @frankhereford - this (& #3317, #3318) is no longer needed, right?

**Comment by frankhereford** [comment] 2022-07-27 21:23
@amenity wrote
> @alan-deanda @frankhereford - this (& #3317, #3318) is no longer needed, right?

I think that @andrewshensky & @alan-deanda are the folks who can answer this with authority. 

But .. to your question .. my understanding is that the canonical version of the polygons is hosted on MAINT (#3318) which makes them available to ArcGIS Pro users who can publish them to AGOL as needed (#3317). It does not guarantee that there is an existing map, but that it should be pretty easy to get one up there, albeit not an authoritative copy as MAINT's polygons could get update once the webmap is published. And then this issue, #3316, I think is a duplicate of #3317, unless I'm misunderstanding. I could simply not be clear about what is meant by `(street segments)` in the title also. 🤷🏼

**Comment by alan-deanda** [comment] 2022-08-01 22:24
@amenity if stakeholders still want a webmap of VZ Polygons on AGOL somewhere, then we could keep this issue open. Neither this web map, or an AGOL copy of the VZ Polygons from MAINT have come up in conversation with Lewis.

**Comment by amenity** [comment] 2022-08-02 04:59
@patrickm02L - can you weigh in on this?

**Comment by patrickm02L** [comment] 2022-08-02 11:49
Now that #3317 and #3318 are closed, this epic is good to close. If there's a request for a VZ Polygon webmap in the future we'll take on that Issue on it's own terms.

**Closed by patrickm02L** 2022-08-02 11:49 UTC
Labels: Service: Geo, Service: Dev, Epic, Workgroup: VZ, Product: Vision Zero Crash Data System
