### ISSUE TITLE
New Quality Control Report and Batch email for ROW Permitting 

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#18722] opened 2024-08-21 16:17 UTC
### Create a report that identifies errors with permit folders to be fixed manually by ROW staff. 
**Needs identified on these cards:**
- _#17856_ 
- _#16894_

**Scenarios to report on:**
1. There is **not** a Right-of-Way Contractor people record on an **active** DS, EX permit `ROW Contractor missing`
2. There is more than one Right-of-Way Contractor people record on an **active** DS, EX permit `Multiple Contractors`
3. There is more than one applicant people record on any active permit `Multiple Applicants`
4. The folder status is **Expired**, and the expiration date is in the future. `Expired with future date`
5. The folder status is **Active**, but expiration date is in the past. `Active with past expiration`

**What data to export:**
- FolderRSN
- Folder type, sub-type
- Folder name
- Status
- In date
- Issue date
- Expiration date
- Description
- Issue (ROW Contractor missing, Expired with future date, Active with past expiration)

**Misc:**
1. How often should this job run? -- Weekly
2. What is the requested output format? -- Excel 
3. Who should this email to? -- rightofway@austintexas.gov, Kim P, Paloma, Kyle

**Comment by TracyLinder** [comment] 2024-08-21 20:00
I added this to the Friday ROW agenda for 8/23.

**Comment by SubhaShroff** [comment] 2024-09-04 18:57
@TracyLinder  @Nadin-Nader  
1. Since its a weekly job, should it be fetching only a week old permits?
2. If not checking the date, should we check the status of the permits?

Thank you.

**Comment by TracyLinder** [comment] 2024-09-06 19:58
@SubhaShroff per ROW, they want the data to stay on the report until it's fixed.

**Comment by TracyLinder** [comment] 2024-09-06 20:03
@SubhaShroff please see the updated AC with 2 new scenarios for multiple applicants and contractors. Thank you.

**Comment by SubhaShroff** [comment] 2024-09-09 18:19
@Nadin-Nader @TracyLinder The other two scenarios are also included now. Following is the TEST report result. Please UAT on TEST. Thank you.
[99035_New Quality Control ROW Permit Report as on 9-9-2024..xlsx](https://github.com/user-attachments/files/16934900/99035_New.Quality.Control.ROW.Permit.Report.as.on.9-9-2024.xlsx)

**Comment by TracyLinder** [comment] 2024-09-24 15:20
I think we'll have to create test scenarios in TEST to be able to validate the report.

**Comment by TracyLinder** [comment] 2024-10-11 20:30
We began UAT today in test. ROW is going to validate the data and get back to us.

**Comment by SubhaShroff** [comment] 2024-10-25 18:10
@Nadin-Nader any feedback from stakeholders? can we close it?

**Comment by TracyLinder** [comment] 2024-10-25 19:44
ROW ok with pushing to PROD. FYI @SubhaShroff

**Comment by Nadin-Nader** [comment] 2024-10-25 20:45
@SubhaShroff this has been sent to the CTM Tema to be deployed to PROD under **SCTASK0466106**

**Comment by SubhaShroff** [comment] 2024-10-29 18:04
@Nadin-Nader This is in PROD now.
Report Name - Quality Control ROW Permitting Report (99035)

Thank you.

**Comment by TracyLinder** [comment] 2024-11-01 19:28
ROW will validate the report results that were exported today from PROD.

**Comment by TracyLinder** [comment] 2024-11-22 21:10
### Batch job missing
- @SubhaShroff please create a batch job to email this weekly on Mondays 6am.
- Distribution list is [rightofway@austintexas.gov](mailto:rightofway@austintexas.gov), Kim P, Paloma, Kyle, Russell

**Comment by SubhaShroff** [comment] 2024-11-25 02:45
@TracyLinder @Nadin-Nader What should be the FROM Email for this batch job?
I have got this deployed on DEV and TEST.  It should auto-trigger on every Monday 6am, from tomorrow.

Thanks.

**Comment by KyleErich** [comment] 2024-11-25 15:49
@Nadin-Nader @SubhaShroff I'm approving this on Test. I think we can promote to Prod. Since we only need to receive the weekly automated emails from Prod going forward, should we maybe turn it off in Test now that we've tested that it's working? Thanks.

**Comment by KyleErich** [comment] 2024-11-25 17:04
I'm good with either the FROM email being rightofway@austintexas.gov or an automatic AMANDA email address, if one exists.

**Comment by SubhaShroff** [comment] 2024-11-25 19:46
@Nadin-Nader Kyle confirmed to keep right of way email id as FROM Email ID. With that as Kyle approved, sending this to PROD deployment. SCTASK0472378 - is created for PROD deployment of the batch job.

 Thanks.
![image](https://github.com/user-attachments/assets/a8b418bd-d385-421e-be7a-46dc4d19b1b9)

**Comment by SubhaShroff** [comment] 2024-11-25 22:48
@Nadin-Nader Its deployed in PROD. **Job RSN- 225** on PROD.
We will wait for it to trigger on Monday.
Thank you.

**Comment by KyleErich** [comment] 2024-12-02 14:57
@SubhaShroff @Nadin-Nader UAT on Prod approved. Thanks y'all!
![{4F062002-253E-470B-9E27-73074E23A32F}](https://github.com/user-attachments/assets/d3f83643-f225-4927-b8b2-2fdb0960c29e)

**Closed** 2024-12-02 17:56 UTC
Labels: Workgroup: ROW, Need: 2-Should Have, Type: Reports, Product: AMANDA, Provider: LaunchIT
