### ISSUE TITLE
Explore approach to connect ServiceNow <--> Github/DTS Portal

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#2160] opened 2020-03-23 19:52 UTC
Might start with something fairly manual, e.g. resource account for us and being cc'ed on all service requests
What does that workflow look like?

**Comment by dianamartin** [comment] 2020-04-08 18:30
I talked to Stephanie about this, she said she'd look into but was just waiting on more context of what wanted. 

She understands that we'd like a CTM HD ticket to be reassigned to a work group that multiple people can work. Scott and Jaime, are probably in a work group already we just have to find out what the name is.

**Comment by moorerst** [comment] 2020-04-08 20:25
The workgroup in SN is called ATD_IT - Scott and Jamie are currently the only members of the group. I confirmed that a resource account can be set up to receive email notifications of incidents assigned to the group and/or all members of the group 
![image](https://user-images.githubusercontent.com/56606465/78830125-13fef300-79ad-11ea-9fc8-d86c75a28914.png)

**Comment by moorerst** [comment] 2020-04-08 20:40
If you would like to test what the email notification would look like provide a email address to use.

**Comment by dianamartin** [comment] 2020-04-08 20:41
@moorerst so we can't just have it go to a work group queue unassigned?

**Comment by moorerst** [comment] 2020-04-08 20:48
@dianamartin the tickets get assigned to the workgroup ATD_IT by the service desk, when assigned to the ATD_IT group queue the email notification is sent to group email and/or all members of the workgroup. Then either Scott or Jamie (current members) take ownership by assigning to themselves.

**Comment by moorerst** [comment] 2020-04-08 21:27
https://atx.service-now.com/nav_to.do?uri=%2Fkb_view.do%3Fsys_kb_id%3Df986039d1bf98050c00dba651a4bcbb7%26sysparm_rank%3D1%26sysparm_tsqueryId%3D6dd234b51b84dc10f9edc8451a4bcb79

Other departments have an Amanda workgroup and a GIS workgroup. 
ATD has ATD_Amanda and ATD_IT.  If there was a ATD_GIS workgroup that Jamie was moved to then ideally there would be a specific work queue for ATD Amanda, GIS and IT

**Comment by moorerst** [comment] 2020-04-08 21:38
DSD has their own DSD_IT_Support workgroup in SN. This knowledge article in SN directs the service desk what to assign to the DSD workgroup.
https://atx.service-now.com/sp?id=kb_article&sys_id=b425ba651b4f0414a7951f861a4bcb3e

**Comment by dianamartin** [comment] 2020-04-08 21:53
@moorerst @johnclary @amenity I honestly don't know how Jaime and Scott get the notifications. I guess I should ask them because I'm not clear on the process. We're also in the middle of creating a level 1 triage process for our team. We'd need to figure out how ServiceNow would come into play with this process.

**Comment by moorerst** [comment] 2020-04-20 14:50
@dianamartin just following up on the need for resource account for ServiceNow notifications on incidents assigned to ATD_IT . Do we want to set this up, if so what should be the resource account name?

**Comment by dianamartin** [comment] 2020-04-20 15:00
@moorerst I think we might want to have a meeting with Scott/Jaime to find out what works best for them bc we haven't made the Go-Live happen with the DTS Service Desk yet.

**Comment by amenity** [comment] 2020-04-23 18:55
@dianamartin - are you good to close this out? It sounds like we have a clear path forward (request notifications & access for a resource account) whenever we want to do it.

**Comment by dianamartin** [comment] 2020-04-23 18:59
@amenity As long as we don't put the request in to enable this without talking to Scott/Jaime first

**Comment by amenity** [comment] 2020-04-23 23:06
@dianamartin - Aha I wasn't imagine our course of action on this affecting their work. I thought this would just be a new notification that the Service Desk resource account would receive, independent of the ones they get already. It would just be used by the on-shift service desk support if they needed to see track something down in Service Now.

**Comment by dianamartin** [comment] 2020-04-24 14:06
@amenity based on Stephanie's findings, we can do a few things. The issue is the tickets that Scott might should be going to the DTS Service Desk. So it's a matter of deciding whether Scott/DTS Service desk are in the same queue notifications or we create a different group and it sends it only to Scott and only to the DTS Service Desk (transportation.data email). 

That's why I wanted to short meeting to just understand what Scott and Jaime's process currently are before we add something into the mix. You might be right and they are unaffected, but I don't know their process in depth.

**Closed** 2020-05-05 13:49 UTC
Labels: Project: DTS Service Delivery, Service: Product, Type: Operations, Workgroup: DTS
