### ISSUE TITLE
Locations for VZA

### ISSUE THREAD

**Issue by SurbhiBakshi** [cityofaustin/atd-data-tech#726] opened 2019-10-22 17:09 UTC
@amenity @TracyLinder looks like I created a duplicate. #711 is the right issue. Closing this one. Thanks for bringing this to my notice.

**Comment by amenity** [comment] 2019-10-23 19:02
@SurbhiBakshi - is this maybe a duplicate of #711 ?

**Comment by TracyLinder** [comment] 2019-10-24 20:12
@SurbhiBakshi can you please update this issue? (Pipeline, assignee, labels)

**Comment by amenity** [comment] 2019-10-24 20:27
@SurbhiBakshi - I labeled and pipelined... But still wondering if it is a dupe and/or if it's complete.

**Closed** 2019-10-24 23:40 UTC
Labels: Project: Vision Zero Citation App, Service: Apps, Workgroup: VZ
