### ISSUE TITLE
Publish school beacon data from Data Tracker to ArcGIS Online

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#7737] opened 2021-11-16 15:24 UTC
Todo:
- Review existing school beacon layer on AGOL (link?) [`apps`]
- Decide if we want to update that schema, or create a new layer [`apps`, `geo`]
- Review existing API view for beacons. Update it as needed. [`apps`]
- Setup knack services and ariflow scripts [`dev`]

**Comment by dianamartin** [comment] 2021-12-15 23:41
Started comparing the AGOL feature layer and new Knack school beacon object table
- `School Zone Beacons` - feature layer
- `atd_school_flashers_production` - point layer

In AMD Asset Map
- Web Map: `Traffic Signal Assets`
- Web App: `Assets - Austin Transportation Arterial Management`

**Comment by dianamartin** [comment] 2022-01-04 21:54
It's looking like the data fields are more closely aligned with the data collection SZB layer than the existing one. I've synced with Allyson on 1/3 to see if she could tell if the MMC staff were using all the fields in the new SZB add/edit forms. 

- [ ] Will need to evaluate the existing SZB API table

**Comment by dianamartin** [comment] 2022-01-10 19:54
Create new data set for this effort

**Comment by dianamartin** [comment] 2022-01-12 15:52
Sync'd with Jorge, Ed and Billy and we were talking about something SZB related, I was able to ask them what they wanted to see on the GIS pop-up box

- DISPLAY NAME?
- ZONE NAME
- ZONE ID
- CLOCK
- BEACON
- DIRECTION
- SCHOOL NAME
- START TIMES
- END TIMES
- WEB IO

**Comment by amenity** [comment] 2022-01-12 16:55
Discussed in planning:
- Can delete existing API view and do a fresh one on the same page; view # is what matters
-

**Comment by dianamartin** [comment] 2022-01-13 20:17
I check w/ John yesterday - 1/12, 
>For the SZB API table, do I need to change the field names on the table or leave them as is?

he replied
>yep, and the field names on the AGOL layer need to match the field names on the knack object: except spaces can be underscores and upper/lower case does not matter

**Comment by dianamartin** [comment] 2022-01-13 22:55
Ear marked fields to be deleted due to the fact they're not being used in the Details page or Add/Edit forms. 
- OBJECTID - Number
- Zone Number - Number, comes from SZ table
  - [ ] Need to create new field `SZ ID`
- Beacon ID - Number, `Beacon ID Short` is sufficient bc it requires 2 digits like (ex. `00`)
- SZ Beacon ID - Short Text, new field `SZB ID` is txt formula that comes from SZ table
- Zone Name, Short, new field `SZBZ Name` is txt formula that comes from SZ table
- School Name - Short, new field `School Name SZ` is txt formula that comes from SZ table
- AM Start Time - Date/Time, references SZ table on main table
- AM End Time - Date/Time, references SZ table on main table
- PM Start Time - Date/Time, references SZ table on main table
- PM End Time - Date/Time, references SZ table on main table
- PM 2nd Start Time - Date/Time, references SZ table on main table
- PM 2nd End Time - Date/Time, references SZ table on main table
- AM Plan - Short, references SZ table on main table
- PM Plan - Short, references SZ table on main table
- PM Plan 2 Display - Short, references SZ table on main table
- Web-IO Name - Short, references SZ table on main table
- Creator - Short, comes from AGOL 
- Editor - Short, comes from AGOL
- GlobalID- Short, comes from AGOL

**Comment by dianamartin** [comment] 2022-01-18 14:36
I asked John on 1/14
>Should I just  have Jaime set up the same fields for Location Name and Lat/Long?

John said
>we only need location_name. the lat/lon columns have been deprecated

**Comment by dianamartin** [comment] 2022-01-18 14:50
@jaime-mckeown Here is a spreadsheet that you can use to build out that empty layer in AGOL. I have it separated by Alias, AGOL field headings, KNACK field headings and the type. Use the AGOL headings to create it, let me know if you have any questions
[school_beacons_API_new_20220113.csv](https://github.com/cityofaustin/atd-data-tech/files/7889935/school_beacons_API_new_20220113.csv)

**Comment by jaime-mckeown** [comment] 2022-01-18 17:56
- Created new point layer under working FGDB for SZB using csv from Diana, and published to AGOL under the ATD Scripts Publisher account.
- Overview: https://austin.maps.arcgis.com/home/item.html?id=ebde70df086942c286dcf9f3f3449f2f
- REST: https://services.arcgis.com/0L95CJ0VTaxqcmED/arcgis/rest/services/School_Zone_Beacons/FeatureServer

**Comment by dianamartin** [comment] 2022-01-26 14:33
@johnclary I confirmed the new empty feature class matches what I have in the new API table. This is ready for dev team to integrate Knack to AGOL.

**Comment by chiaberry** [comment] 2022-02-16 22:40
I'm getting this error when I try upserting to agol: `ValueError: {'code': 1000, 'description': 'String or binary data would be truncated.\r\nThe statement has been terminated.'}`

@jaime-mckeown Could this be republished with longer field lengths? thanks in advance

**Comment by amenity** [comment] 2022-02-23 18:24
Thanks, @chiaberry @jaime-mckeown @alan-deanda 

Should we remove these older datasets? 
![Screen Shot 2022-02-23 at 12 19 30 PM](https://user-images.githubusercontent.com/1463708/155382681-4c138619-1a24-4556-bece-aa5493bff792.png)

Also, how often should the data be updating?

**Comment by dianamartin** [comment] 2022-02-23 19:31
@amenity Chia told me it's updating daily bc she asked me what frequency it should be and I said daily sounds about right.

**Comment by chiaberry** [comment] 2022-02-23 19:35
I haven't merged the script to update daily yet. It's been approved so I will this afternoon.

**Comment by amenity** [comment] 2022-02-23 19:37
Aha, that makes sense. Thanks, @dianamartin @chiaberry.

**Comment by dianamartin** [comment] 2022-02-23 19:43
Will email stakeholders tomorrow 2/24, will wait until ETL is finalized. @jaime-mckeown did the new school beacons layer get added to the AMD asset map yet?

**Comment by jaime-mckeown** [comment] 2022-02-23 20:12
@dianamartin this is the first I've heard that the new layer went live. I will get the maps updated.

**Comment by amenity** [comment] 2022-02-23 21:30
@jaime-mckeown - will you drop a link to the AGOL map here when you're done, please? I was confused which one it is.

**Comment by jaime-mckeown** [comment] 2022-02-23 21:33
@amenity there are multiple maps that have SZB data in them, I assume that you are looking for the main AMD assets map that Diana mentioned.

**Comment by amenity** [comment] 2022-02-23 22:54
@jaime-mckeown - Aha, wrong terminology: I meant a link to the AGOL page for the feature layer. I assume it is [this one](https://austin.maps.arcgis.com/home/item.html?id=1ba4378ad37f41eb8907d66ff0df7eba) and that [the other two](https://austin.maps.arcgis.com/home/search.html?q=school%20zone%20beacons) are obsolete?

**Comment by jaime-mckeown** [comment] 2022-02-23 22:58
@amenity below is the new one, it's easier to tell now as all feature layers created via scripts from Knack are owned by the ATD Scripts Publisher.
https://austin.maps.arcgis.com/home/item.html?id=ebde70df086942c286dcf9f3f3449f2f

**Comment by amenity** [comment] 2022-02-23 23:10
@jaime-mckeown - super, thanks!

**Comment by dianamartin** [comment] 2022-02-24 16:39
Just checked out the new SZB Layer that Jaime linked and spot checked known new records - `Overton` and `Norman`. They show up spatially. 

Checking the AMD Asset map this morning, looks like it's still the old SZB layers. I'm going to wait for @jaime-mckeown to update the map and then I'll send that email to stakeholders today.

**Comment by jaime-mckeown** [comment] 2022-02-24 16:42
Sorry @dianamartin I'm juggling a ton right now. I will ask Andrew to update so it gets done.

**Comment by jaime-mckeown** [comment] 2022-02-24 17:45
@dianamartin the Assets Web Map has been updated. I will any other maps that have the SZBs as well today.
https://austin.maps.arcgis.com/apps/webappviewer/index.html?id=c9bda776b1934e439285570b29d3259c

**Comment by jaime-mckeown** [comment] 2022-02-24 19:25
Set the new School Zone Beacons layer as Authoritative in AGOL.

**Comment by johnclary** [comment] 2022-03-02 19:43
@dianamartin plz update and close. thank you @jaime-mckeown !

**Comment by dianamartin** [comment] 2022-03-02 19:44
I emailed stakeholders on 2/24

>Hi all, 
The process to update the “school beacon zones” layer in GIS from Knack should be updating on a daily frequency now. Just letting everyone know so they can check the asset map to review and QA/QC the new changes.
>- You’ll noticed that you have more fields to reference in the pop-up box. 
![image](https://user-images.githubusercontent.com/21112975/156437782-d2cbbd74-fd8e-4b2d-8d07-939f91501a79.png)
Let us know if there are any other changes/bugs you find.

**Closed by dianamartin** 2022-03-02 19:44 UTC
Labels: Workgroup: AMD, Service: Geo, Service: Dev, Service: Apps, Product: AMD Data Tracker, Project: Beacon Data Tracking, Type: Integration
