### ISSUE TITLE
Update CSR Activities with Activity Outcomes

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#9815] opened 2022-07-20 19:00 UTC
Ask 311 if they (citizen) sees the "Details" 

# Background
Citizens when calling in to 311 customer services can only see "Review Interface Request". With 311 audit and standards initiative, they want more descriptive categories. We had been adding the "Activity Name" to the details portion of the "Review Interface Request".

**Comment by dianamartin** [comment] 2022-07-20 19:32
# Before
![image](https://user-images.githubusercontent.com/21112975/180065700-5f0727b0-ed47-4f93-a89e-15115492c131.png)

# After
![image](https://user-images.githubusercontent.com/21112975/180066455-088f5602-3d6a-4058-8b15-0583b98488b6.png)

**Comment by dianamartin** [comment] 2023-03-03 21:12
## Update 3/3/23
311 Standards are making ATD change the way we've configured the 311<>Knack integration. We've been having conversations with ESB team (Robert) and 311 (Patrick) on how we can accomplish this. Recently, Patrick requested the XML file from Motorola and we are still trying to figure out how to update the Activity Name from "Review Interface Request" to the more meaningful "Activity Name". 

@johnclary did you already have an issue for this? I repurposed this one because it was empty.

**Comment by ChristinaTremel** [comment] 2023-09-12 14:42
## Update 9/12
- Over the past 4 months, we have been meeting with the 311 team (Carrie and Patrick), Robert with CTM, John, and myself to continue moving on this project. 
- We have successfully tested these updates in test for both AMD and SMD and are ready to go live with the changes in Production.
- We are now getting ready for deployment. To ensure we're ready, John needs Robert to update a couple ID fields, but Robert said that should only take him 15 minutes. 
- Planning out deployment, the actual process to go live will take around 4 hours of downtime. Planning to work on things today and tomorrow and regroup on Thursday. 
- Talking about trying to do the deployment next week before Wednesday (Monday seems to work for everyone).

**Comment by ChristinaTremel** [comment] 2023-10-05 21:33
## Update 10/5
- The week of 9/25-9/29 we started making the changes necessary in production to push CSR activities with activity outcomes

- **9/29** 
   - Robert with CTM made required changes in the ESB
   - John started making updates required on the Knack. Ran into some issues that were troubleshooted with Robert and additional ESB changes were needed. 
   - John had an SSL configuration issue with our host server that he had to resolve. 
   - By the end of the day on Friday, the activities were updating with activity outcomes as requested, but we didn't get the paging activities to work because of known issues that John was working through.
   
- **10/2**
   -  Met to troubleshoot issues with the Paging Activity. Also had issues with 311 over the weekend, but resolved those.
   - As of Monday afternoon: We are now live in Production with standardization for Knack. All of the activities are flowing successfully through the interface with the exception of the paging activities. We will continue to troubleshoot that issue, as well as John will continue to work the activities for all the SRs that were created last Friday and any created over the weekend. Once John has processed the activities, I will verify them in CSR. 
   - John also worked to process the backlog of AMD and SMD activities that were occurring over the weekend when there were issues with 311<>Knack.
   
- **10/4**
   - Patrick 
   > We confirmed in this chat that all activities are coming through as expected. You are now seeing the paging activities in Knack, so I think we're good.
   - Carrie: 
   > Does this little conversation mean we are done done with the Knack interface? 
   - Patrick: 
   > I think we can safely say we're done with Knack. Thanks everyone for all your hard work. 🎉

@johnclary do you want to add any more notes to this issue? And do we have anything outstanding before closing it out? 🙂

**Comment by ChristinaTremel** [comment] 2024-01-12 14:48
This was completed October 2023. 🎉

**Comment by ChristinaTremel** [comment] 2024-01-12 14:48
This was completed October 2023. 🎉

**Closed by ChristinaTremel** 2024-01-12 14:48 UTC
Labels: Workgroup: AMD, Service: Apps, Type: Enhancement, Product: AMD Data Tracker
