### ISSUE TITLE
Feature: TIA Submissions Cycle Number

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#4771] opened 2020-12-22 21:23 UTC
### As a TIA Reviewer, I need to know and easily identify the Submission Cycle number.
- Preferable the cycle number would be easy like 1, 2, 3...
- Add column to TIA submissions table overview page, and TIA Submission Details page

**Comment by TracyLinder** [comment] 2020-12-22 21:24
@ChrispinP I put this on sprint 42 in case you wanted more user input before developing.

**Comment by ChrispinP** [comment] 2020-12-29 00:53
On Request object, submission count field counts submissions and increment submission cycle equation adds +1.
On Submission object, text formula pulls in the equation value, and the submission cycle field, if blank, is set to the text formula value.

Added Submission Cycle field to corresponding submission details pages and submission tables and updated sorting by cycle number. Also appended cycle number the the display field for the submission object.

If possible, we may want to limit new submission creation to only one at a time otherwise there is the possibility that submission cycles get out of sync when a user creates multiple submissions, say for example submission 5 and 6 but submits 6 before 5 or submits 6 and deletes 5 after. To solve we would therefore have to hide the New Submission button when one is already available to be edited.

Ready for testing and review

**Comment by ChrispinP** [comment] 2021-02-10 18:02
This is working as intended. Added css to show the button as disabled to prevent multiple submissions. Created another issue to also prevent the button from being clickable. No further issues, closing.

**Closed** 2021-02-10 18:03 UTC
Labels: Need: 1-Must Have, Product: TDS Portal, Project: TIA Module, Service: Apps, Type: Enhancement, Workgroup: TDSD
