### ISSUE TITLE
Feature: Improved Beacon Tracking

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#493] opened 2019-08-15 15:54 UTC
Refactor school zone beacon tracking, support clean-up of school zone beacon data, and handle several related service requests.

**Comment by amenity** [comment] 2019-11-06 17:48
Per 11/6 meeting with AMD:
Jen points out that there are now many more kinds of beacons; updating the title

**Comment by amenity** [comment] 2019-11-06 17:49
@amenity @johnclary - this needs a project label

**Comment by amenity** [comment] 2020-01-13 18:07
Note that precise addresses should be recorded; nearest intersection is not sufficient.

**Comment by amenity** [comment] 2020-06-08 19:43
@johnclary @dianamartin - being as that [we already have basic school zone beacon tracking](https://data.mobility.austin.gov/data-tracker/#home/school-flashers/school-zone-beacons/) , would it be more accurate to call this "Enhanced Beacon Tracking"? This would include:
- [Associate beacons to work orders](https://github.com/cityofaustin/atd-data-tech/issues/1555) (thereby [tracking installation dates over time](https://github.com/cityofaustin/atd-data-tech/issues/1644))
- Expand tracking to additional types of beacons:
    - [Rectangular Rapid Flashing Beacons (RRFBs)](https://github.com/cityofaustin/atd-data-tech/issues/2933)
    - [Dynamic Speed Display Devices(DSDDs)](https://github.com/cityofaustin/atd-data-tech/issues/1540) - _maybe_; the need is different and I remain curious whether these are better tracked as "inventory" 
    - "[many more](https://github.com/cityofaustin/atd-data-tech/issues/493#issuecomment-550423778)"
- [Set up ETL](https://github.com/cityofaustin/atd-data-tech/issues/1606) to push (enhanced!) beacon tracking data to Socrata

**Comment by dianamartin** [comment] 2020-06-08 21:30
@amenity I would say it's just additional asset tracking IMO, @johnclary?

**Comment by johnclary** [comment] 2020-06-15 16:49
Sure. Some info about current state:

In Data Tracker we have school zones and school beacons. School zones are not a physical asset, but they encapsulate a group of beacons that flash on the same schedule. So, one school zone is related to many beacons. The [signal asset map](http://austin.maps.arcgis.com/apps/webappviewer/index.html?id=c9bda776b1934e439285570b29d3259c) depicts the locations of individual beacons (as yellow squares, iirc).

It is currently possible to associate a work order with a school zone—a user just picks that asset type when creating a work order.

Our understanding is that we do not need work orders for individual school beacons, because we were told that if a tech visits any school zone, they will test/repair every beacon in the zone. This is ideal, because there are very many beacons, and it would be very difficult for a user to select a specific beacon from a drop-down list, because they do not have useful addresses and are often clustered on the same block.


The issues with current state that I'm aware of are:
- Tech's may not be using the existing functionality to associate a work order with a school zone
- There is (probably) not anyone at AMD assigned to keeping the school zone and beacon data up to date. (e.g., updating schedules, adding new zones and/or beacons).
- For the above reason, the school zone and beacon data needs to be audited for accuracy (verify schedules are correct, verify all beacons and zones are present, verify beacon locations).

**Comment by dianamartin** [comment] 2020-06-15 16:58
The only people that might have any idea about the school zone data sets is Billy B, Ed G and/or Kenny M.

**Comment by amenity** [comment] 2020-06-16 01:13
Thanks, @johnclary. 

My takeaways:
- The data quality issues we're experiencing now will not be addressed (& might be exacerbated) by adding more fields, e.g. installation date*, to the School Zone Beacon object.  
- It does not make sense to expand the School Zone Beacon object to include other beacon types since the connection with school zones is fundamental for those beacons but irrelevant for others. 
- Accordingly, the following should be considered requests for new asset types: 
    - [Rectangular Rapid Flashing Beacons (RRFBs)](https://github.com/cityofaustin/atd-data-tech/issues/2933)
    - [Dynamic Speed Display Devices(DSDDs)](https://github.com/cityofaustin/atd-data-tech/issues/1540)

_*I see that [School Zone Beacons have `CREATED_DATE` and `MODIFIED_DATE`](https://data.mobility.austin.gov/data-tracker/#school-zone-beacons/view-school-zone-beacon-details/58e7fa74489456433ecda505/)... but those look like Knack audit fields rather than fields for tracking installation and maintenance, yes?_

**Comment by amenity** [comment] 2021-09-22 15:31
This is essentially a dupe of #1555.

**Closed by amenity** 2021-09-22 15:31 UTC
Labels: Workgroup: AMD, Type: Feature, Service: Product, Epic, Product: AMD Data Tracker, Project: Beacon Data Tracking
