### ISSUE TITLE
Prep Presentation for Mgmt Meeting on 10/7

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#527] opened 2019-08-26 16:04 UTC

**Comment by johnclary** [comment] 2019-08-29 03:19
Well, the 9/3 mgmt meeting was cancelled, which means we'll be on the agenda for the 10/7 meeting, and y'all will be fresh off your KnackCon presentation. Updated this issue to reflect the change.

**Comment by amenity** [comment] 2019-10-16 19:12
Duplicate of #667

**Closed by amenity** 2019-10-16 19:12 UTC
Labels: Service: Apps, Service: PM, Workgroup: SMB
