### ISSUE TITLE
Release Moped v2.5

### ISSUE THREAD

**Issue by chiaberry** [cityofaustin/atd-data-tech#15543] opened 2024-02-01 21:54 UTC
- [ ] schedule release party - @johnclary
- [ ] advise users of downtime
- [ ] merge open PRs - @chiaberry
- [ ] propose + vote on release names - @chiaberry  
- [ ] cut release branch - @chiaberry 
- [ ] do testing - @johnclary
- [ ] polish [release notes](https://github.com/cityofaustin/atd-moped/releases/tag/v2.5.0) - @chiaberry
- [ ] let users know maintenance is starting
- [ ] snap database in RDS  - @frankhereford 
- [ ] graphql-engine version bumps ([releases & tags](https://github.com/hasura/graphql-engine/releases)) @frankhereford
  - [ ] Update local dev docker compose to latest Hasura `2.x` release (previously 2.37.0)
  - [ ] update staging task definition to latest Hasura `2.x` release (to 2.37.0/37)
  - [ ] update production task definition to previous staging release version (previously 2.36.2 / 28)
  - [ ] Deploy task definition for staging
  - [ ] Deploy task definition for production~=
- [ ] Merge RC to prod
- [ ] bump Moped editor `package.json`  version to `v2.6.0`
- [ ] create issue for `v2.6.0` release @johnclary 
- [ ] send [release notes](https://github.com/cityofaustin/atd-moped/releases/tag/v2.5.0) to MUG (including reminder to refresh the page) - @johnclary

**Comment by johnclary** [comment] 2024-02-03 03:30
derp this is a dupe of https://github.com/cityofaustin/atd-data-tech/issues/15594 and i did make some minor changes to the template. thank you @chiaberry / closed

**Closed by johnclary** 2024-02-03 03:30 UTC
