### ISSUE TITLE
Configure Tablets with Airwatch and ArcGIS Collector

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#3417] opened 2020-07-16 14:27 UTC
- [x] Created new AirWatch Profile for TED group
- [x] Find out if individual or shared profiles
- [x] Turn in CTM ticket
- [x] Get new QR code
- [x] Create QR code PDF
- [ ] Coordinate configuration with Scott
- [ ] Distribute tablets

**Comment by johnclary** [comment] 2020-07-16 14:27
Scott is dropping these off at Cameron Rd today.

**Comment by dianamartin** [comment] 2020-07-16 17:21
- Scott will help configure tablets
- Need to find out if new TED profile I'm requesting will be individual named users or shared fleet profiles @johnclary if you know let me know, otherwise I can't put in a CTM Request.

Required Apps to load: 
- ArcGIS Collector

**Comment by dianamartin** [comment] 2020-07-17 17:04
John says
>my inclination is to go with individual assignees
- I'll put in a request and talk to Danny too see what our options are

**Comment by dianamartin** [comment] 2020-07-20 21:24
- John confirmed that the TED group will need individual profiles
- [x] Submitted CTM ticket for it `CALL0040630`
- [x] Gave Danny C. a heads up
- [ ] Get new QR code
- [ ] Create QR code PDF
- [ ] Coordinate configuration with Scott

**Comment by dianamartin** [comment] 2020-07-21 14:53
Synced with Danny this morning 7/21, he just had a few things to clarify. He said he'll work on getting the profiles completed.

**Comment by dianamartin** [comment] 2020-07-25 04:21
Emailed Scott on 7/24
>Danny gave me the QR code for the TED group profiles. It’s also documented in our GitBook wiki: (not sure you have access to this one or not, it’s a private one for our team). If you need access, just ask Amenity.

I tried to test it using the tablet I had at home but I was having trouble configuring it because I think I wasn’t able to delete my old profiles. I was hoping to confirm that it works, but I haven’t been successful. I think with a brand new tablet you should have no problem. 

There was a change I noticed though when configuring lately. The part where the user enters their credentials in, it used to accept city of Austin emails. It does not allow you to use that anymore, the user should use their Windows Network username (Ex. DoeJ) instead.

Danny is out of the office until next Tuesday. I’ve filled Chrispin in on tablet configurations so if you have an issues he can help.

**Comment by amenity** [comment] 2020-08-19 18:59
@johnclary - @ChrispinP is waiting for a tablet to test this out.

**Comment by johnclary** [comment] 2020-08-19 19:17
@ChrispinP i had some luck testing on browserstack if you want to mess around with that. login deets are in 1Password.

**Comment by amenity** [comment] 2020-08-19 19:19
Thanks @johnclary!  Probably a good idea for Chrispin to have a tablet to test on regardless, right? E.g. for #1674 ...

**Comment by johnclary** [comment] 2020-08-19 19:27
agreed

**Comment by ChrispinP** [comment] 2020-08-28 19:06
@johnclary I forget, was there anything else actionable for this ticket? I have a tablet now to use for testing. Diana mentioned logging in and using the QR code for an AirWatch profile. Do these things still need to be tested?

Cheers

**Closed** 2020-09-09 16:21 UTC
Labels: Project: Citywide Speed Limit Conversion, Service: Apps, Type: IT Support, Workgroup: TED
