### ISSUE TITLE
[TCP Conflict/Shared Review Cycles] Retire Single Process Views and Functionality

### ISSUE THREAD

**Issue by KaroEngstrom** [cityofaustin/atd-data-tech#13371] opened 2023-08-14 21:07 UTC
## Launch Period Updates/Debugging 📆 8/14-9/15/23
- @TracyLinder  FYI 
- 8/18/23 Samson N. sent a note that all current assigned requests were not showing up in the Reviewer Dashboard
     - I checked the dashboard and made sure all requests (old single process and new cycle review) are now visible  
- 9/11/23 - Samson sent a note that submission assignment was being glitchy; we looked at it together and noticed the logged-in user getting overwritten for Submission Reviewer; corrected this on the backend and confirmed with Samson that it's working
- 9/12/23 - Samson called about review 620, which still shows up for Robert as the original lead reviewer even though it has been reassigned to Samson - solved on the backend by clearing out the conditional rule on a new **Currently Assigned To** field on the `tcp_cswz_request` object

### Retire the following views:
- [ ] Application | Add Attachments page - old form and table 
- [ ] Application | Finalize Request page - old table 
- [ ] Application | Edit Attachments page - old form and table 
- [x] Back Office - Landing Page | Old Single-Process Request Table (all will be completed and can be found through the Advanced Search

**Comment by KaroEngstrom** [comment] 2023-08-20 02:04
TEST
term
: definition

**Comment by TracyLinder** [comment] 2023-09-15 17:09
### Feedback 9/15/23

- Julia can't see submissions she's assigned to on the Reviewer Dashboard, but she can see them on the new Task Board. We should discuss moving forward with retiring the old dashboard. 🔍
- When a user edits the case status the system copies the status to the submission status, but when the user updates the submission status it doesn't update the case status. Karo explained this is by design at the moment and will be updated with external review features and users won't have to hard edit the case status. 
- Users would benefit from a process chart that helps them understand the workflow as they relate to case and submission statuses. 
- Julia recently was assigned to TCP Review in AMANDA that she wasn't aware of until the GP case manager informed her by email that she was late on the review. GP is the only review type that still allows in-process TCP Review. 
- State legislation has done away with completeness check processes in land development permitting and review. More to be discuss as to how this will affect KNACK/AMANDA related features and workflows. 
- Darren is investigating as to if ROW will still be allowed to require review payment before they begin review. 
- [ ] Schedule time to discuss only the status/workflow updates needed. Samson **must** be in the room for this conversation. 


- [ ] AMANDA update needed: make sure the ROW/ATD Traffic Control process that inserts on the GP folder is assigned to the TCP review group. Remind Darren that TCP intake will have to check the AMANDA task list for the TCP Reviewers user group, and create a new KNACK Case for the few reviews a month that are assigned via AMANDA.

**Closed** 2024-03-21 20:43 UTC
Labels: Workgroup: ROW, Service: Apps, Type: Enhancement, Product: ROW Portal
