### ISSUE TITLE
Add Cancel new item request button

### ISSUE THREAD

**Issue by JaceDeloney** [cityofaustin/atd-data-tech#1234] opened 2020-01-21 20:32 UTC
Add a Cancel new item request button

User Flow: 

1. User taps Cancel button
2. User confirms cancelation by clicking yes
3. System submits a form to knack to cancel request

This button should be styled like the edit button. It should also be placed side-by-side to the edit button

**Comment by mddilley** [comment] 2020-01-27 20:40
Duplicate of https://github.com/cityofaustin/atd-data-tech/issues/1216. Closing.

**Closed by mddilley** 2020-01-27 20:40 UTC
Labels: Duplicate, Need: 2-Should Have, Project: Mobile Signal Work Order, Service: Dev, Type: Enhancement, Workgroup: AMD
