### ISSUE TITLE
Migrate TCP Business Days Script to New App

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#2298] opened 2020-04-08 20:55 UTC
1. Create API Views
2. Update Knack script config

**Comment by dianamartin** [comment] 2020-04-09 14:18
- [x] Created api view page and added `TCP tracking submissions` table

**Comment by amenity** [comment] 2020-06-17 15:47
@johnclary @dianamartin - Sprint 27?

**Comment by johnclary** [comment] 2020-07-05 20:02
Sprint 29 :). Marking as blocked by [Knackpy v1.0](https://github.com/cityofaustin/atd-data-tech/issues/3241)

**Comment by amenity** [comment] 2020-08-26 15:51
Duplicate of #2317

**Closed by amenity** 2020-08-26 15:51 UTC
Labels: Need: 1-Must Have, Product: ROW Portal, Service: Apps, Service: Dev, Type: Data, Workgroup: ROW
