### ISSUE TITLE
Add "Submit for Review" button Work Order Supervisor Buttons View on Sign Work Order Details Page

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#12278] opened 2023-05-12 16:21 UTC
Kenny has Supervisor roles as an inspector and needs the ability to "Submit for Review" and "Close" work orders. `Submit for Review` currently isn't a button available to the Supervisor role in the Signs & Markings App, but needs to be.

**Comment by ChristinaTremel** [comment] 2023-05-17 15:34
@dianamartin please put build notes here for Susanne to use!

**Comment by dianamartin** [comment] 2023-05-17 21:25
# Build Notes
## On the Signs Work Order Details [page](https://builder.knack.com/atd/signs-markings/pages/scene_1028)
- The supervisor menu does not have the "Submit for Review" button on it, we can copy the form (we tried that already). We are going to use the "Assigner/Specialist"
![image](https://github.com/cityofaustin/atd-data-tech/assets/21112975/58bda23e-7590-40ef-80f9-5a56507872fe)
- On Supervisor menu, click "link to new page" - rename to "Submit for Review"
- use same icon as other (simple check mark)
- On new page, rebuild these tables and form, see reference below
![image](https://github.com/cityofaustin/atd-data-tech/assets/21112975/62424a1c-8f8e-4294-aec5-b6e8cf7e620c)
- Locations - `work_order_signs_location`
- Time - `work_orders_signs_markings_time_log`
- Materials - `inventory_transaction`
- Submit for Review - 311 CSR | FORM, see below for configurations
![image](https://github.com/cityofaustin/atd-data-tech/assets/21112975/897df3ff-ccf0-44f6-a95f-a905c81188f2)
![image](https://github.com/cityofaustin/atd-data-tech/assets/21112975/957e5dac-438a-46a6-907e-9ce861a7110e)
## Page Rules on "Submit for Review"
- [ ] Configure 12 rules
Rule 1-3
![image](https://github.com/cityofaustin/atd-data-tech/assets/21112975/256f8a30-ca77-401e-95d2-c3afe3e63a7c)
Rule 4-6
![image](https://github.com/cityofaustin/atd-data-tech/assets/21112975/a7153bf8-b72c-41e9-ac60-e6d3b983da6b)
Rule 7-10
![image](https://github.com/cityofaustin/atd-data-tech/assets/21112975/5f66cb83-c931-41a0-97f4-812656e555a6)



## Form Rules
### Submit Rule
- [ ] Redirect to parent
### Display Rules
- [ ] Configure 3 rules
![image](https://github.com/cityofaustin/atd-data-tech/assets/21112975/6287a6a7-9fb3-46d9-9840-eed0da7feaf8)
### Record Rules
- [ ] Configure 3 rules
![image](https://github.com/cityofaustin/atd-data-tech/assets/21112975/210b8a6e-4de2-4f6a-a025-b1c386dd55dc)

**Comment by dianamartin** [comment] 2023-05-25 21:47
# 5/25
- [x] Created new menu page on "Work Order | BUTTONS - Supervisor"
- [x] Created new page `Submit for Review | Supervisor`
- [x] Copied `Locations, Materials, Time` tables to new page `Submit for Review | Supervisor`

**Comment by dianamartin** [comment] 2023-05-25 22:02
@ChristinaTremel this is ready to be tested/stakeholder review

**Comment by dianamartin** [comment] 2023-06-08 20:07
# 6/8
- Emailed Kenny S. (SMD)
>Hi Kenny, 
I’m following up to see if you knew that we had updated the Signs Work Order details to have the “Submit for Review” button added on the supervisor menu. I wanted to check to see if that was working as intended so that I can close this issue we have open for the task.

**Closed** 2023-06-09 16:06 UTC
Labels: Workgroup: SMD, Type: IT Support, Service: Apps, Product: Signs & Markings
