### ISSUE TITLE
Pre-Migration Follow-up Tasks

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#6191] opened 2021-05-25 14:41 UTC
- compare Data Tracker functionality to [new prototype](https://builder.knack.com/atd/right-of-way-portal-johns-migration-copy). See my notes [here](https://github.com/cityofaustin/atd-data-tech/issues/1554#issuecomment-820760164)
- decide: should we re-name all of the fields to be human-friendly now (to make user testing easier) or wait until after the migration (to make data import easier)?
- test out the data import from Data Tracker to make sure that process can be done quickly/smoothly

**Comment by TracyLinder** [comment] 2021-05-25 17:32
@johnclary @ChrispinP - What's the status on this issue? 
PS I'm scheduling UAT w/ a power user. Should be this week or next.

**Comment by johnclary** [comment] 2021-05-25 17:33
@TracyLinder i just created it this morning and it's on Chrispin's todo list for today.

**Comment by TracyLinder** [comment] 2021-05-25 17:40
@johnclary OMG I'm sorry i din't look at the date.

**Comment by ChrispinP** [comment] 2021-05-25 23:01
tcp_project Checklist:
Setup
- [ ] Create/Use CreatedByEmail & ModifiedByEmail fields to map Created By and Modified By fields 
- [ ] Separate Submitter Name(text field) into Submitter First and Submitter Last name fields so they can be imported into Submitter Name(name field) correctly
- [ ] Default TCP Submitted to either Yes or Blank
After Import
- [ ] Update TCP Statuses to non-capitalized values
- [ ] Set value in Assigned To old to TCP Reviewers

tcp_submission Checklist:
Setup
- [ ] Create/Use SubmissionReviewerEmail field to map Submission Reviewers(connection) field. Import Submission Reviewer into Submission Reviewer old if necessary
- [ ] Set tcp_tracking connection field to TCP ID or txtTCPProjectDisplay
- [ ] Default Submission Submitted to either Yes or Blank
After Import
- [ ] Update Submission Statuses to non-capitalized values
- [ ] Set value in Submission Reviewer old to Submission Reviewers if necessary

**Comment by ChrispinP** [comment] 2021-06-01 16:00
Testing is now complete. Only present issue is a data integrity issue with Submitter Name. After being delineated in Excel we also need to make sure the Last Name has a value before import otherwise older records will need to be manually updated in Knack. Knack shoves the Last Name into the Middle Name after delineation by default. If we wanted to clean up the data further, we would remove the Middle Name after making sure the Last Name is in place.

A bit of prep is necessary such as matching object display fields, creating the email fields for connection fields, and adding missing fields like Submitter Name.

With the amount of records, prep, import process, and after care, @johnclary we may need the weekend for this if we dont want to disrupt their workflow.

**Comment by ChrispinP** [comment] 2021-06-10 19:48
Boolean and Sum fields are now setup for status automation. Temporary conditionals setup to automate TCP Status. Will meet with Laura to make sure these are working as intended.
![image](https://user-images.githubusercontent.com/67915167/121587662-ac05cb80-c9fa-11eb-9c68-5e0a8188572c.png)
![image](https://user-images.githubusercontent.com/67915167/121587722-ba53e780-c9fa-11eb-97df-33cf14d98377.png)



Added reporting equations to pull year, month, quarter for Created Date.
![image](https://user-images.githubusercontent.com/67915167/121587593-9bedec00-c9fa-11eb-9559-a277f7310162.png)


Used the new Auto Increment to calculate and generate a TCP ID if the field is blank and padded the number by 100k for new IDs.
![image](https://user-images.githubusercontent.com/67915167/121587524-87a9ef00-c9fa-11eb-97cf-156450a1446d.png)

**Comment by ChrispinP** [comment] 2021-06-11 22:41
Updated the pre-migration process with Excel. Fields are now present in Data Tracker Prod so we can capture Submission ID, Names, & Emails.

**Comment by ChrispinP** [comment] 2021-06-16 20:15
2018 to 2020 tcp_project records are now imported and updated

Account records updated with historical TCP Reviewers

**Comment by ChrispinP** [comment] 2021-06-17 21:04
2018 to 2020 tcp_submission records are now imported but still indexing for almost 24 hours now.

**Comment by johnclary** [comment] 2021-06-21 15:03
thanks @ChrispinP!! nice work. how's that indexing going? when it's done, would you cross check ~10 imported records against the records in the Data Tracker to make sure automated statuses match?

**Comment by ChrispinP** [comment] 2021-06-21 15:48
Indexing finished sometime over the weekend, tcp_submission records are now being updated with Submission Cycle and Missing Dates.

**Comment by ChrispinP** [comment] 2021-06-21 22:54
2018 to 2020 tcp_submission records are now imported and updated

**Comment by TracyLinder** [comment] 2021-06-30 20:26
I probably should have added this here instead of creating a new issue:
TCP Migration Messaging #6570

**Comment by TracyLinder** [comment] 2021-06-30 20:27
@ChrispinP add to your to-do list to remove the login for the TCP tracker on AMD after the migration is complete.

**Comment by ChrispinP** [comment] 2021-07-05 16:49
Migration is complete, object display fields updated. Total # of Deficiencies and Days Under Review added

**Comment by ChrispinP** [comment] 2021-07-06 22:47
Will put remaining followup/cleanup in a new issue.

**Comment by ChrispinP** [comment] 2021-07-07 15:53
Issue #6621 created for cleanup, closing

**Closed by ChrispinP** 2021-07-07 15:53 UTC
Labels: Product: ROW Portal, Service: Apps, Type: Testing
