### ISSUE TITLE
V7 SIF BUG: Online Payments are not reflecting on the SIF folder (Ready for UAT on PROD)

### ISSUE THREAD

**Issue by Nadin-Nader** [cityofaustin/atd-data-tech#10233] opened 2022-09-12 22:11 UTC
### SIF Payments are not updating BO
**INC0226502**

Dan and Nathan have reported that the Payments from the portal are not reflecting in BO. The applicant (Sandra) has paid the Street impact fees for 4 buildings on Dulce Lane.  Buildings 18, 21, 22, 23, and 24. Unit 21 did not create a PR Folder when paid. 
None of these payments show up in AMANDA BO

Examples:
  - PR 2022 121756 000 00 Street Impact Fee Notification 2707 Dulce Ln #18
  - SIF 2022 126149 000 00 Street Impact Fee
  - 2022-101348 SIF 
     - Inv# 7663329, 7669502, 7668175/PDRD $3,621.00 
    

![image.png](https://images.zenhubusercontent.com/5e8dfbfabf171441c3a5684e/2fab3d81-d226-4667-8832-8be651fe4a73)

**Comment by Sreelatha-BlazeKannan** [comment] 2022-09-14 21:02
@Nadin-Nader , @TracyLinder - Analysis is in Progress

**Comment by TracyLinder** [comment] 2022-09-20 18:45
### Chat w/ Nathan A. 9/20/22

**Examples:**
1. 22-111331 - Paid 8/24 (7 fees paid w/ one payment) - (We have the confirmation email; Nate will fwd to me)
2. 22-101348 - Paid 9/13 (8 fees paid) & we have confirmation email

**Comment by TracyLinder** [comment] 2022-10-03 16:43
Tracy will:
- [ ] Contact. ctm/city base
- [ ] Add columns to our data: Folder name, GL Code, SIF District & new data set for all invoices & payment status.

**Comment by TracyLinder** [comment] 2022-10-03 16:50
![Screen Shot 2022-10-03 at 11.25.06 AM.png](https://images.zenhubusercontent.com/5cca1e522b8dfc0ee14dedf5/e15c1d98-6d0a-433e-9205-9848d6e009d9)

**Comment by Sreelatha-BlazeKannan** [comment] 2022-10-03 17:43
@Nadin-Nader , @TracyLinder - Please find attached data in excel. 

[SIF Payment PROD Data.xlsx](https://github.com/cityofaustin/atd-data-tech/files/9699689/SIF.Payment.PROD.Data.xlsx)

**Comment by Sreelatha-BlazeKannan** [comment] 2022-10-03 19:40
@Nadin-Nader , @TracyLinder - Added district data

**Query -** 

SELECT f.folderrsn, f.foldername,f.foldertype, fi.infovalue, vaf.glaccountnumber,ab.billnumber,ab.PAIDINFULLFLAG, ab.billamount,ab.totalpaid
FROM Folder f JOIN accountbill ab ON f.folderrsn = ab.folderrsn
JOIN accountbillfee abf ON f.folderrsn = abf.folderrsn AND abf.billnumber = ab.billnumber
JOIN folderinfo fi ON f.folderrsn = fi.folderrsn
JOIN validaccountfee vaf ON vaf.feecode = abf.feecode
AND fi.infocode = 84012
WHERE f.foldertype = 'SIF'
ORDER BY foldertype

[SIF PROD Data with District.xlsx](https://github.com/cityofaustin/atd-data-tech/files/9700415/SIF.PROD.Data.with.District.xlsx)

**Comment by TracyLinder** [comment] 2022-10-04 18:38
### Test Notes
- I am able to make a SIF payment with check in PROD (13004854) but not test (12870463).

**Comment by TracyLinder** [comment] 2022-10-06 21:31
### Sree's Analysis:

In Payment_SIF Procedure I found a change which recently moved to PROD on 09/09/2022 by Priya to add Valid_Payment_Method check; However the Procedure has been updated to add the check by Priya as per CTM/Swapna team.

Adding the check may not be an issue; however the calling function COA_FEES Package function f_Valid_Payment_Method is different in DEV/Localhost & TEST. i.e., DEV/ Local host are same but not the TEST and this is the reason for us to get “INVALID PAYMENT METHOD TYPE FOR THIS FOLDERTYPE” ERROR in TEST for SIF folder, but not in other environments.

So Now – I would like to know from CTM team which is the Correct/ right Package function to be used to resolve this issue. And if they say that TEST Procedure then we may need to add the Valid payment method types ex: Check/Cash/ACHO etc., for SIF Folder in Lookup table and this need to be tested.
 

**According to above analysis I suggest**

1. To identify the right Package function – by CTM Team
2. Update the right function into all environments so that the behavior can be tested in Localhost and DEV itself. – CTM Team
3. Identify the list valid payment methods for SIF for me to update the list - Tracy
4. Update lookup and test and Commit. - Sree

**Comment by TracyLinder** [comment] 2022-10-06 21:32
**Next Step**: Meeting with Jenice & Swapna tomorrow at 11am.

**Comment by Sreelatha-BlazeKannan** [comment] 2022-10-10 15:37
@Nadin-Nader , @TracyLinder - As per our meeting, George confirmed that all environments code is in sync now. However when I tested it is still same. Now we need Valid Payment method types for SIF to update lookup tables and test.

**Comment by Sreelatha-BlazeKannan** [comment] 2022-10-10 19:37
@Nadin-Nader , @TracyLinder - Submitted DEV/TEST DP; Please approve and create task id for the same.

Commit ID: [87f67948354e](http://coaamandadevops02.austintexas.gov/R5:87f67948354e987a70836d6e8f3354f93c44c4ac)

**Comment by Sreelatha-BlazeKannan** [comment] 2022-10-10 21:26
@Nadin-Nader , @TracyLinder - Updated payment methods in DEV & TEST; Now i am able to make payments from backoffice Amanda side without any errors. However Online payments are not reflecting yet. I will continue my analysis further.

**Comment by Sreelatha-BlazeKannan** [comment] 2022-10-11 17:46
@Nadin-Nader , @TracyLinder - Updated with District n Payment Date

[SIF PROD Data with District n Date.xlsx](https://github.com/cityofaustin/atd-data-tech/files/9758550/SIF.PROD.Data.with.District.n.Date.xlsx)

**Comment by Nadin-Nader** [comment] 2022-10-12 14:18
This has been set to the DevOps CM Team to be deployed to **DEV** under **_SCTASK0255486_**

**Comment by Sreelatha-BlazeKannan** [comment] 2022-10-12 14:22
@Nadin-Nader , @TracyLinder - The above commit deployed to both DEV & TEST environments; Now I am able to make payments from TEST which is good. However the primary issue with Online payments still same; Asked Swapna to Refresh/clear cache portal Test server it was done yesterday evening; tested after that and still no luck. And continuing further analysis on this.

**Comment by Sreelatha-BlazeKannan** [comment] 2022-10-14 18:18
@Nadin-Nader , @TracyLinder - 

I further continued my analysis as Online payments are still an issue; I have done Payment_SIF procedure debugging in TESTwith Martin’s help yesterday, understood that my debugging procedure never triggered when I submitted online payment. So today with the help of Swapna, got both AMANDA and Portal Log files to verify the error and found that it looks like Portal side issue.

AMANDA Log and Portal Log’s are attached. 

AMANDA Log Error – 
SELECT Folder.FolderRSN, Folder.FolderCentury, Folder.FolderYear, Folder.FolderSequence, Folder.FolderSection, Folder.FolderRevision, Folder.FolderType, Folder.StatusCode, Folder.PropertyRSN, Folder.PropertyLocation, Folder.Indate, Folder.IssueDate, Folder.ExpiryDate, Folder.ReferenceFile, Folder.IssueUser, Folder.FinalDate, Folder.SubCode, Folder.WorkCode, Folder.FolderDescription, Folder.ParentRSN, Folder.CopyFlag, Folder.DateFolderPrinted, Folder.StatCanValuation, Folder.StatCanUnitChanged, Folder.StatCanUnits, Folder.StatCanArea, Folder.FolderPropertyUnit, Folder.Priority, Folder.FolderName, Folder.OldFolderRSN, Folder.IssuedFlag, Folder.NewFolderRSN, Folder.ReferenceFile2, Folder.ReferenceFile3, Folder.ReferenceFile4, Folder.ReferenceFile5, Folder.ReferenceFile6, Folder.ReferenceFile7, Folder.VehicleRSN, Folder.OperationName, Folder.LRPropertyRSN, Folder.RenewalPrintDate, Folder.ProjectLeadUserID, Folder.FolderCondition, Folder.AgencyType, f_FolderNumber(Folder.FolderRSN) FolderNumber FROM Folder WHERE  (Folder.SecurityCode IS NULL OR Folder.SecurityCode IN ( 0 )) and FolderRSN = ? ORDER BY FolderRSN
WARNING: The current state of the parser is not equal to the state just received from the parser. The current state in the paser is END_ELEMENT the state just received is END_DOCUMENT


Portal Log Error – 

eference:Object=[org.apache.commons.httpclient.methods.PostMethod@4ea19f9c])
2022-10-14 09:36:45,476 - DEBUG http-apr-443-exec-16 CityBasePayment.Logger - Call addWebPaymentLog
2022-10-14 09:36:45,478 - INFO http-apr-443-exec-16 com.alphinat.sgs.smartlet.template.actions.CmdCalculatePage - Execute command calculate-page.
2022-10-14 09:36:45,479 - ERROR http-apr-443-exec-16 com.alphinat.sgs.smartlet.util.script.APNBSHScripter - Beanshell exception: Sourced file: inline evaluation of: `` String frsn = field("NewFolderRSN").value;  return "<a href='new-application?t_ . . . '' : Method Invocation getOutput
In the context of field "permitNumberLinkNoFees" on page "00-paymentDetails".

2022-10-14 09:39:06,962 - INFO http-apr-443-exec-3 com.alphinat.sgs.smartlet.template.actions.CmdCalculatePage - Execute command calculate-page.
2022-10-14 09:39:06,987 - INFO http-apr-443-exec-3 com.alphinat.sgs.smartlet.SmartletResourceAccessHelper - resolveInterviewTimestamp C:/Program Files/CSDC/WebServer/smartlets-data/address/timestamp.txt
2022-10-14 09:39:06,993 - ERROR http-apr-443-exec-3 com.alphinat.sgs.smartlet.SmartletResourceAccessHelper - Warning:cannot access timestamp of smartlet address from C:/Program Files/CSDC/WebServer/smartlets-data/address/timestamp.txt
2022-10-14 09:39:06,993 - INFO http-apr-443-exec-3 com.alphinat.sgs.smartlet.SmartletResourceAccessHelper - Resolve smartlet  C:/Program Files/CSDC/WebServer/smartlets-data/address/runtime.xml
2022-10-14 09:39:07,000 - ERROR http-apr-443-exec-3 com.alphinat.sgs.smartlet.SmartletResourceAccessHelper - Error resolve runtime xml : C:/Program Files/CSDC/WebServer/smartlets-data/address/runtime.xml
2022-10-14 09:39:07,000 - ERROR http-apr-443-exec-3 com.alphinat.sgs.smartlet.GlobalContainer - null Nested exception: null
org.dom4j.DocumentException: null Nested exception: null
Caused by: java.lang.NullPointerException
2022-10-14 09:39:07,003 - ERROR http-apr-443-exec-3 com.alphinat.sgs.smartportlet.SmartPortlet - Cannot load smartlet address
java.lang.Exception: Cannot load smartlet address


I may be wrong but Other than contacting the portal team I am not seeing any other option to resolve from Back office.

**Comment by TracyLinder** [comment] 2022-10-18 16:33
### CTM-AMANDA must fix this; we cannot. We are meeting with them tomorrow 10/19 with CTM to discuss.

**Comment by Sreelatha-BlazeKannan** [comment] 2022-10-20 19:30
@Nadin-Nader , @TracyLinder - Had a meeting with Swapna, George and CTM Team to debug the issue; recreated and verified the log files and CTM team understood that the issue is related to INTERNET User access and trying to work on the fix. Once it is done, I will also do testing and update the card.

**Comment by Sreelatha-BlazeKannan** [comment] 2022-10-20 21:10
@Nadin-Nader , @TracyLinder - Good News!!! 
Issue in detail - 
The code referred to a table that was used in V6, but no longer used in V7. So we couldn't update through the AMANDA interface, and we had to update via database script. So button permissions are updated in AMANDA V7 by George

And VALIDFOLDER updated with OverPaymentGlAccountRec Number to "1233343434" like RW and other Foldertypes. Submitted the commit for DEV/TEST. Commit ID: [f13819189a6f](http://coaamandadevops02.austintexas.gov/R5:f13819189a6f355334144ed00fe0d1711284c061)

Upon testing it has to be committed to PROD.
Commit Order 1:  87f67948354e
Commit Order 2: [f13819189a6f](http://coaamandadevops02.austintexas.gov/R5:f13819189a6f355334144ed00fe0d1711284c061)

**Comment by Nadin-Nader** [comment] 2022-10-25 15:29
Reopened and updated the comment

**Comment by Nadin-Nader** [comment] 2022-11-02 18:40
Waiting for results of UAT on TEST

**Comment by TracyLinder** [comment] 2022-11-02 19:54
### UAT PASSED
- ROWID 12875704

**Comment by Nadin-Nader** [comment] 2022-11-09 15:29
@Sreelatha-BlazeKannan  @TracyLinder  this has been deployed to PROD

**Comment by TracyLinder** [comment] 2022-11-09 18:04
### Stakeholders Notified & Closing

Howdy, the fix for this is in PROD. If you see any payment failures from this date forward it is a bug that should be reported. We should assume that any online payments made before today failed. I apologize for the huge inconvenience. 

Best,

Tracy Linder, Product Manager

**Closed by TracyLinder** 2022-11-09 18:04 UTC
Labels: Workgroup: Finance, Type: Bug Report, Impact: 1-Severe, Need: 1-Must Have, Workgroup: TDS, Product: AMANDA, Provider: LaunchIT, Project: AMANDA V7 Upgrade, Project: Street Impact Fee Implimentation
