### ISSUE TITLE
TIA MOD BUG: Attachments Table on Case Log Not Populating

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#5339] opened 2021-02-26 22:00 UTC
### Example [here](https://atd.knack.com/development-services#view-tia-requests/tia-request-details/6036d2a21d2d28001bf15898/tia-case-log/6036d2a21d2d28001bf15898/)

**Comment by ChrispinP** [comment] 2021-03-02 23:54
I believe this may have been a result of a specific case issue or setting or no new attachments yet being added to the case outside of the application process. Case logs are appropriately showing up as intended.

No issue, closing

**Closed by ChrispinP** 2021-03-02 23:54 UTC
Labels: Impact: 2-Major, Product: TDS Portal, Project: TIA Module, Service: Apps, Type: Bug Report, Workgroup: TDSD
