### ISSUE TITLE
[Bug] Custom New Submission & Pay Fees Buttons on TIA Module Not Activating

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#3688] opened 2020-08-13 19:46 UTC
### Clicking on the 'New Submission' button isn't doing anything. 
- Example link [here](https://atd.knack.com/development-services#review-status/view-details/5f31b0eff10652001618909b)

**Comment by TracyLinder** [comment] 2020-08-14 04:35
I'm testing a different case, and the page is working as expected, but the green button isn't there. 

![image](https://user-images.githubusercontent.com/49930868/90214294-a0874b00-ddbd-11ea-95d9-cefa10d89436.png)

**Comment by TracyLinder** [comment] 2020-08-14 04:37
You know that might be because I was logged in and had backend permissions.

**Comment by ChrispinP** [comment] 2020-08-14 22:45
Confirmed these two custom buttons are not working. Will need to fix custom css/js or revert back to a default functional knack button.

**Comment by TracyLinder** [comment] 2020-08-28 20:36
Per Chrispin, we need Dev resources to look at this.

@ChrispinP can you talk to @johnclary about who might be able to help please?

**Comment by ChrispinP** [comment] 2020-09-02 20:13
Custom Submission and Pay Fees buttons should now be activating. Adding submission should refresh the page now to show updated submissions. Table display updated as well as submission date.

@TracyLinder Please review these 2 buttons to confirm fix

**Comment by ChrispinP** [comment] 2020-11-09 18:54
Tested Submission button, should be working as intended. Updated some of its rules.

Submission button will not appear unless Fees are set to Paid for the TIA Request.

Ready for Review

**Comment by ChrispinP** [comment] 2020-11-25 18:42
no further issues, closing.

**Closed** 2020-11-25 18:42 UTC
Labels: Impact: 2-Major, Product: TIA Module, Service: Apps, Type: Bug Report
