### ISSUE TITLE
"Milestone" edit modal on Dashboard

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-data-tech#9278] opened 2022-05-25 18:27 UTC
![Dashboard - Modal - Milestones](https://user-images.githubusercontent.com/1463708/160212034-2664c481-efd8-49ea-9c96-ae41c215a6ea.png)

**Comment by chiaberry** [comment] 2022-09-01 19:30
duplicate of https://github.com/cityofaustin/atd-data-tech/issues/9667

**Closed by chiaberry** 2022-09-01 19:30 UTC
Labels: Service: Dev, Need: 2-Should Have, Product: Moped
