### ISSUE TITLE
[Update Data] Open Data Portal in Open Data Inventory

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#8957] opened 2022-04-19 17:22 UTC
- Reference the OpenData spreadsheet that Karo compiled in "OpenData" folder in Google Drive
- Update Open Data Inventory 
- Check/Update: Owner, Data refresh and status

**Comment by dianamartin** [comment] 2022-04-22 14:47
Karo and I synced to remember which spreadsheet we used to QC the datasets and we mapped out the relationships in [Miro ](https://miro.com/app/board/uXjVO6vKjok=/)to confirm where the datasets lived and what we needed to update. 

# Steps
- Update existing dataset records in Opendata Inventory 
  - [ ] Confirm data owner?
  - [ ] Descriptions
  - [ ] Hosted
- Added new dataset records

**Comment by KaroEngstrom** [comment] 2022-07-08 13:34
F 7/8/22 
I'd like to pick this up in mid-August as July is booked

**Comment by KaroEngstrom** [comment] 2022-12-28 15:16
Duplicate of #10750 
Closing this one.

**Closed by KaroEngstrom** 2022-12-28 15:16 UTC
Labels: Workgroup: DTS, Type: Data, Service: Apps, Workgroup: ATD, Type: Open Data
