### ISSUE TITLE
Grant O365 E5/G5 Licenses for All ATD Staff

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#2109] opened 2020-03-16 15:33 UTC
Staff need an E5 license in order to create Teams meetings. Let's ask CTM to add this license for all staff

**Comment by dianamartin** [comment] 2020-03-16 18:02
I got the contact from Scott: Anastasiya T. 4-2463. I tried calling her,  but it looks like she's out. I'm going to put in CTM ticket about it.

**Comment by dianamartin** [comment] 2020-03-16 18:05
This is what I said on the ticket: 
![image](https://user-images.githubusercontent.com/21112975/76787317-c7960e00-6786-11ea-8ecd-e81187dca1c5.png)

**Comment by dianamartin** [comment] 2020-03-17 13:32
@johnclary I finally tracked her down and I'm chatting with her now. She said licenses are $56.56/mo per license. A bit more than a data plan per device or a mifi device. She's sending me report of how many user already have licenses, then I'll have to estimate out how many we need.

**Comment by dianamartin** [comment] 2020-03-17 13:37
I asked
>is E5/G5 the same thing? i assume they stand for Enterprise/Government..

Anastasiya said
>yes, it's the same thing. E5 - enterprise license 5, G5 - government license 5...

**Comment by dianamartin** [comment] 2020-03-17 14:18
@johnclary I got a report of the users that already have E5/G5 licenses. I had to tag them all with the correct divisions so that managers can look at it. 

We have 228 license for ATD, we have a handful of people that left ATD and we can choose to downgrade folks to the E3/G3 license that don't give them the remote meeting options. We should have folks review for their group. 

Be aware that this spreadsheet is just filtered by "24E" and if someone accidentally messes up the filter it can get out of hand. Sorted by Division and Sorted by Display Name. 

Spreadsheet is [here](https://cityofaustin.sharepoint.com/:x:/r/sites/ATD/DTS/_layouts/15/Doc.aspx?sourcedoc=%7Bfcab5c3f-caea-44d5-8bd4-ad4dd6da0c79%7D&action=edit&wdPreviousSession=2b22dd9c-d7dc-4f49-a4f1-55d7874c165d)

**Comment by johnclary** [comment] 2020-03-18 00:15
@dianamartin thank you! I filtered out other departments and added a data validation on the status column. Managers have been instructed to review it.

I'm passing this off to @moorerst since you're out of office.

**Comment by moorerst** [comment] 2020-03-18 15:27
Verified with Anastasiya  that a resource account can be assigned a G5 license if that account is used to schedule Skype/Teams meetings ex. activetransportation@austintexas.gov

**Comment by moorerst** [comment] 2020-03-19 15:26
Opened request # CALL0026020 to update ATD G5 licenses based on spreadsheet tabs Need G5 and Revoke G5. Spoke with Anastasiya directly she will review spreadsheet.

**Comment by moorerst** [comment] 2020-03-19 17:07
Updates have been completed. Will take a few hours for changes to update. Anastasiya will send an updated ATD G5 report on 3/20.  Once we get the new confirmation list from Anastasia,  change "Requested on 3/19" status on the master list to a status of "No Action Needed (Keep E5 License)"?

**Comment by dianamartin** [comment] 2020-03-19 19:30
@moorerst You can request Anastasiya to close my Open Task: `SCTASK0054376` request if you created a new one...for ATD.

**Comment by moorerst** [comment] 2020-03-20 18:51
Anastasiya closed the Open Task. She also provided an updated report, I verified the accounts had been updated. The ATD G5 license spreadsheet was also updated with status "No Action Needed (Keep E5 License"

**Comment by moorerst** [comment] 2020-03-23 16:46
Received clean updated ATD E5 report from CTM, posted updated report on Sharepoint.
Emailed several essential staff to verify they can see Teams

**Comment by moorerst** [comment] 2020-03-23 17:30
Users confirmed they could see Teams. Closing issue.

**Closed by moorerst** 2020-03-23 17:30 UTC
Labels: Need: 1-Must Have, Service: Apps, Type: IT Support, Workgroup: ATD
