### ISSUE TITLE
BUG: TURP Extension Features Not Working (PROD UAT Passed)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#7785] opened 2021-11-18 20:19 UTC
### Clarification
**If the TURP work types are (Private Development, Project Connect, Other City Department)**

1. User saves Extension Granted
2. System updates folder infos extension start date and extension end date
3. System inserts extension fees
4. User bills extension fees
5. Invoice is paid (either BO or Portal)
6. System updates folder status to Active, and updates folder expiration date  to _extension end date_

**If the TURP work types are Franchise, ATD, Austin Energy, Austin Water, Corridor Program Office, Public Works, Watershed Protection:**

1. User saves Extension Granted
2. System updates folder infos extension start date and extension end date
3. System updates folder status to Active and folder expiration date to info _extension end date_

----

**From Izzy**

_regarding an extension for #2021-160444 RW. The dates on the permit are not updating after the extension process has been completed in AMANDA. The status of the permit is not updating when we send the copy of the permit to the applicant. I experimented with the activate upon payment field on the info tab, but it had no effect. The status in AMANDA is essential for PLAs when running a conflict check. Also, if an inspector looks in AMANDA, then they could potentially issue a violation to the contractor for working without an active permit._

----
![image](https://user-images.githubusercontent.com/49930868/142490463-3cf8f9ae-f21d-41d3-aa17-a504134cfd54.png)

![image](https://user-images.githubusercontent.com/49930868/142490543-1c2d1770-00dd-45ce-8729-b38b31d55a3d.png)

![image](https://user-images.githubusercontent.com/49930868/142490563-a911aace-6f00-43cd-94c0-2fad73a75310.png)

![image](https://user-images.githubusercontent.com/49930868/142490586-9085a346-9fdf-41c1-a2fb-be6b8375fd42.png)

**Comment by TracyLinder** [comment] 2021-11-18 20:21
_From Nate_

Shroff, Subhashini - Vendor i spoke to Danil and he said the following:


[12:13 PM] Kontsevoy, Daniil


Hello,
If you are relating to permit 2021 160444 000 00 RW, - yes, when the extension process is complete - the expiration date should change to whatever date it was extended to and the status should change to "Active".

**Comment by SubhaShroff** [comment] 2021-11-18 20:53
@Nadin-Nader  @TracyLinder The Permit Extention code is updating the expiry date and status, conditionally. And the codition is looking for 'COA Division'(75942) value exists and its value is not like 'PVT%'. 
I remember in #2397, we have merged COA Division. Should I change this condition check to 'Project Sponsor'(76765)?

**Comment by Sreelatha-BlazeKannan** [comment] 2021-11-18 21:27
@Nadin-Nader @TracyLinder @SubhaShroff - In Extension process 76765 - Project Sponsor info-related code was commented, as per the #6844 AC - " Any functionality based on Info field Project Sponsor (76765) needs to be removed." requirement.

**Comment by TracyLinder** [comment] 2021-11-18 21:39
@SubhaShroff as per our conversation, please remove the condition of the permit extension so we can resolve this bug.

**Comment by SubhaShroff** [comment] 2021-11-18 21:45
@TracyLinder  Will do. But I just realized, that condition is kept for the old permits that are still with COA Division. I will work around that, if the check still needed for the old permits.

**Comment by SubhaShroff** [comment] 2021-11-19 14:29
@TracyLinder  @Nadin-Nader  
The condition is commented and tested on Localhost. Extension days I gave 10 days, it updated to Nov 28th.
SCTASK0181361 - is submitted for DEV deployment of the commit.

![image](https://user-images.githubusercontent.com/51680715/142633267-31c60f98-3a0a-44d9-a435-dde702b1d945.png)
![image](https://user-images.githubusercontent.com/51680715/142633570-5952a78b-75a5-4e24-b710-e5cb9ee80e9d.png)

**Comment by SubhaShroff** [comment] 2021-11-19 17:53
@TracyLinder  @Nadin-Nader  DEV deployment is done. I tested it for the fix. With Extension Granted, the folder status changed to ACTIVE and Expiry date got updated to Nov 23rd (start date I added in process info -11/19 and 5 extension days).
RW TURP - Public Works Department (RSN:11903946) 
![image](https://user-images.githubusercontent.com/51680715/142668860-fca1a9bd-6d68-4ced-968b-0a9f7867b1b7.png)

**Comment by TracyLinder** [comment] 2021-11-19 22:11
### Clarification
**If the TURP work types are (Private Development, Project Connect, Other City Department)**

1. User saves Extension Granted
2. System updates folder infos extension start date and extension end date
3. System inserts extension fees
4. User bills extension fees
5. Invoice is paid (either BO or Portal)
6. System updates folder status, issue date (_extension start date_), expiration date (_extension end date_)

**If the TURP work types are Franchise, ATD, Austin Energy, Austin Water, Corridor Program Office, Public Works, Watershed Protection:**

1. User saves Extension Granted
2. System updates folder infos extension start date and extension end date
3. System updates folder status, issue date (_extension start date_), expiration date (_extension end date_)

**Comment by SubhaShroff** [comment] 2021-11-23 02:47
@TracyLinder  I did the changes for Private Development, Project Connect, Other City Departments.  In localhost I tested it works as expected. In the above comment you haven't mentioned about the fees for COS worktypes, but with Extension Granted - updates happen.
 But ,I think for all types for COS worktypes also Permit Extension fees are adding. How should these fees should be paid? Is it going to be auto payment for these fees as well? if not for these worktypes also we need to follow the same procedure like Private Development: Update the expiry date & status with payment.
Please guide me.

**Comment by Nadin-Nader** [comment] 2021-11-23 21:18
Response to Subha:
Ok so Tracy said to go ahead and send it like that. 

> Tracy Linder  12:39
> All COS fees should automatically be paid but I don’t think the work should be done on 7785
> 
> Nadin Nader  12:40
> soooo should i let Subha know to send as is since the extension features are working on DEV now? (edited) 
> 
> Tracy Linder  12:49
> I think so. Unless she disagrees for some reason.

**Comment by Nadin-Nader** [comment] 2021-11-23 21:18
Subha has made the commit and will be sending it to DevOps CM Team

**Comment by SubhaShroff** [comment] 2021-11-23 21:29
@Nadin-Nader  @TracyLinder SCTASK0182186 is submitted for DEV deployment of the changes as per Tracy's suggestion.

**Comment by SubhaShroff** [comment] 2021-11-23 23:16
### Status:
Waiting for CTM team to do DEV deployment.

**Comment by SubhaShroff** [comment] 2021-11-24 23:27
@Nadin-Nader  @TracyLinder  The DEV deployment is done by EOD. I need to test.

**Comment by SubhaShroff** [comment] 2021-11-29 16:19
@TracyLinder  @Nadin-Nader  Tested it on DEV, and its working as expected. Kindly, let me know your feed back to move it further.

**Comment by Nadin-Nader** [comment] 2021-11-29 16:55
@SubhaShroff lets get this to TEST

**Comment by SubhaShroff** [comment] 2021-11-29 17:26
@Nadin-Nader  SCTASK0182619 - is submitted for TEST deployment of this ticket.

**Comment by Nadin-Nader** [comment] 2021-11-30 15:07
@SubhaShroff this has been deployed to **_TEST_** Please do the initial UAT and let me know if this is ready for the stakeholder to test.

**Comment by SubhaShroff** [comment] 2021-11-30 19:21
@TracyLinder  @Nadin-Nader  Tested Its working as expected.
2021 048827 000 00 RW - Private Development.
2021 047693 000 00 - Corridor Program Office
I noticed - issue date (extension start date) - Though, I missed this part bring up before commit, I realized while testing. The permit status changes to 'Active' today so the issue date shouldn't be today's date?. If not, if it should be extension start date as mentioned in AC, I need to make that change.

**Comment by SubhaShroff** [comment] 2021-11-30 23:40
### Status:
Tested on TEST, came up with one point mentioned in the above comment, that needs review. Otherwise ready for UAT.

**Comment by SubhaShroff** [comment] 2021-12-01 21:14
Since Tracy clarified that Issuedate should be the date Permit is issued  and I have already taken care of it, this is **ready for UAT.**

**Comment by Nadin-Nader** [comment] 2021-12-02 20:57
**UPDATE:**
Tracy spoke with Kim and Paloma and Kim & Paloma just told her that they never want the issue date to change w/ the extension process on both EX & RW.

**Comment by TracyLinder** [comment] 2021-12-02 22:33
I just updated the AC

**Comment by SubhaShroff** [comment] 2021-12-02 23:36
@TracyLinder @Nadin-Nader  Got it. I want to inform you the earlier code logic was as follows:
With Extension Granted - The permit gets activated, along with that Issue Date changed to Today's date and Expired date changed to 'Extension End Date'. (I didn't do that change, it was already in place).  The bug was caused by the condition to check Project Sponsor/COA Division, that was stopping the update.  So I commented that condition to allow the expected original changes to happen.

Now, stakeholders don't want the issue date to be updated with Extension.  So I just wanted a reconfirmation on this, to make sure this change is deliberate.

**Comment by SubhaShroff** [comment] 2021-12-03 15:45
@Nadin-Nader  No update in  issue date  fix is done and committed - 42983299799a.

**Comment by Nadin-Nader** [comment] 2021-12-07 15:23
@SubhaShroff this has been deployed on **_DEV_**, Please UAT and demo

**Comment by TracyLinder** [comment] 2021-12-07 16:44
**Clarification**
Fyi @SubhaShroff 

`As I understand, Other City Department is one of the COS automation payment work types of RW TURP. So, it will change status to Active with Extension Granted(No need to wait for the payment like it is mentioned for Private Development and Project Connect). Please clarify.`
- Correct. I updated the AC.

**Comment by SubhaShroff** [comment] 2021-12-15 03:32
### Status:

- Since AUP related discussions/changes going around, I need to revisit/test if the changes affected this ticket.

**Comment by Nadin-Nader** [comment] 2021-12-17 20:40
@SubhaShroff 
**Status:**
Approved by Paloma and Kim for PROD

**Comment by SubhaShroff** [comment] 2021-12-17 21:48
@Nadin-Nader
SCTASK0187300 - request is created for TEST deployment.
NOTE: This has a commit related to 7283 also. Submitted together in one ticket as these are related tickets and the commits should go together.

**Comment by Nadin-Nader** [comment] 2021-12-21 15:54
**Status:**
This is ready for UAT on **_TEST_**

**Comment by TracyLinder** [comment] 2021-12-22 18:21
I posted in the ROW UAT channel letting kim & paloma know this is ready for UAT.

**Comment by Nadin-Nader** [comment] 2022-01-03 21:17
@SubhaShroff here are the UAT results from Kim one Yesterday:

> [Yesterday 12:29 AM] Perez, Kimberly
>     
> 
> 
> Test Results for 7785
> 
> For all TURP permits, system correctly updated the extension start and end dates. It also added correct extension fees, and worked accordingly to the "Activate Upon Payment" Feature. It updated status and expiration date if marked appropriately and fees were paid. yes
> 
> However, for Private and Project Connect it did not update days of validity correctly (ticket 8015) and also updated issue date when it shouldn't (21-048608 RW and 21-048607 RW). no
> 
> OBSERVATION:
> TURP ROW Usage Fees for Private still not calculating or not able to "insert and run"  after initial review. (not during extension process) (ticket 7829)
> New Payment Website= Made payment on website for private and project connect permits, and received an email for successful payment, but payment was not reflected in AMANDA or on the ABC Portal.

**_Question for Paloma from Kim:_**

>  I only received emailed copies of permits for Private and Project Connect. @Amayo-Ryan, Paloma Should all work types get an emailed copy of their permit? after initial issuance? after extension?

**Comment by Nadin-Nader** [comment] 2022-01-04 17:57
@subha @TracyLinder 
**Status:**
Changes found in the UAT an be made but we cannot test it in TEST due to CTM making changes to the Portal (going from Chase to City Base). Due to this we are unable to test payments in TEST.

Spoke to Deanna and she will ask Swapna for a timeline on when we will be able to test Payments on Portal.

**Comment by SubhaShroff** [comment] 2022-01-07 17:43
@Nadin-Nader  @TracyLinder  SCTASK0191465 is submitted for DEV deployment.

**Comment by SubhaShroff** [comment] 2022-01-10 17:30
@Nadin-Nader  DEV deployment is done. I tested it  for Private and Project Connect it did not update days of validity correctly (ticket 8015) and also updated issue date when it shouldn't (21-048608 RW and 21-048607 RW).

Looks good.  Kindly, let me know if TEST deployment can be done.

**Comment by Nadin-Nader** [comment] 2022-01-10 18:51
@SubhaShroff ok send it to TEST so we can test it

**Comment by TracyLinder** [comment] 2022-01-10 19:18
@SubhaShroff or @Nadin-Nader are you needing any feedback from me on this?

**Comment by SubhaShroff** [comment] 2022-01-10 19:24
No @TracyLinder. 
I am about to submit TEST deployment request for, as @Nadin-Nader  gave approval.

**Comment by SubhaShroff** [comment] 2022-01-10 20:04
@Nadin-Nader  @TracyLinder  SCTASK0191782 is submitted for TEST deployment of the fix.

**Comment by SubhaShroff** [comment] 2022-01-11 23:47
### Status:
Ready for your test on TEST. Please read my latest comment above after latest testing.

**Comment by SubhaShroff** [comment] 2022-01-18 17:56
@TracyLinder 
Question:  In TEST UAT, there was a concern  raised about TURP PVT, PCO by stakeholders. According to them, if AUP=yes, with payment,  PVT & PCO also should get activated. I have understood the workflow, the AUP activate should not trigger irrespective of AUP value.
However, yesterday, with testing and Acceptance Criteria, I realized it - In case of TUPR PVT, PCO -it needs to turn Active with payment if AUP=YES. 
Since the question arised, please clarify it.

**Comment by TracyLinder** [comment] 2022-01-18 17:59
@SubhaShroff 

Great questions. The stakeholders are correct (and you now also) - AUP = yes should trigger to get activated.

**Comment by SubhaShroff** [comment] 2022-01-21 22:20
@Nadin-Nader  @TracyLinder  SCTASK0194842 is submitted for the PROD deployment.

**Comment by SubhaShroff** [comment] 2022-01-24 21:27
@Nadin-Nader PROD deployment is done.

**Comment by SubhaShroff** [comment] 2022-02-02 21:29
@Nadin-Nader  SCTASK0197725 is submitted for DEV deployment of the fix. For PVT, PCO the expiry date was no updating with the payment (of extension fee after permit extension attempt).

**Comment by SubhaShroff** [comment] 2022-02-07 18:16
@Nadin-Nader  Tested the fix on DEV and SCTASK0198200 is submitted for TEST deployment.

**Comment by SubhaShroff** [comment] 2022-02-09 17:08
@Nadin-Nader  SCTASK0198200 is deployed in TEST. I tested it for the bug fix (PVT, PCO) it was not extending. Now it does. We can push this also to PROD with other rolled back commits.

**Comment by SubhaShroff** [comment] 2022-02-14 15:27
@Nadin-Nader @TracyLinder  we are still waiting on the re-deployment of the commits in PROD.

**Comment by TracyLinder** [comment] 2022-03-11 23:30
### PROD UAT PASSED 🎉

@Nadin-Nader can this be closed?

**Comment by Nadin-Nader** [comment] 2022-03-21 16:57
Passed PROD UAT 10 days ago, closing

**Closed by Nadin-Nader** 2022-03-21 16:57 UTC
Labels: Workgroup: ROW, Type: Bug Report, Impact: 3-Minor, Workgroup: CTM, Product: AMANDA, Provider: LaunchIT
