### ISSUE TITLE
[Tech Debt] VZD | Unit metadata | Inconsistent fatality counts between crash total and unit metadata totals

### ISSUE THREAD

**Issue by mddilley** [cityofaustin/atd-data-tech#2413] opened 2020-04-21 21:57 UTC
While styling the crash points on the VZV map, it was noticed that some results with `death_cnt` of 0 returned from Socrata when filtering to fatalities only. When looking at crash ID #`17168802`, the `death_cnt` for the crash record is 0, but the `atd_mode_category_metadata` column contains one unit with a `death_cnt` of 1. The mode filters in VZV use the `death_cnt` from each unit in `atd_mode_category_metadata` and not the `death_cnt` from the overall crash.

#### Other sample records
`17524347`
`17351089`
`17343328`
`16991949`

#### Data returned from Hasura
<img width="420" alt="Screen Shot 2020-04-21 at 2 22 34 PM" src="https://user-images.githubusercontent.com/37249039/79905316-a951ac80-83db-11ea-9045-be809cada86b.png">

**Comment by patrickm02L** [comment] 2021-08-05 19:54
@mateoclarke to review the 5/6 crashes that are listed. 

While reviewing, determine if there's an open issue or issue to create or scope about inconsistent crashes still being a problem. 

There is an ability for reporting (KAB reporting page) but it's limited to Admins. 

Mateo, to create an issue and communicate with Patrick about what needs to be scoped. Patrick will help determine additional user research and what's necessary to understand the problem.

**Comment by patrickm02L** [comment] 2021-12-30 15:24
Had a chat with Frank to assess lift. 

Easy fix would involve writing script to check all `death_cnt ` and change to make consistent. (2)
Heavy fix would involved fixing underlying schema so that this inconsistency doesn't happen. (8)

**Comment by patrickm02L** [comment] 2022-01-07 21:37
This issue may be the cause of what's happening in #6817.

**Comment by patrickm02L** [comment] 2022-01-18 16:12
Ideally this is a data cleanup issue to get the old data to match the current data. 

We will need to craft a query to compare the metadata value by adding up all of the death counts to make sure it adds up to the actual death counts on the crash.

This should give us a small list of crash records that have fallen out of sync that we can clean up. 

If we identify anything newer than April 21st, we should put more time into identifying the reasons it happened, and come up with strategies for future fixes.

**Comment by patrickm02L** [comment] 2022-01-24 21:29
Would have to study what the database looks like. The complexity is about implementation. The metadata can be affected by two types of changes ETL or UI.

**Comment by patrickm02L** [comment] 2022-09-14 15:15
Solution - Write a query that would compute the json blob and write it to disk. This could be a 3, on it's own. But we'd like to wrap it into a set of data quality updates.

**Comment by patrickm02L** [comment] 2023-10-09 19:01
This is blocked by the LDM. Once we have the LDM there will be a calculated "unit_death_cnt" and a calculated "death_cnt" on the "atd_txdot_crashes" table.

**Comment by johnclary** [comment] 2024-02-29 19:49
i'm going to close this since we have https://github.com/cityofaustin/atd-data-tech/issues/15509 and some recent work was done to try to mitigate the situation. 

reporting by mode is still a flawed process and should indeed be resolved by our data model work.

**Closed by johnclary** 2024-02-29 19:49 UTC
Labels: Type: Bug Report, Service: Dev, Workgroup: VZ, Product: Vision Zero Crash Data System, Type: Tech Debt
