### ISSUE TITLE
Duplicate persons caused by CR3 updates

### ISSUE THREAD

**Issue by JaceDeloney** [cityofaustin/atd-data-tech#4623] opened 2020-12-03 19:37 UTC
VZ Team noticed that the persons table for [this crash record](https://visionzero.austin.gov/editor/#/crashes/17953914) has duplicated persons entries. I looked into the CR3 and noticed that the CR3 had been updated twice (there are three CR3s in the PDF). 

Tasks
- Determine what is causing the duplicate persons entries
- Ensure that we do not duplicate any fields when CR3s are updated

**Comment by mateoclarke** [comment] 2020-12-10 18:46
Currently, our ETL process creates a new user if these attributes are unique for a person or primary person:
`crash_id,unit_nbr,prsn_nbr,prsn_type_id,prsn_occpnt_pos_id`

In this case, it looks like that when the updated records were reprocessed, the `prsn_occpnt_pos_id` had updated values from the original insertion. Which caused duplicate records to be created.

At first, I thought this was a limited example but here's a summary of what I found in the two tables:

atd_txdot_person:
There are 181 distinct records that match other records with the same crash_id, unit_nbr, prsn_nbr, prsn_type_id, but with a different person_id.
Including duplicates, there are 336 total records.

Example query:
```sql
SELECT DISTINCT ON (p1.person_id)
	*
FROM
	atd_txdot_person p1,
	atd_txdot_person p2
WHERE
	p1.crash_id = p2.crash_id
	AND p1.unit_nbr = p2.unit_nbr
	AND p1.prsn_nbr = p2.prsn_nbr
	AND p1.prsn_type_id = p2.prsn_type_id
	AND p1.person_id != p2.person_id;
```

atd_txdot_primaryperson:
There are 381 distinct records that match other records with the same crash_id, unit_nbr, prsn_nbr, prsn_type_id, but with a different person_id.
Including duplicates, there are 444 total records.

The proposed solution would be to drop `prsn_occpnt_pos_id` from the unique columns for both indexes: `atd_txdot_primaryperson_unique` & `atd_txdot_person_unique`. This should fix the issue going forward.

And then we'll need to do some de-duplication for the existing records on the tables to clean up our existing data.

**Comment by mateoclarke** [comment] 2020-12-11 04:20
I found crash_id `17953914` with primaryperson and person records that had human updates and with duplicates. I went ahead and deleted the two records that had been updated to sev_id = "Invalid Record".

The rest of the records are system updated duplicates so my strategy will to preserve the most recently updated record where `crash_id`, `unit_nbr`, `prsn_nbr, and `prsn_type_id` are all equal. And delete the old version(s) of the duplicate.

**Comment by mateoclarke** [comment] 2020-12-11 22:59
We discussed next steps in our dev sync 12/11:

- Copy production tables of primaryperson and person to staging as test
- Use this [delete subquery](https://www.postgresqltutorial.com/how-to-delete-duplicate-rows-in-postgresql/) to test deletions on staging
```sql
DELETE FROM basket
WHERE id IN
    (SELECT id
    FROM 
        (SELECT id,
         ROW_NUMBER() OVER( PARTITION BY fruit
        ORDER BY  id ) AS row_num
        FROM basket ) t
        WHERE t.row_num > 1 );
```
- Manual QA to confirm the crashes with duplicate lists looks good and keep for any remaining duplicates that didn't meet the WHERE constraints
- Reproduce in production DB
- Delete test in staging

**Comment by mateoclarke** [comment] 2020-12-12 00:30
See @sergiogcx's example subquery delete SQL command: https://austininnovation.slack.com/archives/CHZE6BC6L/p1607728635298400?thread_ts=1607728074.296300&cid=CHZE6BC6L

**Comment by patrickm02L** [comment] 2021-08-03 16:22
@mateoclarke to follow up on remaining work. Consult with Frank about how to address this.

**Comment by patrickm02L** [comment] 2021-09-27 15:59
@frankhereford can you QA this?

**Comment by frankhereford** [comment] 2021-09-28 21:45
I recommend that we execute the below query and its corollary primaryperson version to remove duplicates. @sergiogcx 's queries, linked above, are an excellent solution and @mateoclarke indicated in the dev sync that he supports running them to remove duplicates. @patrickm02L - with your approval, I'll be happy to execute these (in local, staging and then production), and we can close this issue.

The duplicates have accumulated at about one every two months over the last year, and we accumulated > 95% of the rest of them in a handful of very brief time intervals, which I hypothesize to be an ETL script that was not doing what we expected. It's going to be a challenge to figure out what caused the problem because it only happens once every 60 days or so, and the problem could be upstream of us in TXDOT.

The `atd_txdot_person` table will have ~106 people removed from it, and if you adjust the query to operate on the primaryperson table, you get ~415 duplicate entries to remove out of there. 

```
DELETE FROM atd_txdot_person
WHERE person_id IN (
    SELECT person_id
    FROM  (
        SELECT person_id, crash_id, unit_nbr, prsn_nbr, prsn_type_id, ROW_NUMBER()
            OVER( PARTITION BY crash_id, unit_nbr, prsn_nbr, prsn_type_id ORDER BY person_id DESC) AS row_num
        FROM atd_txdot_person
        ORDER BY row_num
    ) t
    WHERE t.row_num > 1
);
```

There is one very minor change from Sergio's query: That is to specify the sort order to be descending when partitioning up the groups of records. This changes it to keep the youngest (hopefully, most up to date) record in each set of duplicates instead of the oldest, original record. Please let me know if this isn't preferred. 

Thanks!

**Comment by patrickm02L** [comment] 2021-09-29 15:40
@frankhereford yes, please move forward.

**Comment by frankhereford** [comment] 2021-09-29 18:11
I have executed a DELETE sql statement for both `atd_txdot_person` and `atd_txdot_primaryperson` as described above. 106 persons and 415 primarypersons have been removed from the database. Prior to deleting these, I captured the `person_id` and `primaryperson_id` IDs from the respective tables of the rows that were to be removed, so we can inspect a backup and extract the deleted persons should the need arise, [in this attached zip archive,](https://github.com/cityofaustin/atd-data-tech/files/7254131/deleted.IDs.from.person_primaryperson.zip) for as long as we have yesterday's backup.

**Closed by frankhereford** 2021-09-29 18:11 UTC
Labels: Service: Dev, Workgroup: VZ, Product: Vision Zero Crash Data System
