### ISSUE TITLE
Fix CR3 table widgets in location page not updating bug

### ISSUE THREAD

**Issue by JaceDeloney** [cityofaustin/atd-data-tech#3335] opened 2020-07-10 15:37 UTC
Lewis noticed that on the locations page that when the date range of the CR3 crash table is changed, the info on collision type and comp cost and all the rest above isn't updating. 

**Steps to reproduce:**

1. Go to a Location page (helps if you use a location with a lot of crashes)
2. Scroll down to CR3 table
3. Change date range
4. See widgets above not updating

**Comment by mateoclarke** [comment] 2020-09-28 15:07
Duplicate of https://github.com/cityofaustin/atd-data-tech/issues/3607

**Closed by mateoclarke** 2020-09-28 15:07 UTC
Labels: Product: Vision Zero Crash Data System, Service: Dev, Type: Bug Report, Workgroup: VZ
