### ISSUE TITLE
Project: Digital Work Orders for Parking Meters

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#549] opened 2019-09-07 20:55 UTC
Our Parking Enterprise staff currently use a paper-based process for tracking parking meter installations, repairs, and collections. This project will deliver a digital process for the tracking and reporting of these activities.

**Comment by amenity** [comment] 2021-05-06 16:28
Duplicate of #652

**Closed by amenity** 2021-05-06 16:28 UTC
Labels: Need: 2-Should Have, Project Index, Service: Apps, Type: New Application, Workgroup: PE
