### ISSUE TITLE
AWS Migration

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#725] opened 2019-10-22 16:44 UTC
## Description
We're migrating our AWS services from a CTM-owned organization to an ATD-organization. This will enable us to ensure resources are managed securely and consistently across all of our applications.

### Resources
- [Google Drive Project Folder](https://drive.google.com/drive/u/1/folders/1Xf6L9WCGzZv3FfVyTkvOB6AT2x98Vem6)

---
This Github issue represents a project of Austin Transportation's [Data & Technology Services](https://transportation.austintexas.io/about/) team. Project status is documented regularly in the comments below.

**Comment by amenity** [comment] 2020-06-23 20:27
@mateoclarke @johnclary - should this go in the backlog?

**Comment by amenity** [comment] 2020-06-26 20:51
Duplicate of #706

**Closed by amenity** 2020-06-26 20:51 UTC
Labels: Epic, Index, Service: Dev, Status: Active, Type: Other, Type: Tech Debt, Workgroup: DTS
