### ISSUE TITLE
Updates to Providers page

### ISSUE THREAD

**Issue by JaceDeloney** [cityofaustin/atd-data-tech#4658] opened 2020-12-09 18:53 UTC

**Comment by johnclary** [comment] 2021-03-03 20:00
Needs to be further scoped

**Comment by SurbhiBakshi** [comment] 2021-05-12 16:41
Based on the workflow from #5884, the Providers page should include a way for providers to check on impoundments and 311 SRs.

 When 311 SRs for Shared Mobility are incorporated in the system, there should be a way to send out emails to providers to notify them of abandoned vehicles. The providers will need a page to check on details for these 311 SRs. If the issue is not resolved within a set time frame, the vehicle will be impounded by Parking Enforcement. Providers will need to see details on these impoundments and associated fees.

**Comment by SurbhiBakshi** [comment] 2021-05-14 17:25
Other information that could be included on the page for Providers - 
1. Permits
2. Licenses
3. Insurance
4. Provider Contact details so Providers can notify the Shared Mobility team in case of changes.

**Comment by SurbhiBakshi** [comment] 2021-05-14 19:22
Found some documentation in slide 8 of this [deck.](https://docs.google.com/presentation/d/15EpSHdta8j_SYAoO3ID-6NIeTdDDAsLJ1GIts_iERFI/edit?usp=sharing)

**Comment by SurbhiBakshi** [comment] 2021-05-14 20:28
and some more information in this [User Stories documentation](https://docs.google.com/spreadsheets/d/1AXkKZ-CTR-nKnoujVYslnD40r_1P3b250ItDCUAg-Lk/edit?usp=sharing)

**Comment by SurbhiBakshi** [comment] 2021-05-14 20:52
Based on what I have read so far, it sounds like there are two pages that are called Providers page - 
1. One that the SMO team will reference for information on licenses, permits, bonds, monthly trips and fees, MDS, 311 SRs and impounds for each provider. This could be a table for all Providers and then the details tab leads to this information for each provider.This was built into the application when it was in the prototype stage and might need to be updated.
2. The other tab (which should be called something different) is where provider contacts log in to look at their license, permits, bond, monthly trips and fees, 311 SRs, impounds and ACH information. Potentially they could also use this page to attach documents and communicate with the SMO team, for example when renewing permits or licenses, or dealing with 311 SRs.

**Comment by amenity** [comment] 2021-06-23 18:35
This isn't relevant anymore - some has been addressed in other issues.

**Closed by amenity** 2021-06-23 18:35 UTC
Labels: Product: Shared Mobility Operations, Service: Apps, Type: Feature, Workgroup: PE
