### ISSUE TITLE
Knack Citybase integration Revenue Management UAT

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#10370] opened 2022-10-03 15:26 UTC
Email from Eva
I've added you to the Citybase Revenue Management UAT system. I will not be the one to set you up in the Production system.  For that, you will need to email ADV-Security and request the Revenue Management production access form.

You will need to provide the name of the employee, their email address, and the role in which to assign them.  CV J who manages ADV-Security can help explain the roles to you.  For UAT, I assigned Diana M as the Agency Admin, Chia B as the Supervisor, and Stephanie M as the Researcher.

When you are ready to start UAT testing, I recommend you submit one form for all your employees to your designated SPOC.  Your SPOC will approve it and send the filled out form back to ADV-Security.

To access Revenue Management 
      In UAT, use this link:  https://revenue-management-dashboard-austin-tx.uat.cityba.se/login
      In Production, use this link:  https://revenue.thecitybase.com/login

UAT and Production webpage will look the same.  The only way to tell if you are in production or UAT is in the URL, you will see "uat" in the URL for the non-production system.

To create your password for the first time, use the "Forgot password" link.  It will send you an email to set up your password.

If you have any questions, please email ADV-Security (CV J, or Maura V).

**Comment by moorerst** [comment] 2022-10-03 16:40
You all already have Revenue Management UAT access. The form is for production Revenue Management. I recommend going ahead and getting the production form filled out because you will be rushed between UAT and Prod waiting for setup.

Just determine who will be the administrator for ATD who will have the ability to issue voids and refunds, plus create user accounts for your department. Supervisors can also issue voids and refunds but cannot create accounts. Researcher is a read only account. 
You may want to submit just one form for your entire group.
 
Will complete form and submit to SPOC

**Comment by moorerst** [comment] 2022-10-04 14:57
completed and submitted the Citybase Revenue Management security request form

**Comment by moorerst** [comment] 2022-10-05 14:15
Reply from Eva: 
The form  needs to be sent to the ATD SPOC for approval.  The SPOC will send the approved form to ADV-Security.  Are you the SPOC for ATD?

 @dianamartin do you know what ATD SPOC Eva is referring to?

**Comment by dianamartin** [comment] 2022-10-05 14:34
@moorerst Maybe ATD IT SPOC? that would be Scott or Brian C.?

**Comment by moorerst** [comment] 2022-10-17 16:54
@dianamartin @chiaberry 
In the UAT Citybase Revenue Management system I'm seeing one transaction. It looks to me like the Description and Sub Description have the information we wanted to display:

![image](https://user-images.githubusercontent.com/56606465/196236941-2a55f6c4-abcb-466d-9b58-c367ad48fbac.png)
![image](https://user-images.githubusercontent.com/56606465/196237085-ac061a12-5386-47d8-9c6f-f940f24565f5.png)

**Comment by dianamartin** [comment] 2022-10-17 17:15
@moorerst whoa, cool! I hadn't logged in this week to see anything.

**Comment by dianamartin** [comment] 2022-12-05 20:38
# 12/5

- We have completed the initial two UAT sessions (11/14-11/15)with the stakeholders in the Test Environment. 
- We had a UAT review session 11/17 that revealed more fixes for me and Chia. 
  - We handled those issues
  - As a group we also did 3 production transactions to see how they moved along the workflow
  - the only issue is the ACH payment, missing the transaction fee getting into the COA accounts
- Had a third UAT session on 11/29

**Comment by dianamartin** [comment] 2023-01-09 16:30
Closing this issue, because I was able to review remittance file of this last transaction that CityBase made. Gail from FSD confirmed payment was received. 
>I’m confirming the City received the $10.00 ACH deposit on 1/3/23. Looks like we are good to proceed with processing refunds now.

**Closed** 2023-01-11 16:17 UTC
Labels: Workgroup: SMD, Service: Dev, Service: Apps, Service: Product, Type: Testing, Workgroup: SMO, Product: Banners
