### ISSUE TITLE
SIF - SIF Required Info on PR folder

### ISSUE THREAD

**Issue by vschandramouli** [cityofaustin/atd-data-tech#9223] opened 2022-05-20 16:44 UTC
**Acceptance Criteria** 

- The acceptance criteria provided below applies to PR folders only. 
- When a new PR folder is created of subtype R101 or R103, system needs to check to see if there is an existing PR folder of subtype R645, R646 or R2001 on the primary property chosen for the folder. 
-- If yes, no further action is required 
-- If no, system needs to default the value of info field 'SIF Required?' on the PR folder to 'Yes'.

**Comment by vschandramouli** [comment] 2022-05-20 17:06
Updated AC moving to Backlog for Sree.

**Comment by TracyLinder** [comment] 2022-06-23 19:04
Duplicate of #9451. Closing

**Closed by TracyLinder** 2022-06-23 19:04 UTC
Labels: Workgroup: DTS, Service: Product, Project: Street Impact Fee Implimentation
