### ISSUE TITLE
Add codes to AMANDA for three missing ATD review fees (TL)

### ISSUE THREAD

**Issue by SurbhiBakshi** [cityofaustin/atd-data-tech#2401] opened 2020-04-20 20:17 UTC
### As a project manager, when adding folder fees to C8, C14, SP, or ZC folders, I want all Transportation Review fees available on the Insert & Run fee procedure on the fee tab. 

**Acceptance Criteria**
- Insert & Run procedure adds a fee with the correct amount for these 7 missing fees:
    - ![image](https://user-images.githubusercontent.com/49930868/86079847-14aca000-ba57-11ea-8fc2-f97d43841708.png)
- The 7 missing fees are added to these folders: C8, C14, SP, or ZC

---------

**Previous Description:**
- Some of the fees Sangeeta refers to are not included in the spreadsheet I got from George. I have asked Sangeeta to identify which ones.
- Sent in a ticket to deploy the fees that exist in Test to Prod. (after UAT with Zach W and Roderick B) - #2292, #2293, #2294
- Once Sangeeta gets us the fees that were not in George's spreadsheet or do not exist in Prod, start process to get those in Amanda.

**Comment by SurbhiBakshi** [comment] 2020-04-20 20:39
![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/466bc7ce-a7b0-4a0a-bd13-c175ce49b594)

**Comment by amenity** [comment] 2020-04-27 15:52
Sangeeta verified that these fees are in Production, but the fee amounts (shown in screenshot above) needs to be added. Sree thinks that this is a low effort and that @Nadin-Nader can see about adding them directly to Production. 

Add fees to these folders:
- Site plan
- Subdivision
- Zoning case

**Comment by TracyLinder** [comment] 2020-04-30 20:06
Reading through the notes & talking to Surbhi, it seems like these fees are valid but are missing fee procedures. Need to follow up with LIT to see where this is.

**Comment by TracyLinder** [comment] 2020-06-07 04:43
### Email to Sangeeta, asking for status, 6/6/20:

Hi Sangeeta,

I hope you are doing well. I'm writing because I see we have two stagnant tickets for your group related to fees in AMANDA. It looks like they were close to done, and then got lost in the shuffle when I came back to work from my medical leave. See the ticket info below; can you please tell me if either of these have been resolved for your team? 

#2293 TDS Fees in AMANDA - Opened on April 8th, your team asked us to make sure Roderick's group with DSD could add ATD review fees, using their normal process to add fees, to these folders: C8, C14, SP, ZC. 
#2401 Three Missing ATD Review Fees - I'm not sure what the scope of this request is. It looks like it covers fees that were missed for ticket 2293.

All the Best,

Tracy Linder, Product Manager

**Comment by TracyLinder** [comment] 2020-06-11 20:20
Per Sree, she'll be sending a demo for this soon.

**Comment by TracyLinder** [comment] 2020-06-17 00:00
Sree sent us a demo on 6/11. I responded today 6/16 asking her to move this work to Dev.

**Comment by TracyLinder** [comment] 2020-06-17 19:42
**Status:** Move request should be submitted today.

**Comment by SubhaShroff** [comment] 2020-06-17 21:29
Submitted Dev promotion request :SCTASK0075249 along with Dev Deployment Plan.

**Comment by Nadin-Nader** [comment] 2020-06-17 23:39
**Status:**
Verified and found that the TASK for the CM Team was made and is on their Trello Board in their initial entry column "To-Do". This should be promoted today or tomorrow since it is a DEV deployment

**Comment by licarir** [comment] 2020-06-18 14:37
@Nadin-Nader They sent a weird task to our board. Can you review and let us know what to do with it? It doesn't mention Commits or a Deployment plan or anything.

SCTASK0075245

**Comment by SubhaShroff** [comment] 2020-06-18 14:45
> @Nadin-Nader They sent a weird task to our board. Can you review and let us know what to do with it? It doesn't mention Commits or a Deployment plan or anything.
> 
> SCTASK0075245
@licarir @Nadin-Nader I had created SCTASK0075245 , this TASK needs to be open, to keep the REQ0053201 open, until #2401 is moved to PROD. Otherwise no action is needed.

**Comment by Nadin-Nader** [comment] 2020-06-18 15:51
@licarir i will look into it as this is supposed to be on the CM Team board

**Comment by Nadin-Nader** [comment] 2020-06-18 16:05
@licarir  Im am going to close SCTASK0075245 as a duplicate of SCTASK0075249 which has the deployment attached and is in the CM DevOps Team board in their TO- DO Pipeline. 

Please go ahead and close the card.

**Comment by Nadin-Nader** [comment] 2020-06-22 16:09
**Status**
In the CM Teams "In Progress" Pipeline SCTASK0075249

**Comment by SubhaShroff** [comment] 2020-06-22 20:46
**Status**
The changes are deployed and I have tested it in Dev. It is available for Dev Testing.

**Comment by TracyLinder** [comment] 2020-07-01 19:35
**Status:** User testing on DEV coming up.

**Comment by TracyLinder** [comment] 2020-07-08 18:27
Users approved the move to Test. Sangeeta wants to test in Test before moving to Prod.

**Comment by SubhaShroff** [comment] 2020-07-08 20:08
A ServiceNow Request is submitted for TEST deployment along with the Deployment Plan: SCTASK0080280.

**Comment by Nadin-Nader** [comment] 2020-07-10 17:28
@SubhaShroff please let me know when you send this to get promoted to PROD so we can make sure a TASK is put into CTM to add the lookups to PROD as i dont have permissions on PROD to add them

**Comment by SubhaShroff** [comment] 2020-07-10 18:50
@Nadin-Nader @TracyLinder I tested it in TEST. Once you approve, I will submit the request for PROD deployment. @Nadin-Nader sure, I will let you know when I submit SN request.

**Comment by TracyLinder** [comment] 2020-07-15 16:16
@SubhaShroff @Nadin-Nader just a reminder that the customer (Sangeeta) wants to do some testing before this is approved for Prod.

**Comment by TracyLinder** [comment] 2020-07-15 17:05
**Email to Sangeeta & Nate A.:**

Hi Sangeeta & Nate,

The work for #2401 to add the 7 missing fees to AMANDA is now in Test. Sangeeta you mentioned you wanted to do some independent testing on this before we move it to production. Is this something you’d like to do together, or alone? I can set up a quick teams meeting if you’d like. 

All the Best,

Tracy Linder, Product Manager
Data & Technology Services 🚲 Austin Transportation
————————————————————————

**Comment by TracyLinder** [comment] 2020-07-15 17:07
**Status:** The development work for this has been completed by Launch IT, and is pending customer UAT before promoting to Prod. I'm leaving this in sprint 28.

**Comment by TracyLinder** [comment] 2020-07-15 18:09
**From Sangeeta (I'll need to look into this)**

Hi Tracy,

I just signed on to AMANDA test.  It looks like the following 2 fees are missing:  ATD-SUB-Final Plat and ATD-SUB-Preliminary Plan
The rest seem to be working well.  Thanks 

Sangeeta

**Comment by SubhaShroff** [comment] 2020-07-16 13:49
Missing fees(ATD-SUB-Final Plat and ATD-SUB-Preliminary Plan), Sangeeta has mentioned doesn't look like part of #2401. Is there is any other issue linked to it for (ATD-SUB-Final Plat and ATD-SUB-Preliminary Plan fees)?

**Comment by TracyLinder** [comment] 2020-07-16 19:19
@SubhaShroff @Sreelatha-BlazeKannan 
We just talked to Sangeeta about this. It looks like these 2 fees were missed as requirements, so this is new info. The fee names, amounts, and GL info are below. 
**Question:** Would you prefer to add these two fees as part of this ticket, or separately from this ticket? 

- ATD-SUB-Final Plat is $1310.00
- ATD-SUB-Preliminary Plan is $2920
- GL Account #'s match the other 7 fees

**Comment by SubhaShroff** [comment] 2020-07-16 19:50
@TracyLinder @Sreelatha-BlazeKannan Making a new ticket would be fine for the missing fees, I think.

**Comment by Sreelatha-BlazeKannan** [comment] 2020-07-17 14:16
@TracyLinder - I would recommend a new ticket for this as we cant revert and redo the whole thing again. There are nearly 50 PROCS involved in this change including Stand alone procedures.

**Comment by TracyLinder** [comment] 2020-07-17 21:12
@Sreelatha-BlazeKannan @SubhaShroff 

I created a new ticket for the 2 missing fees #3447. 

### This work is approved to move to Prod! 🎉

**Comment by SubhaShroff** [comment] 2020-07-17 22:15
@TracyLinder @Nadin-Nader following Prod Deployment Requests are submitted.
SCTASK0082880: To deploy the commits 6408b874de69, 9e7caff43caf
SCTASK0082881: To do manual deployment of lookup values.

**Comment by SubhaShroff** [comment] 2020-07-23 21:54
@TracyLinder @Nadin-Nader @Sreelatha-BlazeKannan  This is deployed in PROD.

**Comment by Sreelatha-BlazeKannan** [comment] 2020-07-27 18:13
@Nadin-Nader , @TracyLinder  - Successfully moved to PROD; Can be closed

**Comment by TracyLinder** [comment] 2020-07-27 20:32
**Email sent to Sangeeta:**

Hi Sangeeta,

I hope you are doing well! This is a quick note to let you know that the work performed on #2401 to add 7 missing fees to your folders has been moved to Production, and is ready for your team to use. (Screenshot of the ticket below.) Can you please let your team know?

We have opened a separate ticket for the other 2 missing fees; Sree and her team are working on that now. 

Please let us know if there are any concerns or questions. 

All the Best,

Tracy Linder, Product Manager
Data & Technology Services 🚲 Austin Transportation
————————————————————————

**Closed by TracyLinder** 2020-07-27 20:32 UTC
Labels: Epic, Need: 1-Must Have, Product: AMANDA, Provider: LaunchIT, Workgroup: TDSD
