### ISSUE TITLE
Bug: Non-CR3s not being associated to locations

### ISSUE THREAD

**Issue by JaceDeloney** [cityofaustin/atd-data-tech#4493] opened 2020-11-17 22:47 UTC
Xavier noticed that many of the non-CR3s that he uploaded earlier today are not being associated to a location_id even though it is clear that they are at an intersection. Here's are a couple examples:
- select position from atd_apd_blueform where case_id in (203031079, 162600566)

I'm curious if this is actually a bug, or if the ETL that associates non-CR3s to locations runs on a nightly basis.

**Comment by sergiogcx** [comment] 2020-11-18 17:03
Thank you Jace, will take a look. I know we updated the location assignment function in the database, and I think that's our primary suspect.

**Comment by sergiogcx** [comment] 2020-11-18 19:06
I think I found the main issue & I can confirm there was a bug: Hasura was not able to find the function it needs to associate the crash to a location. Not sure how this function was deleted, it was not present in the database. I recreated it by pulling it from staging, and the function is working again.

It remains to be seen whether this fixes the problem, I need to do some testing with those records and I will report back.

**Comment by sergiogcx** [comment] 2020-11-18 19:25
For case_id 203031079, it seems that no location is found for those coordinates:

SELECT * FROM atd_apd_blueform WHERE case_id = 203031079; -- Shows the record
SELECT * FROM find_noncr3_mainlane_crash(203031079); -- It returns empty, meaning it the crash did not happen on a mainlane
SELECT * FROM find_location_for_noncr3_collision(203031079); -- It returns empty, meaning the crash does not happen within any locations in the database.


For case_id 162600566, it appears it happened on main lane area, so this is considered a Level 5 and therefore it is intentionally not assigned to any locations:

SELECT * FROM atd_apd_blueform WHERE case_id = 162600566; -- Shows the record,
SELECT * FROM find_noncr3_mainlane_crash(162600566); -- Shows one record, meaning it does fall on a main lane.
SELECT * FROM find_location_for_noncr3_collision(162600566); -- Shows one location it belongs to, but this is intentionally ignored because it happened on a level 5 area.

**Comment by sergiogcx** [comment] 2020-11-18 20:15
Ok, another issue I discovered, in case_id 200901186 (It happened on Parmer and Dessau)

The record shows it is assigned:
```sql
SELECT longitude, latitude, location_id FROM atd_apd_blueform WHERE case_id = 200901186;
/* This returns: -97.648592,30.387004,36CD245FAC. Notice it has a location assigned to it./
```

There is a function called `find_location_for_noncr3_collision`, it determines what location a crash needs to be assigned to. This function has been updated by Frank, and it appears it does not find the location for this record. What this means is that given Frank's updates, this crash should not be part of this location.

```sql
SELECT atl.* FROM atd_apd_blueform AS aab
  INNER JOIN atd_txdot_locations AS atl
             ON ( 1=1
                 AND (atl.shape && st_setsrid(ST_POINT(aab.longitude, aab.latitude ), 4326))
                 AND ST_Contains(atl.shape, st_setsrid(ST_POINT(aab.longitude, aab.latitude ), 4326))
                 AND (atl.level_1 > 0 OR atl.level_2 > 0 OR atl.level_3 > 0 AND atl.level_4 > 0) /* <--- this is Franks new line */
                 )
WHERE 1=1
  AND aab.case_id = 200901186
```

**Whenever I remove that line, the function works as expected. I do not know if this is a level 5 polygon, if it not, then we have an issue that needs solving.**

**Comment by sergiogcx** [comment] 2020-11-18 20:25
In short, this is my report:

(a) someone removed the function find_noncr3_mainlane_crash , I do not know who did it or how that happened. This has been fixed, and I can confirm location re-assignment is now working, with some odd observations though.
(b) Frank made an update to the function find_location_for_noncr3_collision  which determines what location a non-cr3 crash belongs to, I think the function is having problems identifying Level 5 locations, but I am not sure. [Is this location a level 5?](https://visionzero.austin.gov/editor/#/locations/36CD245FAC)
(c) We need to re-do all location assignments for Non-CR3s, the nightly job only looks for crashes that do not have a location already assigned, any records with a location will be left alone.

**Comment by sergiogcx** [comment] 2020-11-24 15:46
This is taken care of, will close now.

**Closed by sergiogcx** 2020-11-24 15:46 UTC
Labels: Product: Vision Zero Crash Data System, Service: Dev, Type: Bug Report, Workgroup: VZ
