### ISSUE TITLE
User Management | Hide "New Project" button from viewer role

### ISSUE THREAD

**Issue by mddilley** [cityofaustin/atd-data-tech#5253] opened 2021-02-10 22:50 UTC
Currently, the viewer role can see the button to create a new project but does not have permission to navigate to the`/moped/projects/new` so they are redirected to the dashboard page when they click it. This is confusing, and viewers should not even see that button in the first place.

- Check permissions to see if that is where the problem is
- Use the Can component to wrap the "New Project" button and make sure that only editors and admins can see it

![Screen Shot 2021-02-10 at 4 32 47 PM](https://user-images.githubusercontent.com/37249039/107582715-8b01ab00-6bbf-11eb-821b-8c7ad5bc5f67.png)

**Comment by chiaberry** [comment] 2021-07-26 14:48
@amenity This should be fixed because I added a permission check to the button when I moved it to the navigation bar

**Comment by amenity** [comment] 2021-07-26 23:17
@chiaberry confirmed that this works when I log in as a viewer! Nice. Thanks.

**Closed by amenity** 2021-07-26 23:17 UTC
Labels: Product: Moped, Project: Moped v1.0, Service: Dev, Type: Bug Report
