### ISSUE TITLE
Project: DAPCZ Agenda Management Tool

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#631] opened 2019-09-30 16:29 UTC
## Description
The DAPCZ agenda tool currently in use by Right of Way Management is a non-intuitive Microsoft Word document. Staff and stakeholders need a tool that will foster the coordination the DAPCZ processes depend on. 

### Resources

---
This Github issue represents a project of Austin Transportation's [Data & Technology Services](https://transportation.austintexas.io/about/) team. Project status is documented regularly in the comments below.

**Comment by johnclary** [comment] 2019-10-14 00:03
@TracyLinder this looks like a dupe of #93. I'm going to drop the 'Index' label from this one. Feel free to merge notes/close/etc. Thanks.

**Closed** 2019-10-28 18:27 UTC
Labels: Duplicate, Index, Project: DAPCZ Agenda Tool, Workgroup: ROW
