### ISSUE TITLE
[Feature] Finance and Purchasing Integration

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#4837] opened 2021-01-05 07:36 UTC
Integrate with DTS' Finance and Purchasing Knack app.

**Comment by johnclary** [comment] 2021-04-13 03:21
@amenity closing as a dupe of [#4530](https://github.com/cityofaustin/atd-data-tech/issues/4530)

**Closed by johnclary** 2021-04-13 03:21 UTC
Labels: Epic, Product: Moped, Type: Feature

**Comment by johnclary** [comment] 2021-04-13 04:12
Ah, just realized this is the epic on the v1.0 roadmap. @amenity i don't want to mess that up any further so FYI sorry.

**Comment by amenity** [comment] 2021-04-13 15:15
@johnclary - no I was about to do the same thing.
