### ISSUE TITLE
SIF District FDU Mapping

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#8839] opened 2022-04-05 16:49 UTC
### We need to map each SIF district value to the correct FDU for that district. 
- How do we make sure that when the fee is paid, the correct GL code is chosen?

**Comment by vschandramouli** [comment] 2022-04-14 18:52
Duplicate of #8906 . Closing.

**Closed** 2022-04-14 18:53 UTC
Labels: Type: Feature, Need: 1-Must Have, Product: AMANDA, Project: Street Impact Fee Implimentation
