### ISSUE TITLE
Get cookies daily to download CR3s

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#7815] opened 2021-11-24 20:19 UTC
@frankhereford Please fill in the details describing the process for getting cookies in case others would need to take over this task.

**Comment by frankhereford** [comment] 2021-11-29 19:09
@patrickm02L - sure thing, thank you for creating this issue to document the process. I am hopeful we'll be doing this only for a fairly limited time. It's also worth nothing, that as of the time of writing (2021-11-29), we have not resolved our sourcing of new crash data from CRIS after their recent software upgrade, and therefore, there have not been new crashes which require the process described below to be executed. However, once that stream of new crashes resumes, this will be our way of downloading CR3 PDF files until we are able to either code up or coordinate a permanent solution with the folks who run CRIS. @mateoclarke has been leading the communication efforts with the team at TxDOT.

Anyway: Here are the steps for downloading the CR3s for the time being:

1) We'll be working out of the `flh_7801_cr3_downloading` branch in the VZ repo. It is unlikely that this branch will ever be PR'd into the `master,`; it's more of a place to hold the work-around until we come up with a better, long term solution.
1) We'll be using the docker image defined by the `Dockerfile` in the VZ repo in the `atd-etl` directory. Build that as usual. I tag my local copy as `vz_etl`.
1) I invoke it from the `atd-etl` directory with this command, but this may vary by user or preference. ``docker run -it -p 5555:5555 -v `pwd`/app:/app -v `pwd`/data:/data -v /tmp:/app/tmp --env-file ~/secrets/vz_etl/etl.production.env vz_etl``
1) This should dump you in a `bash` shell on that docker container. 
1) Now, we'll need to get a set of cookies from an authenticated session at CRIS. In a web browser, open up https://cris.dot.state.tx.us/. Login using the entry for `CRIS Search` as found in 1Password.
1) Once logged in, open up your developer tools and switch to the 'Network' tab.
1) Reload the page and in the developer tools, look for the originating HTTP request to `home`, and click on it to explore the headers of the request and response. Copy the value for the Request Header `cookie:` to your clipboard, like this:

![cookie_header_string](https://user-images.githubusercontent.com/3653206/143926349-d7cd633e-d4c8-4e11-b9b4-bbdf5fbd367f.jpg)

8) Back to that shell you have running in the docker container you built earlier. Execute the program `/app/process_cris_cr3.py`. You will be asked by the program to paste in the cookies you copied out of the development console in the previous step. 
9) The program will query Hasura for a list of crashes for which we need to download CR3s, and it will use the string of cookies you provided to download them from CRIS and store them in the usual manner. 

That's about it! Please feel free to get in touch with if there's anything that I can clarify in these instructions or otherwise help.

**Comment by mateoclarke** [comment] 2021-11-30 00:57
I emailed TXDOT a follow-up note today and I plan to call them first thing tomorrow.

**Comment by mateoclarke** [comment] 2021-11-30 04:38
@frankhereford, when I try to repeat your steps in staging, I get this error 

```
Initializing Execution Thread Pool:
Error: can only concatenate str (not "dict") to str
Error: can only concatenate str (not "dict") to str
Error: can only concatenate str (not "dict") to str
```

The explanation about how to retrieve the Cookie and the user input prompt added to the program is nice. I just think something is going wrong for me in the thread pool loop and I'm not sure how to troubleshoot. Could we pair on it in the next day or so?

**Comment by frankhereford** [comment] 2021-11-30 04:41
> The explanation about how to retrieve the Cookie and the user input prompt added to the program is nice. I just think something is going wrong for me in the thread pool loop and I'm not sure how to troubleshoot. Could we pair on it in the next day or so?

@mateoclarke - you bet! Thanks for checking it out. It's rough around the edges, and I'm thankful for you finding something I need to polish up. I totally am looking forward to pairing with you on it whenever is good for you, and I'll give it a first-pass tomorrow morning to see if I can remedy the problem too. Thanks for the heads up! 🙏

**Comment by frankhereford** [comment] 2021-11-30 20:38
> @frankhereford, when I try to repeat your steps in staging, I get this error ...

@mateoclarke - Got this one figured out. This was an oversight on my part. I had changed the name of an argument in the `process_crash_cr3` function definition in `helpers_cr3.py`. I also had a bunch of debugging statements in there as well -- which I intended to use to double-triple check my work once we had our CRIS issue worked out and had some new crashes to test on. Since I had those debugging statements in there, I had withheld committing the file to avoid putting my noise in the permanent record, but, of course, there was the argument name change that actually did need to get committed. 

Commit [930e70a2](https://github.com/cityofaustin/atd-vz-data/commit/930e70a225bffa272a2e6e41ca063c3e84c837f0) makes this work again. Sorry about that! Thanks again for testing out the tool.

**Comment by mateoclarke** [comment] 2021-12-01 09:08
Test now on staging and all ✅ . Hope we get some new records this week so we can run this on production ASAP.

**Comment by frankhereford** [comment] 2021-12-02 20:14
Good news 📰 - The semi-manual method we have come up with to download CR3s worked as expected today and downloaded the CR3s we needed for the new crashes that have recently come in. Thank you to @mateoclarke for working with CRIS on getting that data stream restored and for your thoughts and help related to the PDF portion.

I am scheduling a reoccurring event to invoke this script first thing in the morning, and I look forward to our discussions to return to our fully automated state. 

I have also spoken @chiaberry and she has confirmed that the OCR DAG remains active and we should see these new CR3s get processed. Thanks!

**Comment by patrickm02L** [comment] 2021-12-02 20:19
Put this on the agenda to talk about at next week's Vision Zero Sprint Review.

**Comment by mateoclarke** [comment] 2021-12-03 23:56
Going to close this since the immediate work required to get us to a temporary solution is resolved but I've opened a WIP PR to capture this work and documentation. https://github.com/cityofaustin/atd-vz-data/pull/1048

**Closed by mateoclarke** 2021-12-03 23:56 UTC
Labels: Type: Other, Impact: 2-Major, Service: Dev, Need: 1-Must Have, Workgroup: VZ, Product: Vision Zero Crash Data System
